package org.guce.siat.core.ct.util;

/**
 *
 * @author ht
 */
public interface PottingReportConstants {

    String PVE_ATTACHMENT_TYPE = "PVE";

    String PVE_AUTHORIZATION_NUMBER_FILE_FIELD = "NUMERO_AUTORISATION";

    String PVE_AUTHORIZATION_DATE_FILE_FIELD = "DATE_AUTORISATION";

    String PVE_SUPERVISOR_FILE_FIELD = "SUPERVISEUR_OPERATION";

    String PVE_NUMBER_FILE_FIELD = "PV_EMPOTAGE_NUMERO";

    String PVE_SIGNATORY_FILE_FIELD = "PV_EMPOTAGE_SIGNATAIRE";

    String PVE_DATE_FILE_FIELD = "PV_EMPOTAGE_DATE";

    String PVE_TA_NUMBER_FILE_FIELD = "PV_EMPOTAGE_NUMERO_AT";

    String PVE_TA_DATE_FILE_FIELD = "PV_EMPOTAGE_DATE_AT";

    String PVE_APPOINTMENT_DATE_FILE_FIELD = "DATE_RDV_FINALE";

    String PVE_POTTING_END_DATE_FILE_FIELD = "DATE_EMPOTAGE_EFFECTIF";

}
