/*cette procedure permet d'affecter l'ID maximal d'une table à une sequence.*/
CREATE OR REPLACE PROCEDURE SET_SEQUENCE_VAL_FROM_TABLE(
    SEQUENCE_NAME IN VARCHAR2,
    TABLE_NAME    IN VARCHAR2)
IS
  L_MAX_VALUE NUMBER;
BEGIN
  EXECUTE IMMEDIATE 'SELECT MAX(ID)            
FROM '||TABLE_NAME INTO L_MAX_VALUE;
  EXECUTE IMMEDIATE 'DROP SEQUENCE '||SEQUENCE_NAME;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE '||SEQUENCE_NAME||'                                 
START WITH ' || L_MAX_VALUE || ' INCREMENT BY 1                                 
NOMAXVALUE                                 
NOCYCLE                                 
NOCACHE';
  DBMS_OUTPUT.PUT_LINE('THE NEXT VAL IS : '||(L_MAX_VALUE+1));
EXCEPTION
WHEN OTHERS THEN
  RAISE_APPLICATION_ERROR(-20001,'OBJECT NOT FOUND - '||SQLCODE||' -ERROR- '||SQLERRM);
  ROLLBACK;
END;