-------------------------------------------------------------------
------ Permetre à un agent de cotation de traiter un dossier ------
-------------------------------------------------------------------

-- STEP_AUTHORITY : 1er Agent Cotation
INSERT INTO STEP_AUTHORITY (STEP_ID, AUTHORITY_ID) VALUES (112, 6);
-- STEP_AUTHORITY : 2e Agent de Cotation
INSERT INTO STEP_AUTHORITY (STEP_ID, AUTHORITY_ID) VALUES (112, 7);
-- STEP_AUTHORITY : 3e Agent de Cotation
INSERT INTO STEP_AUTHORITY (STEP_ID, AUTHORITY_ID) VALUES (112, 8);
-- STEP_AUTHORITY : 4e Agent de Cotation
INSERT INTO STEP_AUTHORITY (STEP_ID, AUTHORITY_ID) VALUES (112, 9);
-- STEP_AUTHORITY : 5e Agent de Cotation
INSERT INTO STEP_AUTHORITY (STEP_ID, AUTHORITY_ID) VALUES (112, 10);
-- STEP_AUTHORITY : 6e Agent de Cotation
INSERT INTO STEP_AUTHORITY (STEP_ID, AUTHORITY_ID) VALUES (112, 11);

COMMIT;

-- Décision Autorisation AP Suite Etude Recevabilité Agent Cotation 1
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_AP_169', 24, 0, 'Autorisation AP Suite Etude Recevabilite', 'Autorisation AP Suite Etude Recevabilite', 0, 105, 102 );
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_AP_175', 24, 0, 'Rejet Suite Etude AP', 'Rejet Suite Recevabilité', 1, 105, 101 );
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_AP_176', 24, 0, 'Complément d''information Suite Etude Recevabilité', 'Complément d''information Suite Etude Recevabilité', 1, 105, 100 );

INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_AP_187', 24, 0, 'Réponse CI Suite Etude AP', 'Réponse CI Suite Etude AP', 0, 100, 105 );


-- Décision Autorisation AP Suite Etude Recevabilité Agent Cotation 2
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_AP_170', 24, 0, 'Autorisation AP Suite Cotation 1', 'Autorisation AP Suite Cotation 1', 0, 106, 112 );
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_AP_177', 24, 0, 'Rejet Suite Cotation', 'Rejet Suite Cotation', 1, 106, 101 );
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_AP_178', 24, 0, 'Complément d''information Suite Cotation', 'Complément d''information Suite Cotation', 1, 106, 100 );

INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_AP_188', 24, 0, 'Réponse CI Suite Etude AP', 'Réponse CI Suite Etude AP', 0, 100, 106 );



-- Décision Autorisation AP Suite Etude Recevabilité Agent Cotation 3
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_AP_171', 24, 0, 'Autorisation AP Suite Cotation 2', 'Autorisation AP Suite Cotation 2', 0, 107, 113 );
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_AP_179', 24, 0, 'Rejet Suite Etude AP', 'Rejet Suite Recevabilité', 1, 107, 101 );
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_AP_180', 24, 0, 'Complément d''information Suite Etude Recevabilité', 'Complément d''information Suite Etude Recevabilité', 1, 107, 100 );

INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_AP_189', 24, 0, 'Réponse CI Suite Etude AP', 'Réponse CI Suite Etude AP', 0, 100, 107 );



-- Décision Autorisation AP Suite Etude Recevabilité Agent Cotation 4
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_AP_172', 24, 0, 'Autorisation AP Suite Cotation 3', 'Autorisation AP Suite Cotation 3', 1, 108, 114 );
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_AP_181', 24, 0, 'Rejet Suite Etude AP', 'Rejet Suite Recevabilité', 1, 108, 101 );
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_AP_182', 24, 0, 'Complément d''information Suite Etude Recevabilité', 'Complément d''information Suite Etude Recevabilité', 1, 108, 100 );

INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_AP_190', 24, 0, 'Réponse CI Suite Etude AP', 'Réponse CI Suite Etude AP', 0, 100, 108 );


-- Décision Autorisation AP Suite Etude Recevabilité Agent Cotation 5
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_AP_173', 24, 0, 'Autorisation AP Suite Cotation 4', 'Autorisation AP Suite Cotation 4', 0, 109, 115 );
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_AP_183', 24, 0, 'Rejet Suite Etude AP', 'Rejet Suite Recevabilité', 1, 109, 101 );
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_AP_184', 24, 0, 'Complément d''information Suite Etude Recevabilité', 'Complément d''information Suite Etude Recevabilité', 1, 109, 100 );

INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_AP_191', 24, 0, 'Réponse CI Suite Etude AP', 'Réponse CI Suite Etude AP', 0, 100, 109 );


-- Décision Autorisation AP Suite Etude Recevabilité Agent Cotation 6
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_AP_174', 24, 0, 'Autorisation AP Suite Cotation 4', 'Autorisation AP Suite Cotation 5', 0, 110, 116 );
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_AP_185', 24, 0, 'Rejet Suite Etude AP', 'Rejet Suite Recevabilité', 1, 110, 101  );
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_AP_186', 24, 0, 'Complément d''information Suite Etude Recevabilité', 'Complément d''information Suite Etude Recevabilité', 1, 110, 100 );

INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_AP_192', 24, 0, 'Réponse CI Suite Etude AP', 'Réponse CI Suite Etude AP', 0, 100, 110 );

--COMMIT;

----- Visa Technique Définitif - MINSANTE (2 Niveaux de cotation)
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization of the Definitive Technical Visa ','Autorisation du Visa Technique Définitif ','9', (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_169'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization of the Definitive Technical Visa ','Autorisation du Visa Technique Définitif ','9', (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_170'));

----- Visa Technique Provisoir - MINSANTE (4 Niveaux de cotation)
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization of the Provisional Technical Visa','Autorisation du Visa Technique Provisoire','8', (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_169'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization of the Provisional Technical Visa','Autorisation du Visa Technique Provisoire','8', (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_170'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization of the Provisional Technical Visa','Autorisation du Visa Technique Provisoire','8', (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_171'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization of the Provisional Technical Visa','Autorisation du Visa Technique Provisoire','8', (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_172'));

----- Autorisation d'importation - MINSANTE (5 Niveaux de cotation)
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization of the Import authorization ','Autorisation d''Autorisation d''Importation ','10', (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_169'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization of the Import authorization ','Autorisation d''Autorisation d''Importation ','10', (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_170'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization of the Import authorization ','Autorisation d''Autorisation d''Importation ','10', (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_171'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization of the Import authorization ','Autorisation d''Autorisation d''Importation ','10', (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_172'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization of the Import authorization ','Autorisation d''Autorisation d''Importation ','10', (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_173'));

----- Avis technique - MINSANTE (6 Niveaux de cotation)
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization of the Technical Advice ','Autorisation de l''Avis Technique ','7', (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_169'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization of the Technical Advice ','Autorisation de l''Avis Technique ','7', (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_170'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization of the Technical Advice ','Autorisation de l''Avis Technique ','7', (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_171'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization of the Technical Advice ','Autorisation de l''Avis Technique ','7', (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_172'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization of the Technical Advice ','Autorisation de l''Avis Technique ','7', (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_173'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization of the Technical Advice ','Autorisation de l''Avis Technique ','7', (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_174'));


--COMMIT;

----- FLOW_GUCE pour les décisions au premier niveau de cotation
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES ((SELECT MAX(ID) + 1 FROM FLOW_GUCE_SIAT),'VTD004','FL_AP_169',9);


INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES ((SELECT MAX(ID) + 1 FROM FLOW_GUCE_SIAT),'VTP004','FL_AP_169',8);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES ((SELECT MAX(ID) + 1 FROM FLOW_GUCE_SIAT),'ATS04','FL_AP_169',7);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES ((SELECT MAX(ID) + 1 FROM FLOW_GUCE_SIAT),'AI104','FL_AP_169',10);

----- DATA_TYPE
----- VTP et VTD Minsante
------- Cotation 1
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_169'), 'Décision Générale',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_169'), 'Spécification technique',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_169'), 'Condition',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_169'), 'Consigne',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_169'), 'Observation',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_169'), 'Quantité accordé',  1, 'inputText' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_169'), 'Date validité',  1, 'calendar' );

INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_175'), 'Observation',  0, 'inputTextarea' );

INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_176'), 'Observation',  0, 'inputTextarea' );

------- Cotation 2
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_170'), 'Décision Générale',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_170'), 'Spécification technique',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_170'), 'Condition',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_170'), 'Consigne',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_170'), 'Observation',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_170'), 'Quantité accordé',  1, 'inputText' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_170'), 'Date validité',  1, 'calendar' );

INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_177'), 'Observation',  1, 'inputTextarea' );

INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_178'), 'Observation',  1, 'inputTextarea' );

------- Cotation 3
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_171'), 'Décision Générale',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_171'), 'Spécification technique',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_171'), 'Condition',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_171'), 'Consigne',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_171'), 'Observation',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_171'), 'Quantité accordé',  1, 'inputText' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_171'), 'Date validité',  1, 'calendar' );

INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_179'), 'Observation',  1, 'inputTextarea' );

INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_180'), 'Observation',  1, 'inputTextarea' );

------- Cotation 4
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_172'), 'Décision Générale',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_172'), 'Spécification technique',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_172'), 'Condition',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_172'), 'Consigne',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_172'), 'Observation',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_172'), 'Quantité accordé',  1, 'inputText' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_172'), 'Date validité',  1, 'calendar' );

INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_181'), 'Observation',  1, 'inputTextarea' );

INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_182'), 'Observation',  1, 'inputTextarea' );


------- Cotation 5
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_173'), 'Décision Générale',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_173'), 'Spécification technique',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_173'), 'Condition',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_173'), 'Consigne',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_173'), 'Observation',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_173'), 'Quantité accordé',  1, 'inputText' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_173'), 'Date validité',  1, 'calendar' );

INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_183'), 'Observation',  1, 'inputTextarea' );

INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_184'), 'Observation',  1, 'inputTextarea' );


------- Cotation 6
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_174'), 'Décision Générale',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_174'), 'Spécification technique',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_174'), 'Condition',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_174'), 'Consigne',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_174'), 'Observation',  0, 'inputTextarea' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_174'), 'Quantité accordé',  1, 'inputText' );
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_174'), 'Date validité',  1, 'calendar' );

INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_185') 'Observation',  1, 'inputTextarea' );

INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_186') 'Observation',  1, 'inputTextarea' );


--COMMIT;

-- Avis Technique MINEPIA (5 niveaux de cotation)

INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization of the Technical Advice ','Autorisation de l''Avis Technique','14', (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_169'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization of the Technical Advice ','Autorisation de l''Avis Technique','14', (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_170'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization of the Technical Advice ','Autorisation de l''Avis Technique','14', (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_171'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization of the Technical Advice ','Autorisation de l''Avis Technique','14', (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_172'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization of the Technical Advice ','Autorisation de l''Avis Technique','14', (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_173'));

-- Visa Technique - MINEPIA (2 niveaux de cotation)
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization of the Technical Visa ','Autorisation du Visa Technique ','15', (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_169'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization of the Technical Visa ','Autorisation du Visa Technique ','15', (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_170'));
---- Flow Guce Siat
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES ((SELECT MAX(ID) + 1 FROM FLOW_GUCE_SIAT),'AT04','FL_AP_169',14);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES ((SELECT MAX(ID) + 1 FROM FLOW_GUCE_SIAT),'VT104','FL_AP_169',15);

--COMMIT;

-- Ajouté le 22/11/2018
-- Complément pour le VTP

INSERT INTO FILE_TYPE_FLOW_REPORT(ID, REPORT_CLASS_NAME, REPORT_NAME, FILE_FIELD_NAME, FILE_TYPE_ID, FLOW_ID, ORGANISM_ID) VALUES (FILE_TYPE_FLOW_REPORT_SEQ.nextVal, 'org.guce.siat.web.reports.exporter.VtpMinsanteExporter', 'VTP_MINSANTE.pdf','NUMERO_VTP_MINSANTE',  8, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_169'), 90 );

INSERT INTO FILE_TYPE_FLOW_REPORT(ID, REPORT_CLASS_NAME, REPORT_NAME, FILE_FIELD_NAME, FILE_TYPE_ID, FLOW_ID, ORGANISM_ID) VALUES (FILE_TYPE_FLOW_REPORT_SEQ.nextVal, 'org.guce.siat.web.reports.exporter.VtdMinsanteExporter', 'VTD_MINSANTE.pdf','NUMERO_VTD_MINSANTE',  9, (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_169'), 90 );

INSERT INTO REPORT_ORGANISM(ID, SEQUENCE, VALUE, FILE_TYPE_FLOW_REPORT, ORGANISM)
VALUES (REPORT_ORGANISME_SEQ.nextVal, 0, '/VTP/MINSANTE', (SELECT MIN(ID) FROM FILE_TYPE_FLOW_REPORT WHERE FILE_FIELD_NAME ='NUMERO_VTP_MINSANTE' AND FLOW_ID = (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_169')), 90);

INSERT INTO REPORT_ORGANISM(ID, SEQUENCE, VALUE, FILE_TYPE_FLOW_REPORT, ORGANISM)
VALUES (REPORT_ORGANISME_SEQ.nextVal, 0, 'VTD/MINSANTE', (SELECT MIN(ID) FROM FILE_TYPE_FLOW_REPORT WHERE FILE_FIELD_NAME ='NUMERO_VTD_MINSANTE' AND FLOW_ID = (SELECT MIN(ID) FROM FLOW WHERE CODE='FL_AP_169')), 90);

NSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (FILE_ITEM_FIELD_SEQ.NEXTVAL,8,'AMM','Amm','Amm',1,1,0);


COMMIT;
