/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Gildas AYEFOU
 * Author:  Ulrich ETEME
 * Created: 12 août 2016
 */
-- MISE A JOUR DE AI_MINSANTE
/*==============================================================*/
/* Table : FIELD_GROUP                                          */
/*==============================================================*/
INSERT INTO FIELD_GROUP (ID, LABEL_FR, LABEL_EN) VALUES (60, 'Pharmacien', 'Pharmacist');
INSERT INTO FIELD_GROUP (ID, LABEL_FR, LABEL_EN) VALUES (61, 'Laboratoire frabricant', 'Manufacturing laboratory');
/*==============================================================*/
/* Table : FILE_FIELD                                           */
/*==============================================================*/
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (449,10,'PHARMACIEN__RAISON_SOCIALE','Raison Sociale','Name/Business Name',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (450,10,'PHARMACIEN__NUMERO_CONTRIBUABLE','Numéro contribuable','Taxpayer ID',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (451,10,'PHARMACIEN__ADRESSE__ADRESSE1','Adresse (Adresse 1)','Address (Address 1)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (452,10,'PHARMACIEN__ADRESSE__ADRESSE2','Adresse (Adresse 2)','Address (Address 2)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (453,10,'PHARMACIEN__ADRESSE__BP','Adresse (BP)','Address (P.O. Box)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (454,10,'PHARMACIEN__ADRESSE__PAYS_ADRESSE__CODE_PAYS','Adresse Pays (Code Pays)','Address Country (Country Code)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (455,10,'PHARMACIEN__ADRESSE__PAYS_ADRESSE__NOM_PAYS','Adresse Pays (Nom Pays)','Address Country (Country Name)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (456,10,'PHARMACIEN__ADRESSE__VILLE','Adresse (Ville)','Address (City)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (457,10,'PHARMACIEN__ADRESSE__EMAIL','Adresse (Adresse Électronique)','Address (e-mail Address)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (458,10,'PHARMACIEN__ADRESSE__SITE_WEB','Adresse (Site Web)','Address (Web Site)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (459,10,'PHARMACIEN__TELEPHONE_FIXE__INDICATIF_PAYS','Téléphone Fixe (Indicatif Pays)','Telephone (Country Dialing Code)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (460,10,'PHARMACIEN__TELEPHONE_FIXE__NUMERO','Téléphone Fixe (Numéro)','Telephone (Number)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (461,10,'PHARMACIEN__TELEPHONE_MOBILE__INDICATIF_PAYS','Téléphone Mobile (Indicatif Pays)','Mobile Phone (Country Dialing Code)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (462,10,'PHARMACIEN__TELEPHONE_MOBILE__NUMERO','Téléphone Mobile (Numéro)','Mobile Phone (Number)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (463,10,'PHARMACIEN__FAX__INDICATIF_PAYS','Fax (Indicatif Pays)','Fax (Country Dialing Code)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (464,10,'PHARMACIEN__FAX__NUMERO','Fax (Numéro)','Fax (Number)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (465,10,'PHARMACIEN__NOM_STRUCTURE_PHARMACIEN','Nom de la structure du pharmacien','Name of the pharmacist''s company',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (466,10,'PHARMACIEN__NUM_INSCRIPTION_ORDRE_PHARMACIEN','Numéro d''inscription à l''ordre des pharmaciens','Registration number at the College of Pharmacists',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (467,10,'PHARMACIEN__NUMERO_AGREMENT','Agrément (Numéro)','Agreement (Number)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (468,10,'PHARMACIEN__DATE_EMISSION_AGREMENT','Agrément (Date émission)','Agreement (Issue date)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (469,10,'PHARMACIEN__DATE_FIN_AGREMENT','Agrément (Date expiration)','Agreement (Expiration date)',0,60,1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (470,10,'LABORATOIRE_FABRICANT__RAISON_SOCIALE','Raison Sociale','Name/Business Name',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (471,10,'LABORATOIRE_FABRICANT__NUMERO_CONTRIBUABLE','Numéro contribuable','Taxpayer ID',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (472,10,'LABORATOIRE_FABRICANT__ADRESSE__ADRESSE1','Adresse (Adresse 1)','Address (Address 1)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (473,10,'LABORATOIRE_FABRICANT__ADRESSE__ADRESSE2','Adresse (Adresse 2)','Address (Address 2)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (474,10,'LABORATOIRE_FABRICANT__ADRESSE__BP','Adresse (BP)','Address (P.O. Box)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (475,10,'LABORATOIRE_FABRICANT__ADRESSE__PAYS_ADRESSE__CODE_PAYS','Adresse Pays (Code Pays)','Address Country (Country Code)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (476,10,'LABORATOIRE_FABRICANT__ADRESSE__PAYS_ADRESSE__NOM_PAYS','Adresse Pays (Nom Pays)','Address Country (Country Name)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (477,10,'LABORATOIRE_FABRICANT__ADRESSE__VILLE','Adresse (Ville)','Address (City)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (478,10,'LABORATOIRE_FABRICANT__ADRESSE__EMAIL','Adresse (Adresse Électronique)','Address (e-mail Address)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (479,10,'LABORATOIRE_FABRICANT__ADRESSE__SITE_WEB','Adresse (Site Web)','Address (Web Site)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (480,10,'LABORATOIRE_FABRICANT__TELEPHONE_FIXE__INDICATIF_PAYS','Téléphone Fixe (Indicatif Pays)','Telephone (Country Dialing Code)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (481,10,'LABORATOIRE_FABRICANT__TELEPHONE_FIXE__NUMERO','Téléphone Fixe (Numéro)','Telephone (Number)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (482,10,'LABORATOIRE_FABRICANT__TELEPHONE_MOBILE__INDICATIF_PAYS','Téléphone Mobile (Indicatif Pays)','Mobile Phone (Country Dialing Code)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (483,10,'LABORATOIRE_FABRICANT__TELEPHONE_MOBILE__NUMERO','Téléphone Mobile (Numéro)','Mobile Phone (Number)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (484,10,'LABORATOIRE_FABRICANT__FAX__INDICATIF_PAYS','Fax (Indicatif Pays)','Fax (Country Dialing Code)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (485,10,'LABORATOIRE_FABRICANT__FAX__NUMERO','Fax (Numéro)','Fax (Number)',0,61,1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (486,10,'AMM__NUMERO_AMM','AMM (Numéro)','AMM (Number)',0,11,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (487,10,'AMM__DATE_EMISSION','AMM (Date émission)','AMM (Issue date)',0,11,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (488,10,'AMM__DATE_FIN','AMM (Date expiration)','AMM (Expiration date)',0,11,1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (489,10,'TYPE_PRODUIT','Type de produit pharmaceutique','Pharmaceutical product type',0,1,1);

UPDATE FILE_FIELD SET CODE = 'FOURNISSEUR_SIGLE' WHERE ID='418';
UPDATE FILE_FIELD SET CODE = 'DETENTEUR_MARQUE_FAX_NUMERO' WHERE ID='444';
UPDATE FILE_ITEM_FIELD SET LABEL_FR = 'Dénomination commune internationale' , LABEL_EN = 'International name' WHERE ID='412';
COMMIT;

-- MISE A JOUR DE VTD_MINSANTE
/*==============================================================*/
/* Table : FIELD_GROUP                                          */
/*==============================================================*/
-- INSERT INTO FIELD_GROUP (ID, LABEL_FR, LABEL_EN) VALUES (62, 'Autorisation de Mise sur le Marché', 'Marketing Authorisation Holder');
INSERT INTO FIELD_GROUP (ID, LABEL_FR, LABEL_EN) VALUES (62, 'Agrément MINSANTE', 'MINSANTE Approval');
INSERT INTO FIELD_GROUP (ID, LABEL_FR, LABEL_EN) VALUES (63, 'Facture', 'Invoice');
/*==============================================================*/
/* Table : FILE_FIELD                                           */
/*==============================================================*/
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2820,9,'PHARMACIEN__RAISON_SOCIALE','Raison Sociale','Name/Business Name',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2821,9,'PHARMACIEN__NUMERO_CONTRIBUABLE','Numéro contribuable','Taxpayer ID',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2822,9,'PHARMACIEN__ADRESSE__ADRESSE1','Adresse (Adresse 1)','Address (Address 1)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2823,9,'PHARMACIEN__ADRESSE__ADRESSE2','Adresse (Adresse 2)','Address (Address 2)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2824,9,'PHARMACIEN__ADRESSE__BP','Adresse (BP)','Address (P.O. Box)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2825,9,'PHARMACIEN__ADRESSE__PAYS_ADRESSE__CODE_PAYS','Adresse Pays (Code Pays)','Address Country (Country Code)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2826,9,'PHARMACIEN__ADRESSE__PAYS_ADRESSE__NOM_PAYS','Adresse Pays (Nom Pays)','Address Country (Country Name)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2827,9,'PHARMACIEN__ADRESSE__VILLE','Adresse (Ville)','Address (City)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2828,9,'PHARMACIEN__ADRESSE__EMAIL','Adresse (Adresse Électronique)','Address (e-mail Address)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2829,9,'PHARMACIEN__ADRESSE__SITE_WEB','Adresse (Site Web)','Address (Web Site)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2830,9,'PHARMACIEN__TELEPHONE_FIXE__INDICATIF_PAYS','Téléphone Fixe (Indicatif Pays)','Telephone (Country Dialing Code)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2831,9,'PHARMACIEN__TELEPHONE_FIXE__NUMERO','Téléphone Fixe (Numéro)','Telephone (Number)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2832,9,'PHARMACIEN__TELEPHONE_MOBILE__INDICATIF_PAYS','Téléphone Mobile (Indicatif Pays)','Mobile Phone (Country Dialing Code)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2833,9,'PHARMACIEN__TELEPHONE_MOBILE__NUMERO','Téléphone Mobile (Numéro)','Mobile Phone (Number)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2834,9,'PHARMACIEN__FAX__INDICATIF_PAYS','Fax (Indicatif Pays)','Fax (Country Dialing Code)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2835,9,'PHARMACIEN__FAX__NUMERO','Fax (Numéro)','Fax (Number)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2836,9,'PHARMACIEN__NOM_STRUCTURE_PHARMACIEN','Nom de la structure du pharmacien','Name of the pharmacist''s company',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2837,9,'PHARMACIEN__NUM_INSCRIPTION_ORDRE_PHARMACIEN','Numéro d''inscription à l''ordre des pharmaciens','Registration number at the College of Pharmacists',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2838,9,'PHARMACIEN__NUMERO_AGREMENT','Agrément (Numéro)','Agreement (Number)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2839,9,'PHARMACIEN__DATE_EMISSION_AGREMENT','Agrément (Date émission)','Agreement (Issue date)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2840,9,'PHARMACIEN__DATE_FIN_AGREMENT','Agrément (Date expiration)','Agreement (Expiration date)',0,60,1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2841,9,'LABORATOIRE_FABRICANT__RAISON_SOCIALE','Raison Sociale','Name/Business Name',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2842,9,'LABORATOIRE_FABRICANT__NUMERO_CONTRIBUABLE','Numéro contribuable','Taxpayer ID',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2843,9,'LABORATOIRE_FABRICANT__ADRESSE__ADRESSE1','Adresse (Adresse 1)','Address (Address 1)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2844,9,'LABORATOIRE_FABRICANT__ADRESSE__ADRESSE2','Adresse (Adresse 2)','Address (Address 2)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2845,9,'LABORATOIRE_FABRICANT__ADRESSE__BP','Adresse (BP)','Address (P.O. Box)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2846,9,'LABORATOIRE_FABRICANT__ADRESSE__PAYS_ADRESSE__CODE_PAYS','Adresse Pays (Code Pays)','Address Country (Country Code)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2847,9,'LABORATOIRE_FABRICANT__ADRESSE__PAYS_ADRESSE__NOM_PAYS','Adresse Pays (Nom Pays)','Address Country (Country Name)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2848,9,'LABORATOIRE_FABRICANT__ADRESSE__VILLE','Adresse (Ville)','Address (City)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2849,9,'LABORATOIRE_FABRICANT__ADRESSE__EMAIL','Adresse (Adresse Électronique)','Address (e-mail Address)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2850,9,'LABORATOIRE_FABRICANT__ADRESSE__SITE_WEB','Adresse (Site Web)','Address (Web Site)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2851,9,'LABORATOIRE_FABRICANT__TELEPHONE_FIXE__INDICATIF_PAYS','Téléphone Fixe (Indicatif Pays)','Telephone (Country Dialing Code)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2852,9,'LABORATOIRE_FABRICANT__TELEPHONE_FIXE__NUMERO','Téléphone Fixe (Numéro)','Telephone (Number)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2853,9,'LABORATOIRE_FABRICANT__TELEPHONE_MOBILE__INDICATIF_PAYS','Téléphone Mobile (Indicatif Pays)','Mobile Phone (Country Dialing Code)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2854,9,'LABORATOIRE_FABRICANT__TELEPHONE_MOBILE__NUMERO','Téléphone Mobile (Numéro)','Mobile Phone (Number)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2855,9,'LABORATOIRE_FABRICANT__FAX__INDICATIF_PAYS','Fax (Indicatif Pays)','Fax (Country Dialing Code)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2856,9,'LABORATOIRE_FABRICANT__FAX__NUMERO','Fax (Numéro)','Fax (Number)',0,61,1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2857,9,'AMM__NUMERO_AMM','AMM (Numéro)','AMM (Number)',0,11,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2858,9,'AMM__DATE_EMISSION','AMM (Date émission)','AMM (Issue date)',0,11,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2859,9,'AMM__DATE_FIN','AMM (Date expiration)','AMM (Expiration date)',0,11,1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2860,9,'AGREMENT_MINSANTE__NUMERO_AOI','AOI (Numéro)','AOI (Number)',0,62,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2861,9,'AGREMENT_MINSANTE__NUMERO_VTP','VTP (Numéro)','VTP (Number)',0,62,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2862,9,'AGREMENT_MINSANTE__NUMERO_AGREMENT','Agrément (Numéro)','Approval (Number)',0,62,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2863,9,'AGREMENT_MINSANTE__DATE_EMISSION_AGREMENT','Agrément (Date émission)','Approval (Issue date)',0,62,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2864,9,'AGREMENT_MINSANTE__DATE_EXPIRATION_AGREMENT','Agrément (Date expiration)','Approval (Expiration date)',0,62,1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2865,9,'FACTURE__NUMERO_FACTURE','Facture (Numéro ou Référence)','Invoice (Reference)',0,63,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2866,9,'FACTURE__MONTANT_TOTAL','Facture (Montant)','Invoice (Amount)',0,63,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2867,9,'FACTURE__DATE_FACTURE','Facture (Date émission)','Invoice (Issue date)',0,63,1);

/*==============================================================*/
/* Table : FILE_ITEM_FIELD                                      */
/*==============================================================*/
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (2728,9,'QUANTITE_IMPORTEE','Quantité Importée','Imported Quantity',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (2729,9,'MODE_EMBALLAGE','Mode d''emballage','Packaging mode',1,1,0);
UPDATE FILE_FIELD SET CODE = 'FOURNISSEUR_SIGLE' WHERE ID='2722';
UPDATE FILE_FIELD SET CODE = 'INFORMATIONS_GENERALES_LETTRE_TRANSPORT_DATE_LETTRE_TRANSPORT' WHERE ID='2782';
DELETE FROM FILE_ITEM_FIELD WHERE ID = 2724;
COMMIT;

-- MISE A JOUR DE VTP_MINSANTE

/*==============================================================*/
/* Table : FILE_FIELD                                           */
/*==============================================================*/
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3019,8,'PHARMACIEN__RAISON_SOCIALE','Raison Sociale','Name/Business Name',0,60,1);
-- INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3020,8,'PHARMACIEN__NUMERO_CONTRIBUABLE','Numéro contribuable','Taxpayer ID',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3021,8,'PHARMACIEN__ADRESSE__ADRESSE1','Adresse (Adresse 1)','Address (Address 1)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3022,8,'PHARMACIEN__ADRESSE__ADRESSE2','Adresse (Adresse 2)','Address (Address 2)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3023,8,'PHARMACIEN__ADRESSE__BP','Adresse (BP)','Address (P.O. Box)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3024,8,'PHARMACIEN__ADRESSE__PAYS_ADRESSE__CODE_PAYS','Adresse Pays (Code Pays)','Address Country (Country Code)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3025,8,'PHARMACIEN__ADRESSE__PAYS_ADRESSE__NOM_PAYS','Adresse Pays (Nom Pays)','Address Country (Country Name)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3026,8,'PHARMACIEN__ADRESSE__VILLE','Adresse (Ville)','Address (City)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3027,8,'PHARMACIEN__ADRESSE__EMAIL','Adresse (Adresse Électronique)','Address (e-mail Address)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3028,8,'PHARMACIEN__ADRESSE__SITE_WEB','Adresse (Site Web)','Address (Web Site)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3029,8,'PHARMACIEN__TELEPHONE_FIXE__INDICATIF_PAYS','Téléphone Fixe (Indicatif Pays)','Telephone (Country Dialing Code)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3030,8,'PHARMACIEN__TELEPHONE_FIXE__NUMERO','Téléphone Fixe (Numéro)','Telephone (Number)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3031,8,'PHARMACIEN__TELEPHONE_MOBILE__INDICATIF_PAYS','Téléphone Mobile (Indicatif Pays)','Mobile Phone (Country Dialing Code)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3032,8,'PHARMACIEN__TELEPHONE_MOBILE__NUMERO','Téléphone Mobile (Numéro)','Mobile Phone (Number)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3033,8,'PHARMACIEN__FAX__INDICATIF_PAYS','Fax (Indicatif Pays)','Fax (Country Dialing Code)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3034,8,'PHARMACIEN__FAX__NUMERO','Fax (Numéro)','Fax (Number)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3035,8,'PHARMACIEN__NOM_STRUCTURE_PHARMACIEN','Nom de la structure du pharmacien','Name of the pharmacist''s company',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3036,8,'PHARMACIEN__NUM_INSCRIPTION_ORDRE_PHARMACIEN','Numéro d''inscription à l''ordre des pharmaciens','Registration number at the College of Pharmacists',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3037,8,'PHARMACIEN__NUMERO_AGREMENT','Agrément (Numéro)','Agreement (Number)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3038,8,'PHARMACIEN__DATE_EMISSION_AGREMENT','Agrément (Date émission)','Agreement (Issue date)',0,60,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3039,8,'PHARMACIEN__DATE_FIN_AGREMENT','Agrément (Date expiration)','Agreement (Expiration date)',0,60,1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3040,8,'LABORATOIRE_FABRICANT__RAISON_SOCIALE','Raison Sociale','Name/Business Name',0,61,1);
-- INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3041,8,'LABORATOIRE_FABRICANT__NUMERO_CONTRIBUABLE','Numéro contribuable','Taxpayer ID',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3042,8,'LABORATOIRE_FABRICANT__ADRESSE__ADRESSE1','Adresse (Adresse 1)','Address (Address 1)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3043,8,'LABORATOIRE_FABRICANT__ADRESSE__ADRESSE2','Adresse (Adresse 2)','Address (Address 2)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3044,8,'LABORATOIRE_FABRICANT__ADRESSE__BP','Adresse (BP)','Address (P.O. Box)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3045,8,'LABORATOIRE_FABRICANT__ADRESSE__PAYS_ADRESSE__CODE_PAYS','Adresse Pays (Code Pays)','Address Country (Country Code)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3046,8,'LABORATOIRE_FABRICANT__ADRESSE__PAYS_ADRESSE__NOM_PAYS','Adresse Pays (Nom Pays)','Address Country (Country Name)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3047,8,'LABORATOIRE_FABRICANT__ADRESSE__VILLE','Adresse (Ville)','Address (City)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3048,8,'LABORATOIRE_FABRICANT__ADRESSE__EMAIL','Adresse (Adresse Électronique)','Address (e-mail Address)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3049,8,'LABORATOIRE_FABRICANT__ADRESSE__SITE_WEB','Adresse (Site Web)','Address (Web Site)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3050,8,'LABORATOIRE_FABRICANT__TELEPHONE_FIXE__INDICATIF_PAYS','Téléphone Fixe (Indicatif Pays)','Telephone (Country Dialing Code)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3051,8,'LABORATOIRE_FABRICANT__TELEPHONE_FIXE__NUMERO','Téléphone Fixe (Numéro)','Telephone (Number)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3052,8,'LABORATOIRE_FABRICANT__TELEPHONE_MOBILE__INDICATIF_PAYS','Téléphone Mobile (Indicatif Pays)','Mobile Phone (Country Dialing Code)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3053,8,'LABORATOIRE_FABRICANT__TELEPHONE_MOBILE__NUMERO','Téléphone Mobile (Numéro)','Mobile Phone (Number)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3054,8,'LABORATOIRE_FABRICANT__FAX__INDICATIF_PAYS','Fax (Indicatif Pays)','Fax (Country Dialing Code)',0,61,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3055,8,'LABORATOIRE_FABRICANT__FAX__NUMERO','Fax (Numéro)','Fax (Number)',0,61,1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3056,8,'AMM__NUMERO_AMM','AMM (Numéro)','AMM (Number)',0,11,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3057,8,'AMM__DATE_EMISSION','AMM (Date émission)','AMM (Issue date)',0,11,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3058,8,'AMM__DATE_FIN','AMM (Date expiration)','AMM (Expiration date)',0,11,1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3059,8,'AGREMENT_MINSANTE__NUMERO_AOI','AOI (Numéro)','AOI (Number)',0,62,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3060,8,'AGREMENT_MINSANTE__NUMERO_AGREMENT','Agrément (Numéro)','Approval (Number)',0,62,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3061,8,'AGREMENT_MINSANTE__DATE_EMISSION_AGREMENT','Agrément (Date émission)','Approval (Issue date)',0,62,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3062,8,'AGREMENT_MINSANTE__DATE_EXPIRATION_AGREMENT','Agrément (Date expiration)','Approval (Expiration date)',0,62,1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3063,8,'FACTURE__NUMERO_FACTURE','Facture (Numéro ou Référence)','Invoice (Reference)',0,63,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3064,8,'FACTURE__MONTANT_TOTAL','Facture (Montant)','Invoice (Amount)',0,63,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3065,8,'FACTURE__DATE_FACTURE','Facture (Date émission)','Invoice (Issue date)',0,63,1);

/*==============================================================*/
/* Table : FILE_ITEM_FIELD                                      */
/*==============================================================*/
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (2928,8,'QUANTITE_IMPORTEE','Quantité Importée','Imported Quantity',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (2929,8,'MODE_EMBALLAGE','Mode d''emballage','Packaging mode',1,1,0);
UPDATE FILE_FIELD SET CODE = 'FOURNISSEUR_SIGLE' WHERE ID='2922';
UPDATE FILE_FIELD SET CODE = 'INFORMATIONS_GENERALES_LETTRE_TRANSPORT_DATE_LETTRE_TRANSPORT' WHERE ID='2981';
DELETE FROM FILE_ITEM_FIELD WHERE ID = 2924;
COMMIT;