--
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),33,'POIDS_BRUT','Poids Brut','Gross Weight',1,1,0);
COMMIT;
-- 1.3.3-SNAPSHOT
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'NUMEROS_LOTS','Numéros Lots','Lots Numbers',0,1,1);
-- 1.3.4
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'EXIGENCES_PHYTOSANITAIRES','Exigences Phytosanitaires','Phytosaniratary Requirements',0,1,1);
-- 1.3.8-TEST
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'TYPE_DOSSIER_EGUCE','Type de dossier e-GUCE','e-GUCE file type',0,1,1);
-- 1.3.10a
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'TYPE_PRODUIT_CODE','Code type produit','Product type code',0,1,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'TYPE_PRODUIT_NOM','Nom type produit','Product type name',0,1,1);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),33,'NOMBRE_SACS','Nombre de sacs','Number of bags',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),33,'NOMBRE_GRUMES','Nombre de grumes','Number of logs',1,1,0);
--
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES ((SELECT MAX(ID) + 1 FROM FLOW_GUCE_SIAT),'CTE001','FL_CT_01',33);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES ((SELECT MAX(ID) + 1 FROM FLOW_GUCE_SIAT),'CTE002','FL_CT_02',33);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES ((SELECT MAX(ID) + 1 FROM FLOW_GUCE_SIAT),'CTE011',NULL,33);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES ((SELECT MAX(ID) + 1 FROM FLOW_GUCE_SIAT),'CTE003','FL_CT_04',33);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES ((SELECT MAX(ID) + 1 FROM FLOW_GUCE_SIAT),'CTE003','FL_CT_91',33);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES ((SELECT MAX(ID) + 1 FROM FLOW_GUCE_SIAT),'CTE004','FL_CT_08',33);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES ((SELECT MAX(ID) + 1 FROM FLOW_GUCE_SIAT),'CTE002','FL_CT_24',33);
--
-- FILE_TYPE_FLOW_REPORT
INSERT INTO FILE_TYPE_FLOW_REPORT (ID, FILE_FIELD_NAME, FILE_TYPE_ID, FLOW_ID, ORGANISM_ID, REPORT_CLASS_NAME, REPORT_NAME) VALUES(33, 'NUMERO_CT_CCT_CP_E', 33, 8, 3, 'org.guce.siat.web.reports.exporter.CtCctCpEExporter', 'CT_CCT_CP_E.pdf');
INSERT INTO FILE_TYPE_FLOW_REPORT (ID, FILE_FIELD_NAME, FILE_TYPE_ID, FLOW_ID, ORGANISM_ID, REPORT_CLASS_NAME, REPORT_NAME) VALUES(30, 'NUMERO_CT_CCT_CP_E', 33, 89, 3, 'org.guce.siat.web.reports.exporter.CtCctCpEExporter', 'CT_CCT_CP_E.pdf');
-- REPORT_ORGANISM
INSERT INTO REPORT_ORGANISM(ID, SEQUENCE, VALUE, FILE_TYPE_FLOW_REPORT, ORGANISM) VALUES ((SELECT MAX(ID) + 1 FROM REPORT_ORGANISM), 0, '/CCT/CPE/MINADER', 33, 3);
--
ALTER TABLE TREATMENT_INFOS MODIFY (REGISTRATION_DATE TIMESTAMP);
-- COMMIT
COMMIT;
