
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),37,'NOM_BOTANIQUE','Nom botanique','Botanical Name',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),37,'NOMBRE_GRUMES','Nombre de grumes','Number of logs',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),37,'POIDS','Poids','Weight',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),37,'POIDS_BRUT','Poids brute','Gros Weight',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),37,'NOM_COMMERCIAL','Nom Commercial','Trade Name',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),37,'NOMBRE_SACS','Nombre de sacs','Number of bags',1,1,0);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),37,'NUMEROS_LOTS','Numéros Lots','Lots Numbers',0,1,1);

--
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),39,'NOM_BOTANIQUE','Nom botanique','Botanical Name',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),39,'NOMBRE_GRUMES','Nombre de grumes','Number of logs',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),39,'POIDS','Poids','Weight',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),39,'POIDS_BRUT','Poids brute','Gros Weight',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),39,'NOMBRE_SACS','Nombre de sacs','Number of bags',1,1,0);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),39,'NUMEROS_LOTS','Numéros Lots','Lots Numbers',0,1,1);

INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),36,'POIDS','Poids','Weight',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),36,'POIDS_BRUT','Poids brute','Gros Weight',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),36,'NOM_COMMERCIAL','Nom Commercial','Trade Name',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),36,'NOM_BOTANIQUE','Nom botanique','Botanical Name',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),36,'NOMBRE_GRUMES','Nombre de grumes','Number of logs',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),36,'NOMBRE_SACS','Nombre de sacs','Number of bags',1,1,0);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),36,'NUMEROS_LOTS','Numéros Lots','Lots Numbers',0,1,1);


COMMIT;

-- 09/07/2019
-- yenke
-- Modification du libelle du file_item_field NOMBRE_GRUMES pour la procédure CTE
UPDATE FILE_ITEM_FIELD SET LABEL_FR = 'Nombre de grume/colis/balle', LABEL_EN = 'Number of logs/package/ball' WHERE CODE='NOMBRE_GRUMES' AND FILE_TYPE_ID=39;
COMMIT;


INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_CT_106', 24, 0, 'Retourner le dossier pour réorientation', 'Retourner le dossier pour réorientation', 0, 4, 3);
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_CT_107', 24, 0, 'Retourner le dossier pour réorientation', 'Retourner le dossier pour réorientation', 0, 129, 128);

INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Retourner le dossier pour réorientation','Retourner le dossier pour réorientation',33,(SELECT ID FROM FLOW WHERE CODE ='FL_CT_106'));

INSERT INTO STEP (ID,CODE,LABELFR,LABELEN,IS_FINAL) VALUES ((SELECT MAX(ID) + 1 FROM STEP), 'ST_CT_50', 'Retourner le dossier pour réorientation', 'Retourner le dossier pour réorientation',0);

INSERT INTO FILE_TYPE_STEP (LABEL_EN,LABEL_FR,FILE_TYPE_ID,STEP_ID) VALUES ('Retourner le dossier pour réorientation', 'Retourner le dossier pour réorientation', 33, (SELECT ID FROM STEP WHERE CODE ='ST_CT_50'));


INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES ((SELECT MAX(ID) + 1 FROM DATA_TYPE), (SELECT ID FROM FLOW WHERE CODE = 'FL_CT_106'), 'Observation',  1, 'inputTextarea');


INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Retourner le dossier pour réorientation','Retourner le dossier pour réorientation',36,(SELECT ID FROM FLOW WHERE CODE ='FL_CT_107'));

INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES ((SELECT MAX(ID) + 1 FROM DATA_TYPE), (SELECT ID FROM FLOW WHERE CODE = 'FL_CT_107'), 'Observation',  1, 'inputTextarea');



-- RFC_STATISTIQUE
INSERT INTO AUTHORITY (ID, ROLE, LABEL_FR, LABEL_EN, AUTHORITY_TYPE) VALUES ((SELECT MAX(ID) + 1 FROM AUTHORITY), 'STAT', 'Statistique', 'Statistic', 'STATISTIQUE');


INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),36,'TYPE_DOSSIER_EGUCE','Type de dossier e-GUCE','e-GUCE file type',0,1,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),37,'TYPE_DOSSIER_EGUCE','Type de dossier e-GUCE','e-GUCE file type',0,1,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),39,'TYPE_DOSSIER_EGUCE','Type de dossier e-GUCE','e-GUCE file type',0,1,1);

INSERT INTO POSITION_AUTHORITY (POSITION_TYPE, AUTHORITY_ID) VALUES ('AGENT', (SELECT MAX(ID) FROM AUTHORITY WHERE AUTHORITY_TYPE = 'STATISTIQUE'));
INSERT INTO POSITION_AUTHORITY (POSITION_TYPE, AUTHORITY_ID) VALUES ('CHEF_BUREAU', (SELECT MAX(ID) FROM AUTHORITY WHERE AUTHORITY_TYPE = 'STATISTIQUE'));
INSERT INTO POSITION_AUTHORITY (POSITION_TYPE, AUTHORITY_ID) VALUES ('CHEF_SERVICE', (SELECT MAX(ID) FROM AUTHORITY WHERE AUTHORITY_TYPE = 'STATISTIQUE'));
INSERT INTO POSITION_AUTHORITY (POSITION_TYPE, AUTHORITY_ID) VALUES ('SOUS_DIRECTEUR', (SELECT MAX(ID) FROM AUTHORITY WHERE AUTHORITY_TYPE = 'STATISTIQUE'));
INSERT INTO POSITION_AUTHORITY (POSITION_TYPE, AUTHORITY_ID) VALUES ('DIRECTEUR', (SELECT MAX(ID) FROM AUTHORITY WHERE AUTHORITY_TYPE = 'STATISTIQUE'));
INSERT INTO POSITION_AUTHORITY (POSITION_TYPE, AUTHORITY_ID) VALUES ('SECRETAIRE_GENERAL', (SELECT MAX(ID) FROM AUTHORITY WHERE AUTHORITY_TYPE = 'STATISTIQUE'));
INSERT INTO POSITION_AUTHORITY (POSITION_TYPE, AUTHORITY_ID) VALUES ('MINISTRE', (SELECT MAX(ID) FROM AUTHORITY WHERE AUTHORITY_TYPE = 'STATISTIQUE'));
