-- Requêtes de suppression des associations file type flow dans la tables file_type_flow pour cte
DELETE FROM FILE_TYPE_FLOW WHERE FILE_TYPE_ID = 33 AND FLOW_ID = 11;
DELETE FROM FILE_TYPE_FLOW WHERE FILE_TYPE_ID = 33 AND FLOW_ID = 19;

-- modifications bd :
-- file_field for type of technical visa in vt minepded
INSERT INTO FILE_FIELD (ID, CODE, LABEL_EN, LABEL_FR, REPEATABLE, UPDATABLE, FILE_TYPE_ID, GROUP_ID) VALUES
((SELECT MAX(ID) + 1 FROM FILE_FIELD), 'TYPE_OF_TECHNICAL_VISA', 'Type of technical visa', 'Type de visa technique', 0, 1, 16, 1);
-- field pour pour le numéro de rapport de cq
INSERT INTO FILE_FIELD (ID, CODE, FILE_TYPE_ID, GROUP_ID, LABEL_EN, LABEL_FR, REPEATABLE, UPDATABLE)
VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD), 'NUMERO_CT_CCT_CQE', 21, 1, 'Quality Certificate Number', 'N° Certificat de qualité', 0, 1);
-- FILE_TYPE_FLOW_REPORT for cq
INSERT INTO FILE_TYPE_FLOW_REPORT (ID, FILE_FIELD_NAME, FILE_TYPE_ID, FLOW_ID, ORGANISM_ID, REPORT_CLASS_NAME, REPORT_NAME)
VALUES(32, 'NUMERO_CT_CCT_CQE', 21, 89, 209, 'org.guce.siat.web.reports.exporter.CtCctCqeExporter', 'CERTIFICAT_QUALITE.pdf');
INSERT INTO FILE_TYPE_FLOW_REPORT (ID, FILE_FIELD_NAME, FILE_TYPE_ID, FLOW_ID, ORGANISM_ID, REPORT_CLASS_NAME, REPORT_NAME)
VALUES(35, 'NUMERO_CT_CCT_CQE', 21, 8, 209, 'org.guce.siat.web.reports.exporter.CtCctCqeExporter', 'CERTIFICAT_QUALITE.pdf');
-- FILE_TYPE_FLOW_REPORT for cte
INSERT INTO FILE_TYPE_FLOW_REPORT (ID, FILE_FIELD_NAME, FILE_TYPE_ID, FLOW_ID, ORGANISM_ID, REPORT_CLASS_NAME, REPORT_NAME)
VALUES(33, 'NUMERO_CT_CCT_CP_E', 33, 8, 3, 'org.guce.siat.web.reports.exporter.CtCctCpEExporter', 'CT_CCT_CP_E.pdf');
-- REPORT_ORGANISM pour gérer la séquence des numéros de rapport cte (non envoyée)
INSERT INTO REPORT_ORGANISM(ID, SEQUENCE, VALUE, FILE_TYPE_FLOW_REPORT, ORGANISM)
VALUES (REPORT_ORGANISME_SEQ.nextVal, 0, '/CCT/CPE/MINADER', 33, 3);
-- REPORT_ORGANISM pour gérer la séquence des numéros de rapport cq
INSERT INTO REPORT_ORGANISM(ID, SEQUENCE, VALUE, FILE_TYPE_FLOW_REPORT, ORGANISM)
VALUES (REPORT_ORGANISME_SEQ.nextVal, 0, '/CCT/CPE/MINADER', 32, 209);

-- file_field pour l'ajout du transitaire dans le certificat de qualité
INSERT INTO FILE_FIELD (ID, CODE, FILE_TYPE_ID, GROUP_ID, LABEL_EN, LABEL_FR, REPEATABLE, UPDATABLE)
VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD), 'TRANSITAIRE_NUMERO_CONTRIBUABLE', 21, 7, 'Taxpayer ID', 'N° Contribuable', 0, 1);
INSERT INTO FILE_FIELD (ID, CODE, FILE_TYPE_ID, GROUP_ID, LABEL_EN, LABEL_FR, REPEATABLE, UPDATABLE)
VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD), 'TRANSITAIRE_RAISONSOCIALE', 21, 7, 'Name/Business Name', 'Raison Sociale', 0, 1);
INSERT INTO FILE_FIELD (ID, CODE, FILE_TYPE_ID, GROUP_ID, LABEL_EN, LABEL_FR, REPEATABLE, UPDATABLE)
VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD), 'CATEGORIE', 21, 7, 'Category', 'Catégorie', 0, 1);
