
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),37,'NOM_BOTANIQUE','Nom botanique','Botanical Name',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),37,'NOMBRE_GRUMES','Nombre de grumes','Number of logs',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),37,'POIDS','Poids','Weight',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),37,'POIDS_BRUT','Poids brute','Gros Weight',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),37,'NOM_COMMERCIAL','Nom Commercial','Trade Name',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),37,'NOMBRE_SACS','Nombre de sacs','Number of bags',1,1,0);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),37,'NUMEROS_LOTS','Numéros Lots','Lots Numbers',0,1,1);

--
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),39,'NOM_BOTANIQUE','Nom botanique','Botanical Name',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),39,'NOMBRE_GRUMES','Nombre de grumes','Number of logs',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),39,'POIDS','Poids','Weight',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),39,'POIDS_BRUT','Poids brute','Gros Weight',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),39,'NOMBRE_SACS','Nombre de sacs','Number of bags',1,1,0);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),39,'NUMEROS_LOTS','Numéros Lots','Lots Numbers',0,1,1);

INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),36,'POIDS','Poids','Weight',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),36,'POIDS_BRUT','Poids brute','Gros Weight',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),36,'NOM_COMMERCIAL','Nom Commercial','Trade Name',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),36,'NOM_BOTANIQUE','Nom botanique','Botanical Name',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),36,'NOMBRE_GRUMES','Nombre de grumes','Number of logs',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),36,'NOMBRE_SACS','Nombre de sacs','Number of bags',1,1,0);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),36,'NUMEROS_LOTS','Numéros Lots','Lots Numbers',0,1,1);


COMMIT;

-- 09/07/2019
-- yenke
-- Modification du libelle du file_item_field NOMBRE_GRUMES pour la procédure CTE
UPDATE FILE_ITEM_FIELD SET LABEL_FR = 'Nombre de grume/colis/balle', LABEL_EN = 'Number of logs/package/ball' WHERE CODE='NOMBRE_GRUMES' AND FILE_TYPE_ID=39;
COMMIT;


INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_CT_106', 24, 0, 'Retourner le dossier pour réorientation', 'Retourner le dossier pour réorientation', 0, 4, 3);
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_CT_107', 24, 0, 'Retourner le dossier pour réorientation', 'Retourner le dossier pour réorientation', 0, 129, 128);

INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Retourner le dossier pour réorientation','Retourner le dossier pour réorientation',33,(SELECT ID FROM FLOW WHERE CODE ='FL_CT_106'));

INSERT INTO STEP (ID,CODE,LABELFR,LABELEN,IS_FINAL) VALUES ((SELECT MAX(ID) + 1 FROM STEP), 'ST_CT_50', 'Retourner le dossier pour réorientation', 'Retourner le dossier pour réorientation',0);

INSERT INTO FILE_TYPE_STEP (LABEL_EN,LABEL_FR,FILE_TYPE_ID,STEP_ID) VALUES ('Retourner le dossier pour réorientation', 'Retourner le dossier pour réorientation', 33, (SELECT ID FROM STEP WHERE CODE ='ST_CT_50'));


INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES ((SELECT MAX(ID) + 1 FROM DATA_TYPE), (SELECT ID FROM FLOW WHERE CODE = 'FL_CT_106'), 'Observation',  1, 'inputTextarea');


INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Retourner le dossier pour réorientation','Retourner le dossier pour réorientation',36,(SELECT ID FROM FLOW WHERE CODE ='FL_CT_107'));

INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES ((SELECT MAX(ID) + 1 FROM DATA_TYPE), (SELECT ID FROM FLOW WHERE CODE = 'FL_CT_107'), 'Observation',  1, 'inputTextarea');



-- RFC_STATISTIQUE
INSERT INTO AUTHORITY (ID, ROLE, LABEL_FR, LABEL_EN, AUTHORITY_TYPE) VALUES ((SELECT MAX(ID) + 1 FROM AUTHORITY), 'STAT', 'Statistique', 'Statistic', 'STATISTIQUE');


INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),36,'TYPE_DOSSIER_EGUCE','Type de dossier e-GUCE','e-GUCE file type',0,1,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),37,'TYPE_DOSSIER_EGUCE','Type de dossier e-GUCE','e-GUCE file type',0,1,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),39,'TYPE_DOSSIER_EGUCE','Type de dossier e-GUCE','e-GUCE file type',0,1,1);

INSERT INTO POSITION_AUTHORITY (POSITION_TYPE, AUTHORITY_ID) VALUES ('AGENT', (SELECT MAX(ID) FROM AUTHORITY WHERE AUTHORITY_TYPE = 'STATISTIQUE'));
INSERT INTO POSITION_AUTHORITY (POSITION_TYPE, AUTHORITY_ID) VALUES ('CHEF_BUREAU', (SELECT MAX(ID) FROM AUTHORITY WHERE AUTHORITY_TYPE = 'STATISTIQUE'));
INSERT INTO POSITION_AUTHORITY (POSITION_TYPE, AUTHORITY_ID) VALUES ('CHEF_SERVICE', (SELECT MAX(ID) FROM AUTHORITY WHERE AUTHORITY_TYPE = 'STATISTIQUE'));
INSERT INTO POSITION_AUTHORITY (POSITION_TYPE, AUTHORITY_ID) VALUES ('SOUS_DIRECTEUR', (SELECT MAX(ID) FROM AUTHORITY WHERE AUTHORITY_TYPE = 'STATISTIQUE'));
INSERT INTO POSITION_AUTHORITY (POSITION_TYPE, AUTHORITY_ID) VALUES ('DIRECTEUR', (SELECT MAX(ID) FROM AUTHORITY WHERE AUTHORITY_TYPE = 'STATISTIQUE'));
INSERT INTO POSITION_AUTHORITY (POSITION_TYPE, AUTHORITY_ID) VALUES ('SECRETAIRE_GENERAL', (SELECT MAX(ID) FROM AUTHORITY WHERE AUTHORITY_TYPE = 'STATISTIQUE'));
INSERT INTO POSITION_AUTHORITY (POSITION_TYPE, AUTHORITY_ID) VALUES ('MINISTRE', (SELECT MAX(ID) FROM AUTHORITY WHERE AUTHORITY_TYPE = 'STATISTIQUE'));



-- 
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'INFORMATIONS_GENERALES_OBSERVATIONS','Observations','Observations',0,1,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'INFORMATIONS_GENERALES_REFERENCE_BASE','Référence de Base','Base reference',0,1,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),36,'INFORMATIONS_GENERALES_OBSERVATIONS','Observations','Observations',0,1,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),36,'INFORMATIONS_GENERALES_REFERENCE_BASE','Référence de Base','Base reference',0,1,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),37,'INFORMATIONS_GENERALES_OBSERVATIONS','Observations','Observations',0,1,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),37,'INFORMATIONS_GENERALES_REFERENCE_BASE','Référence de Base','Base reference',0,1,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),39,'INFORMATIONS_GENERALES_OBSERVATIONS','Observations','Observations',0,1,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),39,'INFORMATIONS_GENERALES_REFERENCE_BASE','Référence de Base','Base reference',0,1,1);



INSERT INTO STEP (ID, IS_FINAL, LABELEN, LABELFR, CODE) VALUES (132, 0, 'Demande de modification', 'Demande de modification', 'ST_CT_51');
INSERT INTO STEP (ID, IS_FINAL, LABELEN, LABELFR, CODE) VALUES (133, 0, 'Recevabilité - Demande de modification', 'Recevabilité - Demande de modification', 'ST_CT_52');
INSERT INTO STEP (ID, IS_FINAL, LABELEN, LABELFR, CODE) VALUES (134, 0, 'Cotation - Demande de modification', 'Cotation - Demande de modification', 'ST_CT_53');
INSERT INTO STEP (ID, IS_FINAL, LABELEN, LABELFR, CODE) VALUES (135, 1, 'Rejet - Demande de modification', 'Rejet - Demande de modification', 'ST_CT_54');
INSERT INTO STEP (ID, IS_FINAL, LABELEN, LABELFR, CODE) VALUES (136, 0, 'Traitement - Demande de modification', 'Traitement - Demande de modification', 'ST_CT_55');
INSERT INTO STEP (ID, IS_FINAL, LABELEN, LABELFR, CODE) VALUES (137, 0, 'Signature - Demande de modification', 'Signature - Demande de modification', 'ST_CT_56');

INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_CT_110', 24, 0, 'Demande de modification', 'Demande de modification', 0, 132, 133);
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_CT_111', 24, 0, 'Validation suite recevabilité - Demande de modification', 'Validation suite recevabilité - Demande de modification', 0, 133, 134);
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_CT_108', 24, 0, 'Rejet suite recevabilité - Demande de modification', 'Rejet suite recevabilité - Demande de modification', 1, 133, 5);
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_CT_109', 24, 1, 'Cotation - Demande de modification', 'Cotation - Demande de modification', 0, 134, 136);
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_CT_112', 24, 0, 'Validation pour signature - Demande de modification', 'Validation pour signature - Demande de modification', 0, 136, 137);
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_CT_113', 24, 0, 'Rejet suite traitement - Demande de modification', 'Rejet suite traitement - Demande de modification', 1, 136, 5);
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_CT_114', 24, 0, 'Signature - Demande de modification', 'Signature - Demande de modification', 1, 137, 6);
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_CT_115', 24, 0, 'Refus Signature - Demande de modification', 'Refus Signature - Demande de modification', 0, 137, 136);
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_CT_116', 24, 0, 'Rejet Suite Etude Approfondie - Demande de modification', 'Rejet Suite Etude Approfondie - Demande de modification', 1, 134, 5);
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_CT_117', 24, 0, 'Validation Suite Etude Approfondie Cotation - Demande de modification', 'Validation Suite Etude Approfondie Cotation - Demande de modification', 1, 134, 6);

INSERT INTO FILE_TYPE_FLOW (LABEL_EN, LABEL_FR, FILE_TYPE_ID, FLOW_ID) VALUES ('Validation Modification du certificat phytosanitaire pour signature', 'Validation Modification du certificat phytosanitaire pour signature', 33, (SELECT MAX(ID) FROM FLOW WHERE CODE='FL_CT_112'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN, LABEL_FR, FILE_TYPE_ID, FLOW_ID) VALUES ('Rejet Suite Recevabilité - Demande de modification certificat phytosanitaire', 'Rejet Suite Recevabilité - Demande de modification certificat phytosanitaire', 33, (SELECT MAX(ID) FROM FLOW WHERE CODE='FL_CT_108'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN, LABEL_FR, FILE_TYPE_ID, FLOW_ID) VALUES ('Rejet Suite Etude Approfondie - Demande de modification certificat phytosanitaire', 'Rejet Suite Etude Approfondie - Demande de modification certificat phytosanitaire', 33, (SELECT MAX(ID) FROM FLOW WHERE CODE='FL_CT_113'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN, LABEL_FR, FILE_TYPE_ID, FLOW_ID) VALUES ('Signature Modification Certificat phytosanitaire', 'Signature Modification Certificat phytosanitaire', 33, (SELECT MAX(ID) FROM FLOW WHERE CODE='FL_CT_114'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN, LABEL_FR, FILE_TYPE_ID, FLOW_ID) VALUES ('Refus de signature modification certificat phytosanitaire', 'Refus de signature modification certificat phytosanitaire', 33, (SELECT MAX(ID) FROM FLOW WHERE CODE='FL_CT_115'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN, LABEL_FR, FILE_TYPE_ID, FLOW_ID) VALUES ('Demande de modification certificat phytosanitaire', 'Demande de modification certificat phytosanitaire', 33, (SELECT MAX(ID) FROM FLOW WHERE CODE='FL_CT_110'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN, LABEL_FR, FILE_TYPE_ID, FLOW_ID) VALUES ('Validation suite recevabilité - Demande de modification certificat phytosanitaire', 'Validation suite recevabilité - Demande de modification certificat phytosanitaire', 33, (SELECT MAX(ID) FROM FLOW WHERE CODE='FL_CT_111'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN, LABEL_FR, FILE_TYPE_ID, FLOW_ID) VALUES ('Cotation - Demande de modification certificat phytosanitaire', 'Cotation - Demande de modification certificat phytosanitaire', 33, (SELECT MAX(ID) FROM FLOW WHERE CODE='FL_CT_109'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN, LABEL_FR, FILE_TYPE_ID, FLOW_ID) VALUES ('Rejet Suite Etude Approfondie Cotation - Demande de modification certificat phytosanitaire', 'Rejet Suite Etude Approfondie Cotation - Demande de modification certificat phytosanitaire', 33, (SELECT MAX(ID) FROM FLOW WHERE CODE='FL_CT_116'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN, LABEL_FR, FILE_TYPE_ID, FLOW_ID) VALUES ('Validation Suite Etude Approfondie Cotation - Demande de modification certificat phytosanitaire', 'Validation Suite Etude Approfondie Cotation - Demande de modification certificat phytosanitaire', 33, (SELECT MAX(ID) FROM FLOW WHERE CODE='FL_CT_117'));


INSERT INTO FLOW_GUCE_SIAT(ID, FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES ((SELECT MAX(ID) + 1 FROM FLOW_GUCE_SIAT), 'CTE001M1', 'FL_CT_110', 33);
INSERT INTO FLOW_GUCE_SIAT(ID, FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES ((SELECT MAX(ID) + 1 FROM FLOW_GUCE_SIAT), 'CTE001M3', 'FL_CT_108', 33);
INSERT INTO FLOW_GUCE_SIAT(ID, FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES ((SELECT MAX(ID) + 1 FROM FLOW_GUCE_SIAT), 'CTE001M3', 'FL_CT_113', 33);
INSERT INTO FLOW_GUCE_SIAT(ID, FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES ((SELECT MAX(ID) + 1 FROM FLOW_GUCE_SIAT), 'CTE001M3', 'FL_CT_116', 33);
INSERT INTO FLOW_GUCE_SIAT(ID, FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES ((SELECT MAX(ID) + 1 FROM FLOW_GUCE_SIAT), 'CTE001M4', 'FL_CT_114', 33);
INSERT INTO FLOW_GUCE_SIAT(ID, FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES ((SELECT MAX(ID) + 1 FROM FLOW_GUCE_SIAT), 'CTE001M4', 'FL_CT_117', 33);

INSERT INTO FILE_TYPE_STEP (LABEL_EN,LABEL_FR,FILE_TYPE_ID,STEP_ID) VALUES ('Demande de modification - Certificat phytosanitaire', 'Demande de modification - Certificat phytosanitaire', 33, (SELECT ID FROM STEP WHERE CODE ='ST_CT_51'));
INSERT INTO FILE_TYPE_STEP (LABEL_EN,LABEL_FR,FILE_TYPE_ID,STEP_ID) VALUES ('Recevabilité - Demande de modification certificat phytosanitaire', 'Recevabilité - Demande de modification certificat phytosanitaire', 33, (SELECT ID FROM STEP WHERE CODE ='ST_CT_52'));
INSERT INTO FILE_TYPE_STEP (LABEL_EN,LABEL_FR,FILE_TYPE_ID,STEP_ID) VALUES ('Cotation - Demande de modification certificat phytosanitaire', 'Cotation - Demande de modification certificat phytosanitaire', 33, (SELECT ID FROM STEP WHERE CODE ='ST_CT_53'));

INSERT INTO FILE_TYPE_STEP (LABEL_EN,LABEL_FR,FILE_TYPE_ID,STEP_ID) VALUES ('Rejet - Demande de modification certificat phytosanitaire', 'Rejet - Demande de modification certificat phytosanitaire', 33, (SELECT ID FROM STEP WHERE CODE ='ST_CT_54'));
INSERT INTO FILE_TYPE_STEP (LABEL_EN,LABEL_FR,FILE_TYPE_ID,STEP_ID) VALUES ('Traitement - Demande de modification certificat phytosanitaire', 'Traitement - Demande de modification certificat phytosanitaire', 33, (SELECT ID FROM STEP WHERE CODE ='ST_CT_55'));
INSERT INTO FILE_TYPE_STEP (LABEL_EN,LABEL_FR,FILE_TYPE_ID,STEP_ID) VALUES ('Signature - Demande de modification certificat phytosanitaire', 'Signature - Demande de modification certificat phytosanitaire', 33, (SELECT ID FROM STEP WHERE CODE ='ST_CT_56'));




INSERT INTO STEP_AUTHORITY (STEP_ID, AUTHORITY_ID) VALUES (132, 12);
INSERT INTO STEP_AUTHORITY (STEP_ID, AUTHORITY_ID) VALUES (133, 12);
INSERT INTO STEP_AUTHORITY (STEP_ID, AUTHORITY_ID) VALUES (134, 6);
--INSERT INTO STEP_AUTHORITY (STEP_ID, AUTHORITY_ID) VALUES (135, 17);
--INSERT INTO STEP_AUTHORITY (STEP_ID, AUTHORITY_ID) VALUES (135, 6);
INSERT INTO STEP_AUTHORITY (STEP_ID, AUTHORITY_ID) VALUES (135, 13);
INSERT INTO STEP_AUTHORITY (STEP_ID, AUTHORITY_ID) VALUES (136, 13);
INSERT INTO STEP_AUTHORITY (STEP_ID, AUTHORITY_ID) VALUES (137, 17);


INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES ((SELECT MAX(ID) + 1 FROM DATA_TYPE), (SELECT ID FROM FLOW WHERE CODE = 'FL_CT_110'), 'Observation',  0, 'inputTextarea');
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES ((SELECT MAX(ID) + 1 FROM DATA_TYPE), (SELECT ID FROM FLOW WHERE CODE = 'FL_CT_111'), 'Observation',  0, 'inputTextarea');
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES ((SELECT MAX(ID) + 1 FROM DATA_TYPE), (SELECT ID FROM FLOW WHERE CODE = 'FL_CT_108'), 'Observation',  1, 'inputTextarea');
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES ((SELECT MAX(ID) + 1 FROM DATA_TYPE), (SELECT ID FROM FLOW WHERE CODE = 'FL_CT_109'), 'Observation',  0, 'inputTextarea');
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES ((SELECT MAX(ID) + 1 FROM DATA_TYPE), (SELECT ID FROM FLOW WHERE CODE = 'FL_CT_112'), 'Observation',  0, 'inputTextarea');
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES ((SELECT MAX(ID) + 1 FROM DATA_TYPE), (SELECT ID FROM FLOW WHERE CODE = 'FL_CT_113'), 'Observation',  1, 'inputTextarea');
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES ((SELECT MAX(ID) + 1 FROM DATA_TYPE), (SELECT ID FROM FLOW WHERE CODE = 'FL_CT_114'), 'Observation',  0, 'inputTextarea');
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES ((SELECT MAX(ID) + 1 FROM DATA_TYPE), (SELECT ID FROM FLOW WHERE CODE = 'FL_CT_115'), 'Observation',  1, 'inputTextarea');
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES ((SELECT MAX(ID) + 1 FROM DATA_TYPE), (SELECT ID FROM FLOW WHERE CODE = 'FL_CT_116'), 'Observation',  1, 'inputTextarea');

-- FileTypeFLowReport
INSERT INTO FILE_TYPE_FLOW_REPORT (ID, FILE_FIELD_NAME, FILE_TYPE_ID, FLOW_ID, ORGANISM_ID, REPORT_CLASS_NAME, REPORT_NAME) VALUES((SELECT MAX(ID) + 1 FROM FILE_TYPE_FLOW_REPORT), 'NUMERO_CT_CCT_CP_E', 33, (SELECT MAX(ID) FROM FLOW WHERE CODE = 'FL_CT_114'), 3, 'org.guce.siat.web.reports.exporter.CtCctCpEExporter', 'NUMERO_CT_CCT_CP_E.pdf');
INSERT INTO FILE_TYPE_FLOW_REPORT (ID, FILE_FIELD_NAME, FILE_TYPE_ID, FLOW_ID, ORGANISM_ID, REPORT_CLASS_NAME, REPORT_NAME) VALUES((SELECT MAX(ID) + 1 FROM FILE_TYPE_FLOW_REPORT), 'NUMERO_CT_CCT_CP_E', 33, (SELECT MAX(ID) FROM FLOW WHERE CODE = 'FL_CT_117'), 3, 'org.guce.siat.web.reports.exporter.CtCctCpEExporter', 'NUMERO_CT_CCT_CP_E.pdf');


-- Autre contact
-- Destinataire
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'DESTINATAIRE_AUTRE_CONTACT','Autre Contact','Autre Contact',0,8,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),36,'DESTINATAIRE_AUTRE_CONTACT','Autre Contact','Autre Contact',0,8,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),37,'DESTINATAIRE_AUTRE_CONTACT','Autre Contact','Autre Contact',0,8,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),39,'DESTINATAIRE_AUTRE_CONTACT','Autre Contact','Autre Contact',0,8,1);
-- Déclarant
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'CLIENT_AUTRE_CONTACT','Autre Contact','Autre Contact',0,1,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),36,'CLIENT_AUTRE_CONTACT','Autre Contact','Autre Contact',0,1,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),37,'CLIENT_AUTRE_CONTACT','Autre Contact','Autre Contact',0,1,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),39,'CLIENT_AUTRE_CONTACT','Autre Contact','Autre Contact',0,1,1);