--
INSERT INTO FILE_TYPE_FLOW_REPORT (ID, FILE_FIELD_NAME, FILE_TYPE_ID, FLOW_ID, ORGANISM_ID, REPORT_CLASS_NAME, REPORT_NAME)
VALUES(33, 'NUMERO_CT_CCT_CP_E', 33, 8, 3, 'org.guce.siat.web.reports.exporter.CtCctCpEExporter', 'CT_CCT_CP_E.pdf');
-- REPORT_ORGANISM pour gérer la séquence des numéros de rapport cte
DELETE FROM FILE_TYPE_FLOW WHERE FILE_TYPE_ID = 33 AND FLOW_ID = 11;
DELETE FROM FILE_TYPE_FLOW WHERE FILE_TYPE_ID = 33 AND FLOW_ID = 19;
INSERT INTO REPORT_ORGANISM(ID, SEQUENCE, VALUE, FILE_TYPE_FLOW_REPORT, ORGANISM)
VALUES (REPORT_ORGANISME_SEQ.nextVal, 0, '/CCT/CPE/MINADER', 33, 3);
--
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),33,'POIDS_NET','Poids Net','Net Weight',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),33,'POIDS_BRUT','Poids Brut','Gross Weight',1,1,0);
COMMIT;
-- 1.3.3-SNAPSHOT
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'NUMEROS_LOTS','Numéros Lots','Lots Numbers',0,1,1);
-- 1.3.4
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'EXIGENCES_PHYTOSANITAIRES','Exigences Phytosanitaires','Phytosaniratary Requirements',0,1,1);
-- 1.3.8-TEST
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'TYPE_DOSSIER_EGUCE','Type de dossier e-GUCE','e-GUCE file type',0,1,1);
-- 1.3.10a
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'TYPE_PRODUIT_CODE','Code type produit','Product type code',0,1,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'TYPE_PRODUIT_NOM','Nom type produit','Product type name',0,1,1);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),33,'NOMBRE_SACS','Nombre de sacs','Number of bags',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),33,'NOMBRE_GRUMES','Nombre de grumes','Number of logs',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),36,'UNITE','Unité','Mesure',1,1,0);
--
DELETE FROM FLOW_GUCE_SIAT WHERE FILE_TYPE_ID = 33 OR FILE_TYPE_ID = 36 OR FILE_TYPE_ID = 37 OR FILE_TYPE_ID = 39;

-- not yet
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'INSPECTION_LIEU_INSPECTION_CODE','Code lieu inspection','Inspection place code',0,1,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'INSPECTION_LIEU_INSPECTION_NOM','Nom lieu inspection','Inspection place name',0,1,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'INSPECTION_DATE_INSPECTION_PROPOSEE','Date inspection proposée','Proposed inspection date',0,1,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'INSPECTION_DATE_INSPECTION','Date effective inspection','Inspection effective date',0,1,1);
