/*==============================================================*/
/* Table : REP_MODE_TRANSPORT = MODE DE TRANSPORT               */
/*==============================================================*/
INSERT INTO REP_MODE_TRANSPORT ( MODE_TRANSPORT_CODE, MODE_TRANSPORT_NAME, MODE_TRANSPORT_NAME_EN) VALUES ( 1, 'Le Transport Aérien ', 'Air Transport');
INSERT INTO REP_MODE_TRANSPORT ( MODE_TRANSPORT_CODE, MODE_TRANSPORT_NAME, MODE_TRANSPORT_NAME_EN) VALUES ( 2, 'Le Transport par voie des eaux (maritime et fluvial)', 'Transport by water channel (sea and river)');
INSERT INTO REP_MODE_TRANSPORT ( MODE_TRANSPORT_CODE, MODE_TRANSPORT_NAME, MODE_TRANSPORT_NAME_EN) VALUES ( 3, 'Le Transport Routier ', 'Road Transport');
INSERT INTO REP_MODE_TRANSPORT ( MODE_TRANSPORT_CODE, MODE_TRANSPORT_NAME, MODE_TRANSPORT_NAME_EN) VALUES ( 4, 'Le Transport Ferroviaire ', 'The Rail Transport');
COMMIT;

/*==============================================================*/
/* Table : REP_TYPES_MOYEN_TRANSPORT = MOYEN DE TRANSPORT       */
/*==============================================================*/
INSERT INTO REP_TYPES_MOYEN_TRANSPORT ( MEAN_TRANSPORT_CODE,  MEAN_TRANSPORT_NAME,  MEAN_TRANSPORT_NAME_EN, MEAN_TRANSPORT_PARENT_CODE, MODE_TRANSPORT_CODE) VALUES('TA', 'Le Transport Aérien ', 'Air Transport', 'Air Transport', 1);
INSERT INTO REP_TYPES_MOYEN_TRANSPORT ( MEAN_TRANSPORT_CODE,  MEAN_TRANSPORT_NAME,  MEAN_TRANSPORT_NAME_EN, MEAN_TRANSPORT_PARENT_CODE, MODE_TRANSPORT_CODE) VALUES('TM', 'Le Transport par voie des eaux (maritime et fluvial)', 'Transport by water channel (sea and river)', 'Transport by water channel (sea and river)', 2);
INSERT INTO REP_TYPES_MOYEN_TRANSPORT ( MEAN_TRANSPORT_CODE,  MEAN_TRANSPORT_NAME,  MEAN_TRANSPORT_NAME_EN, MEAN_TRANSPORT_PARENT_CODE, MODE_TRANSPORT_CODE) VALUES('TR', 'Le Transport Routier ', 'Road Transport', 'Road Transport', 3);
INSERT INTO REP_TYPES_MOYEN_TRANSPORT ( MEAN_TRANSPORT_CODE,  MEAN_TRANSPORT_NAME,  MEAN_TRANSPORT_NAME_EN, MEAN_TRANSPORT_PARENT_CODE, MODE_TRANSPORT_CODE) VALUES( 'TF', 'Le Transport Ferroviaire ', 'The Rail Transport', 'The Rail Transport', 4);
COMMIT;

/*==============================================================*/
/* Table : REP_COUNTRY                                          */
/*==============================================================*/
INSERT INTO REP_COUNTRY(COUNTRY_ID_ALPHA2, COUNTRY_ID_NUM, COUNTRY_ID_ALPHA3, LANGUAGE_CODE3, COUNTRY_NAME, COUNTRY_NAME_FR, COUNTRY_NAME_CPL, COUNTRY_NAME_CPL_FR) 
VALUES ('BG', '001', 'BG3', 'BGLC3', 'Bulgaria', 'Bulgarie', 'Bulgaria', 'Bulgaria');
INSERT INTO REP_COUNTRY(COUNTRY_ID_ALPHA2, COUNTRY_ID_NUM, COUNTRY_ID_ALPHA3, LANGUAGE_CODE3, COUNTRY_NAME, COUNTRY_NAME_FR, COUNTRY_NAME_CPL, COUNTRY_NAME_CPL_FR) 
VALUES ('TN', '002', 'TN3', 'TNLC3', 'Tunisia', 'Tunisie', 'Tunisia', 'Tunisia');
INSERT INTO REP_COUNTRY(COUNTRY_ID_ALPHA2, COUNTRY_ID_NUM, COUNTRY_ID_ALPHA3, LANGUAGE_CODE3, COUNTRY_NAME, COUNTRY_NAME_FR, COUNTRY_NAME_CPL, COUNTRY_NAME_CPL_FR) 
VALUES ('TR', '003', 'TR3', 'TRLC3', 'Turkey', 'Turquie', 'Turkey', 'Turkey');
INSERT INTO REP_COUNTRY(COUNTRY_ID_ALPHA2, COUNTRY_ID_NUM, COUNTRY_ID_ALPHA3, LANGUAGE_CODE3, COUNTRY_NAME, COUNTRY_NAME_FR, COUNTRY_NAME_CPL, COUNTRY_NAME_CPL_FR) 
VALUES ('UG', '004', 'UG3', 'UGLC3', 'Uganda', 'Uganda', 'Uganda', 'Uganda');
INSERT INTO REP_COUNTRY(COUNTRY_ID_ALPHA2, COUNTRY_ID_NUM, COUNTRY_ID_ALPHA3, LANGUAGE_CODE3, COUNTRY_NAME, COUNTRY_NAME_FR, COUNTRY_NAME_CPL, COUNTRY_NAME_CPL_FR) 
VALUES ('UA', '005', 'UA3', 'UALC3', 'Ukraine', 'Ukraine', 'Ukraine', 'Ukraine');
INSERT INTO REP_COUNTRY(COUNTRY_ID_ALPHA2, COUNTRY_ID_NUM, COUNTRY_ID_ALPHA3, LANGUAGE_CODE3, COUNTRY_NAME, COUNTRY_NAME_FR, COUNTRY_NAME_CPL, COUNTRY_NAME_CPL_FR) 
VALUES ('GB', '006', 'GB3', 'GBLC3', 'United Kingdom', 'Royaume-Uni', 'United Kingdom', 'United Kingdom');
INSERT INTO REP_COUNTRY(COUNTRY_ID_ALPHA2, COUNTRY_ID_NUM, COUNTRY_ID_ALPHA3, LANGUAGE_CODE3, COUNTRY_NAME, COUNTRY_NAME_FR, COUNTRY_NAME_CPL, COUNTRY_NAME_CPL_FR) 
VALUES ('CM', '007', 'CM3', 'CMLC3', 'Cameroon', 'Cameroun', 'Cameroon', 'Cameroun');
INSERT INTO REP_COUNTRY(COUNTRY_ID_ALPHA2, COUNTRY_ID_NUM, COUNTRY_ID_ALPHA3, LANGUAGE_CODE3, COUNTRY_NAME, COUNTRY_NAME_FR, COUNTRY_NAME_CPL, COUNTRY_NAME_CPL_FR) 
VALUES ('FR', '008', 'FR', 'FR', 'France', 'France', 'France', 'France');
COMMIT;

/*==============================================================*/
/* Table : REP_UNLOCODE = Port                                  */
/*==============================================================*/
INSERT INTO REP_UNLOCODE ( LOCATION_CODE, LOCATION_COORDINATES, LOCATION_DATE, LOCATION_FUNCTION_CODE, LOCATION_IATA_CODE,LOCATION_NAME, LOCATION_NAME_EN, LOCATION_STATUT, SUBDIVISION_CODE, COUNTRY_ID) VALUES( 'RADTN', 'Rades Port', TO_DATE('30/01/2015','dd/mm/yyyy'), 'RADES LOCATION CODE 1122', 'RADES LOCATION IATA CODE 2525', 'Port Maritime International de Rades', 'International Port Rades', 'Ouvert', 'SUBDIVISION CODE SUB01', 'TN');
INSERT INTO REP_UNLOCODE ( LOCATION_CODE, LOCATION_COORDINATES, LOCATION_DATE, LOCATION_FUNCTION_CODE, LOCATION_IATA_CODE, LOCATION_NAME, LOCATION_NAME_EN, LOCATION_STATUT, SUBDIVISION_CODE, COUNTRY_ID ) VALUES( 'BELUK', 'Port de Belfast', TO_DATE('30/01/2015','dd/mm/yyyy'), 'Belfast LOCATION CODE 1122', 'Belfast LOCATION IATA CODE 2525', 'Port Maritime International de Belfast', 'International Port of Belfast', 'Ouvert', 'SUBDIVISION CODE SUB01', 'GB');
COMMIT;

/*==============================================================*/
/* Table : REP_TYPES_PACKAGE = Packaging                        */
/*==============================================================*/
INSERT INTO REP_TYPES_PACKAGE( PACKAGE_TYPE_CODE, PACKAGE_TYPE_DESC, PACKAGE_TYPE_DESC_EN) VALUES ( 'Conteneurs de fret intermodaux', 'Conteneurs de fret intermodaux', 'Intermodal freight containers');
INSERT INTO REP_TYPES_PACKAGE( PACKAGE_TYPE_CODE, PACKAGE_TYPE_DESC, PACKAGE_TYPE_DESC_EN) VALUES ( 'boîte en carton ondulé', 'boîte en carton ondulé', 'Corrugated box');
INSERT INTO REP_TYPES_PACKAGE( PACKAGE_TYPE_CODE, PACKAGE_TYPE_DESC, PACKAGE_TYPE_DESC_EN) VALUES ( 'boîte en bois', 'boîte en bois', 'Wooden box');
INSERT INTO REP_TYPES_PACKAGE( PACKAGE_TYPE_CODE, PACKAGE_TYPE_DESC, PACKAGE_TYPE_DESC_EN) VALUES ( 'caisse', 'caisse', 'Crate');
INSERT INTO REP_TYPES_PACKAGE( PACKAGE_TYPE_CODE, PACKAGE_TYPE_DESC, PACKAGE_TYPE_DESC_EN) VALUES ( 'Conteneur dexpédition vrac', 'Conteneur dexpédition vrac', 'Intermediate bulk shipping container');
INSERT INTO REP_TYPES_PACKAGE( PACKAGE_TYPE_CODE, PACKAGE_TYPE_DESC, PACKAGE_TYPE_DESC_EN) VALUES ( 'Flexible Intermediate Bulk Container', 'Flexible Intermediate Bulk Container', 'Flexible Intermediate Bulk Container');
INSERT INTO REP_TYPES_PACKAGE( PACKAGE_TYPE_CODE, PACKAGE_TYPE_DESC, PACKAGE_TYPE_DESC_EN) VALUES ( 'boîte en vrac', 'boîte en vrac', 'Bulk box');
INSERT INTO REP_TYPES_PACKAGE( PACKAGE_TYPE_CODE, PACKAGE_TYPE_DESC, PACKAGE_TYPE_DESC_EN) VALUES ( 'tambour', 'tambour', 'Drum');
INSERT INTO REP_TYPES_PACKAGE( PACKAGE_TYPE_CODE, PACKAGE_TYPE_DESC, PACKAGE_TYPE_DESC_EN) VALUES ( 'Des conteneurs dexpédition isolés', 'Des conteneurs dexpédition isolés', 'Insulated shipping containers');
INSERT INTO REP_TYPES_PACKAGE( PACKAGE_TYPE_CODE, PACKAGE_TYPE_DESC, PACKAGE_TYPE_DESC_EN) VALUES ( 'seau', 'seau', 'Pail');
INSERT INTO REP_TYPES_PACKAGE( PACKAGE_TYPE_CODE, PACKAGE_TYPE_DESC, PACKAGE_TYPE_DESC_EN) VALUES ( 'Dispositif de charge d unité', 'Dispositif de charge d unité', 'Unit load device');
INSERT INTO REP_TYPES_PACKAGE( PACKAGE_TYPE_CODE, PACKAGE_TYPE_DESC, PACKAGE_TYPE_DESC_EN) VALUES ( 'Certains conteneurs spécialisés d expédition', 'Certains conteneurs spécialisés d expédition', 'Specialized shipping containers');
INSERT INTO REP_TYPES_PACKAGE( PACKAGE_TYPE_CODE, PACKAGE_TYPE_DESC, PACKAGE_TYPE_DESC_EN) VALUES ( 'Transit et Flight Case', 'Transit et Flight Case', 'Transit and Flight Case');
INSERT INTO REP_TYPES_PACKAGE( PACKAGE_TYPE_CODE, PACKAGE_TYPE_DESC, PACKAGE_TYPE_DESC_EN) VALUES ( 'Road Case', 'Road Case', 'Road Case');
COMMIT;

/*==============================================================*/
/* Table : REP_UNIT_MEASURE = Unite de Mesure                   */
/*==============================================================*/
INSERT INTO REP_UNIT_MEASURE ( UNIT_MEASURE_CODE, UNIT_MEASURE_CATEGORY, UNIT_MEASURE_NAME, UNIT_MEASURE_NAME_EN, UNIT_MEASURE_QUANTITY, UNIT_MEASURE_SECTOR) VALUES ( 'm', 'Metre', 'Length', 'Metre', '1', 'Length');
INSERT INTO REP_UNIT_MEASURE ( UNIT_MEASURE_CODE, UNIT_MEASURE_CATEGORY, UNIT_MEASURE_NAME, UNIT_MEASURE_NAME_EN, UNIT_MEASURE_QUANTITY, UNIT_MEASURE_SECTOR) VALUES ( 'kg', 'Kilogram', 'Mass', 'Kilogram', '1', 'Mass');
INSERT INTO REP_UNIT_MEASURE ( UNIT_MEASURE_CODE, UNIT_MEASURE_CATEGORY, UNIT_MEASURE_NAME, UNIT_MEASURE_NAME_EN, UNIT_MEASURE_QUANTITY, UNIT_MEASURE_SECTOR) VALUES ( 's', 'Second', 'Time', 'Second', '1', 'Time');
INSERT INTO REP_UNIT_MEASURE ( UNIT_MEASURE_CODE, UNIT_MEASURE_CATEGORY, UNIT_MEASURE_NAME, UNIT_MEASURE_NAME_EN, UNIT_MEASURE_QUANTITY, UNIT_MEASURE_SECTOR) VALUES ( 'A', 'Ampere', 'Electric current', 'Ampere', '1', 'Electric current');
INSERT INTO REP_UNIT_MEASURE ( UNIT_MEASURE_CODE, UNIT_MEASURE_CATEGORY, UNIT_MEASURE_NAME, UNIT_MEASURE_NAME_EN, UNIT_MEASURE_QUANTITY, UNIT_MEASURE_SECTOR) VALUES ( 'K', 'Kelvin', 'Thermodynamic temperature', 'Kelvin', '1', 'Thermodynamic temperature');
INSERT INTO REP_UNIT_MEASURE ( UNIT_MEASURE_CODE, UNIT_MEASURE_CATEGORY, UNIT_MEASURE_NAME, UNIT_MEASURE_NAME_EN, UNIT_MEASURE_QUANTITY, UNIT_MEASURE_SECTOR) VALUES ( 'mol', 'Amount of substance', 'Mole', 'Mole', '1', 'Amount of substance');
INSERT INTO REP_UNIT_MEASURE ( UNIT_MEASURE_CODE, UNIT_MEASURE_CATEGORY, UNIT_MEASURE_NAME, UNIT_MEASURE_NAME_EN, UNIT_MEASURE_QUANTITY, UNIT_MEASURE_SECTOR) VALUES ( 'cd', 'Luminous intensity', 'Candela', 'Candela', '1', 'Luminous intensity');
COMMIT;

/*==============================================================*/
/* Table : REP_TYPE_EQUIPMENT                                   */
/*==============================================================*/
INSERT INTO REP_TYPE_EQUIPMENT (EQUIPMENT_TYPE_CODE,EQUIPMENT_TYPE_NAME,EQUIPMENT_TYPE_NAME_EN) VALUES ('vcc','Conteneur aéré fermé','Ventilated container closed');
INSERT INTO REP_TYPE_EQUIPMENT (EQUIPMENT_TYPE_CODE,EQUIPMENT_TYPE_NAME,EQUIPMENT_TYPE_NAME_EN) VALUES ('pbcoscs','conteneur type plate-forme à parois latérales ouvertes et superstructure complète','Platform based container open sided with complete superstructure');
INSERT INTO REP_TYPE_EQUIPMENT (EQUIPMENT_TYPE_CODE,EQUIPMENT_TYPE_NAME,EQUIPMENT_TYPE_NAME_EN) VALUES ('pbcos','conteneur type plate-forme à parois latérales ouvertes','Platform based container open sided');
INSERT INTO REP_TYPE_EQUIPMENT (EQUIPMENT_TYPE_CODE,EQUIPMENT_TYPE_NAME,EQUIPMENT_TYPE_NAME_EN) VALUES ('otp','conteneur à toit ouvert','open top container');
INSERT INTO REP_TYPE_EQUIPMENT (EQUIPMENT_TYPE_CODE,EQUIPMENT_TYPE_NAME,EQUIPMENT_TYPE_NAME_EN) VALUES ('cpbisfe','conteneur type plate-forme à superstructure incomplète et extrémités fixes','container platform based on incomplete superstructure and fixed ends');
INSERT INTO REP_TYPE_EQUIPMENT (EQUIPMENT_TYPE_CODE,EQUIPMENT_TYPE_NAME,EQUIPMENT_TYPE_NAME_EN) VALUES ('cpisfe','conteneur plate-forme à superstructure incomplète et extrémités repliables','container platform with incomplete superstructure and folding ends');
INSERT INTO REP_TYPE_EQUIPMENT (EQUIPMENT_TYPE_CODE,EQUIPMENT_TYPE_NAME,EQUIPMENT_TYPE_NAME_EN) VALUES ('cp','conteneur plate-forme','container platform');
INSERT INTO REP_TYPE_EQUIPMENT (EQUIPMENT_TYPE_CODE,EQUIPMENT_TYPE_NAME,EQUIPMENT_TYPE_NAME_EN) VALUES ('thc','conteneur à caractéristiques thermiques','Thermal container');
INSERT INTO REP_TYPE_EQUIPMENT (EQUIPMENT_TYPE_CODE,EQUIPMENT_TYPE_NAME,EQUIPMENT_TYPE_NAME_EN) VALUES ('ic','conteneur isotherme','insulated container');
INSERT INTO REP_TYPE_EQUIPMENT (EQUIPMENT_TYPE_CODE,EQUIPMENT_TYPE_NAME,EQUIPMENT_TYPE_NAME_EN) VALUES ('rc','conteneur réfrigéré (à réfrigérant renouvelable)','Refrigerated container (expendable refrigerant)');
INSERT INTO REP_TYPE_EQUIPMENT (EQUIPMENT_TYPE_CODE,EQUIPMENT_TYPE_NAME,EQUIPMENT_TYPE_NAME_EN) VALUES ('mrc','conteneur réfrigéré mécaniquement','mechanically refrigerated container');
INSERT INTO REP_TYPE_EQUIPMENT (EQUIPMENT_TYPE_CODE,EQUIPMENT_TYPE_NAME,EQUIPMENT_TYPE_NAME_EN) VALUES ('hc','conteneur chauffé','heated container');
INSERT INTO REP_TYPE_EQUIPMENT (EQUIPMENT_TYPE_CODE,EQUIPMENT_TYPE_NAME,EQUIPMENT_TYPE_NAME_EN) VALUES ('rhc','conteneur réfrigéré et chauffé','Refrigerated and heated container');
INSERT INTO REP_TYPE_EQUIPMENT (EQUIPMENT_TYPE_CODE,EQUIPMENT_TYPE_NAME,EQUIPMENT_TYPE_NAME_EN) VALUES ('tc','conteneur-citerne','tank-container');
INSERT INTO REP_TYPE_EQUIPMENT (EQUIPMENT_TYPE_CODE,EQUIPMENT_TYPE_NAME,EQUIPMENT_TYPE_NAME_EN) VALUES ('cdb','conteneur pour marchandises solides en vrac','container for dry bulk');
INSERT INTO REP_TYPE_EQUIPMENT (EQUIPMENT_TYPE_CODE,EQUIPMENT_TYPE_NAME,EQUIPMENT_TYPE_NAME_EN) VALUES ('sc','conteneur spécialisé','specialized container');
INSERT INTO REP_TYPE_EQUIPMENT (EQUIPMENT_TYPE_CODE,EQUIPMENT_TYPE_NAME,EQUIPMENT_TYPE_NAME_EN) VALUES ('ac','conteneur aérien','air container');
COMMIT;

/*==============================================================*/
/* Table : REP_NSH                                              */
/*==============================================================*/
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('18069031004', null,null,'Autres chocolat et artciles en chocolat, fourres','Other chocolate and chocolate items vary, thickets');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('19059045922', null,null,'Autres biscuits non additionnes d''edulcorants ne contenant pasde cacao ou contenant moins de 20% de cacao','Other non biscuits added together to sweeteners containing ACSD cocoa or containing less than 20% cocoa');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('19059020101', null,null,'Pâtes alimentaires','pasta');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('33061000006', null,null,'Dentifrice','Toothpastes');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('33069000093', null,null,'Préparation pour l''hygiène buccale ou dentaire','Preparation for oral or dental hygiene');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('85163190005', null,null,'Sèche cheveux','Hair dryer');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('84263000003', null,null,'Grues sur portiques u','Gantry cranes u');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('90181990024', null,null,'Cardioscopes','Cardioscopes');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('44061000013', null,null,'Sac','Sac');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('55061002143', null,null,'Pantallon','Pantallon');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('66061000874', null,null,'Chaise','Chaise');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('77061009842', null,null,'Pull','Pull');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('88061000214', null,null,'Ecran','Ecran');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('99061000214', null,null,'Lunette','Lunette');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('36061550002', null,null,'PC','PC');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('85061020265', null,null,'Fruits','Fruits');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('55000045458', null,null,'Or','Or');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('87884245458', null,null,'Argent','Argent');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('36161000214', null,null,'cites','cites');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('36121458214', null,null,'Couleur','Couleur');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('56001232133', null,null,'Autre bois  ','bois');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('11111111111', null,null,'Plastique','Plastique');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('22222222222', null,null,'Vêtement','Vêtement');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('33333333333', null,null,'Cigarette','Cigarette');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('44444444444', null,null,'Ballon','Ballon');

--NSH GUCE

-- CO_MINFOF_FAUNE
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC,GOODS_ITEM_DESC_EN)  VALUES ('85401111017',null,null,'TUBES CATHODIQUES POUR RECEPTEURS DE TELEVISION,EN COULEUR,PRESENTANT UN RAPPORT LARGEUR/HAUTEUR DE L''ECRAN INFERIEUR A 1,5 ET DONT LA DIAGONALE DE L''ECRAN N''EXCEDE PAS 42 CM  *','TUBES CATHODIQUES POUR RECEPTEURS DE TELEVISION,EN COULEUR,PRESENTANT UN RAPPORT LARGEUR/HAUTEUR DE L''ECRAN INFERIEUR A 1,5 ET DONT LA DIAGONALE DE L''ECRAN N''EXCEDE PAS 42 CM  *');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC,GOODS_ITEM_DESC_EN)  VALUES ('85171990102',null,null,'AUTRES POSTES TELEPHONIQUES D''USAGERS,A CARACTERES ORNEMENTAL,EN PIERRES DURES,EN BOIS,EN IVOIRE OU EN METAUX COMMUNS PLAQUES OU DOUBLES DE METAUX PRECIEUX *','AUTRES POSTES TELEPHONIQUES D''USAGERS,A CARACTERES ORNEMENTAL,EN PIERRES DURES,EN BOIS,EN IVOIRE OU EN METAUX COMMUNS PLAQUES OU DOUBLES DE METAUX PRECIEUX *');
-- Example CO_MINFOF_FORET
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('40544784438', null,null,'FORET MINFOFO','FORET MINFOF');

--AS_MINADER	Autorisation Spéciale - MINADER
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('84289071004', null,null,'CHARGEURS SPÉCIALEMENT CONÇUS POUR L''EXPLOITATION AGRICOLE,CONÇUS POUR ETRE PORTÉS PAR TRACTEUR AGRICOLE *','CHARGEURS SPÉCIALEMENT CONÇUS POUR L''EXPLOITATION AGRICOLE,CONÇUS POUR ETRE PORTÉS PAR TRACTEUR AGRICOLE *');

--CAT_MINADER	Certification des Appareils de Traitement
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('84332090000', null,null,'AUTRES FAUCHEUSES,Y COMPRIS LES BARRES DE COUPE A MOTEUR SUR TRACTEUR *','AUTRES FAUCHEUSES,Y COMPRIS LES BARRES DE COUPE A MOTEUR SUR TRACTEUR *');	

--PIVPSRP_MINADER	Permis d’Importation des végétaux et produits soumis à la réglementation phytosanitaire
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('23011000078', null,null,'CRETONS DESTINÉS A ETRE UTILISÉS COMME ENGRAIS *','CRETONS DESTINÉS A ETRE UTILISÉS COMME ENGRAIS *');	

-- CP_MINEPDED
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC,GOODS_ITEM_DESC_EN)  VALUES ('31010000096',null,null,'Autres engrais d''origine animale ou végétale, même mélangésentre eux ou traités chimiquement, autres engrais résultantdu mélange ou du traitement chimique de produits d''origine animale ou végétale *"','Autres engrais d''origine animale ou végétale, même mélangésentre eux ou traités chimiquement, autres engrais résultantdu mélange ou du traitement chimique de produits d''origine animale ou végétale *');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC,GOODS_ITEM_DESC_EN) VALUES ('85122000920',null,null,'PHARES DE TOUS GENRES Y COMPRIS LES PROJECTEURS POUR AUTOMOBILES *','PHARES DE TOUS GENRES Y COMPRIS LES PROJECTEURS POUR AUTOMOBILES *');
--AI_MINSTANTE
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC,GOODS_ITEM_DESC_EN)  VALUES ('29242930005',null,null,'PARACETAMOL (DCI) *','PARACETAMOL (DCI) *');
--CEA MINMIDT
INSERT INTO REP_NSH (GOODS_ITEM_CODE,CUSTOMS_STATUS_CODE,GOODS_ITEM_CHAPTER_CODE,GOODS_ITEM_DESC,GOODS_ITEM_DESC_EN) VALUES ('71069110903',null,null,'ARGENT ET ALLIAGES D''ARGENT,SOUS FORMES BRUTES,PRESENTÉS AUTREMENT,TITRANT 999°/00 OU PLUS *','ARGENT ET ALLIAGES D''ARGENT,SOUS FORMES BRUTES,PRESENTÉS AUTREMENT,TITRANT 999°/00 OU PLUS *');

-- AI MINMIDAT
INSERT INTO REP_NSH (GOODS_ITEM_CODE,CUSTOMS_STATUS_CODE,GOODS_ITEM_CHAPTER_CODE,GOODS_ITEM_DESC,GOODS_ITEM_DESC_EN) VALUES ('28433000004',null,null,'COMPOSES D''OR *','COMPOSES D''OR *');


--AS_MINFOF
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('44011000000', null,null,'BOIS DE CHAUFFAGE EN RONDINS, BUCHES,RAMILLES, FAGOTS OU SOUS FORMES SIMILAIRES *','BOIS DE CHAUFFAGE EN RONDINS, BUCHES, RAMILLES, FAGOTS OU SOUS FORMES SIMILAIRES *');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('85118090016', null,null,'AUTRES BOUGIES DE CHAUFFAGE','AUTRES BOUGIES DE CHAUFFAGE');

--DI_MINCOMMERCE
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('87042110116', null,null,'VEHICULES AUTOMOBILES SPECIALEMENT CONÇUS','VEHICULES AUTOMOBILES SPECIALEMENT CONÇUS');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('33012961907', null,null,'AUTRES HUILES ESSENTIELLES ,NON DÉTERPÉNÉES *','AUTRES HUILES ESSENTIELLES ,NON DÉTERPÉNÉES *');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('85281252099', null,null,'AUTRES APP. RECEPTEURS DE TÉLÉVISION,EN','AUTRES APP. RECEPTEURS DE TÉLÉVISION,EN');

--AS_MINCOMMERCE
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('87032310101', null,null,'Voitures de tourisme et autres véhicules automobiles principalement conçus pour le transport de personnes (autres que ceux du n° 87.02), y compris les voitures du type << break >> et les voitures de course.   -§-   -- A un essieu moteur(*)','Voitures de tourisme et autres véhicules automobiles principalement conçus pour le transport de personnes (autres que ceux du n° 87.02), y compris les voitures du type << break >> et les voitures de course.   -§-   -- A un essieu moteur(*)');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('84614090002', null,null,'AUTRES MACHINES A FINIR LES ENGRENAGES, TRAVAILLANT PAR ENLEVEMENT DE METAL OU DE CERMETS *','AUTRES MACHINES A FINIR LES ENGRENAGES, TRAVAILLANT PAR ENLEVEMENT DE METAL OU DE CERMETS *');

--DE_MINCOMMERCE
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('18010000102', null,null,'CACAO EN FÈVES ET BRISURES DE FÈVES,BRUTS *','CACAO EN FÈVES ET BRISURES DE FÈVES,BRUTS *');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('28211000013', null,null,'OXYDES DE FER *','OXYDES DE FER *');

--IDI MINCOMMERCE 
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('49119900040', null,null,'FORMULAIRES D''IMPORTATION TEMPORAIRE OU DE CIRCULATION INTERNATIONALE,EXPEDIES AUX ASSOCIATIONS DE TOURISME ACCREDITES PAR LEURS ASSOCIATIONS CORRESPONDANTES OU LES DOUANES ETRANGERES*','FORMULAIRES D''IMPORTATION TEMPORAIRE OU DE CIRCULATION INTERNATIONALE,EXPEDIES AUX ASSOCIATIONS DE TOURISME ACCREDITES PAR LEURS ASSOCIATIONS CORRESPONDANTES OU LES DOUANES ETRANGERES*');

--IDE MINCOMMERCE 
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('98020000007', null,null,'MOBILIERS ET EFFETS PERSONNELS IMPORTÉS OU EXPORTÉS EN SUITE DE CHAMGEMENT DE RESIDENCE OU POUR RÉSIDENCE SECONDAIRE *','MOBILIERS ET EFFETS PERSONNELS IMPORTÉS OU EXPORTÉS EN SUITE DE CHAMGEMENT DE RESIDENCE OU POUR RÉSIDENCE SECONDAIRE *');

--BSBE
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('44041000012', null,null,'BOIS DE CONIFERES,EN ECLISSES,LAMES,RUBANS ET SIMILAIRES *','BOIS DE CONIFERES,EN ECLISSES,LAMES,RUBANS ET SIMILAIRES *');

--LVTB
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('44012200006', null,null,'BOIS EN PLAQUETTES OU EN PARTICULES,AUTRES QUE DE CONIFERES *','BOIS EN PLAQUETTES OU EN PARTICULES,AUTRES QUE DE CONIFERES *');

--AEX_MINMIDT
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('13021998014', null,null,'Pulpe d Aloes','Pulpe d Aloes');

--MINADER-CCT
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('11023000002', null,null,'FARINE DE RIZ *','FARINE DE RIZ *');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('19049010906', null,null,'AUTRE RIZ, EN GRAINS OU SOUS FORME DE FLOCONS OU AUTRES GRAINS TRAVAILLÉS (EXCEPTION DE LA FARINE,DU GRUAUX ET DE LA SEMOULE),AUTREMENT PRÉPARÉS,NON DENOMMÉS NI COMPRISES AILLEURS *','AUTRE RIZ, EN GRAINS OU SOUS FORME DE FLOCONS OU AUTRES GRAINS TRAVAILLÉS (EXCEPTION DE LA FARINE,DU GRUAUX ET DE LA SEMOULE),AUTREMENT PRÉPARÉS,NON DENOMMÉS NI COMPRISES AILLEURS *');

--MINADER-CC
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('84336000097', null,null,'MACHINES POUR LR NETTOYAGE OU LE TIRAGE DES OEUFS OU AUTRES PRODUITS AGRICOLES *','MACHINES POUR LR NETTOYAGE OU LE TIRAGE DES OEUFS OU AUTRES PRODUITS AGRICOLES *');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('87019025008', null,null,'TRACTEURS AGRICOLES ET TRACTEURS FORESTIERS(EXCLUSION DES MOTOCULTEURS),A ROUES,UNE PUISSANCE DE MOTEUR,EXCEDANT 37KW MAIS N''EXCEDANT PAS 59 KW ,NEUFS *','TRACTEURS AGRICOLES ET TRACTEURS FORESTIERS(EXCLUSION DES MOTOCULTEURS),A ROUES,UNE PUISSANCE DE MOTEUR,EXCEDANT 37KW MAIS N''EXCEDANT PAS 59 KW ,NEUFS *');

--MINADER-CQ
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('84368099093', null,null,'AUTRES MACHINES ET APPAREILS POUR AGRICULTURE,HORTICULTURE,LA SYLVICULTURE ET APICULTURE,Y COMPRIS LES GERMOIRS COMPORTANT DES DISPOSITIFS MÉCANIQUES OU THERMIQUES *','AUTRES MACHINES ET APPAREILS POUR AGRICULTURE,HORTICULTURE,LA SYLVICULTURE ET APICULTURE,Y COMPRIS LES GERMOIRS COMPORTANT DES DISPOSITIFS MÉCANIQUES OU THERMIQUES *');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('73089099012', null,null,'SERRES AGRICOLES EN FONTE,FER OU ACIER*','SERRES AGRICOLES EN FONTE,FER OU ACIER*');

--MINEPIA-CCT
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('87019020003', null,null,'TRACTEURS AGRICOLES ET TRACTEURS FORESTIERS (EXCLUSION DES MOTOCULTEURS),A ROUES,UNE PUISSANCE DE MOTEUR EXCEDANT 18 KW MAIS EXCEDANT PAS 37 KW, NEUFS *','TRACTEURS AGRICOLES ET TRACTEURS FORESTIERS (EXCLUSION DES MOTOCULTEURS),A ROUES,UNE PUISSANCE DE MOTEUR EXCEDANT 18 KW MAIS EXCEDANT PAS 37 KW, NEUFS *');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('84248130006', null,null,'AUTRES APPAREILS PORTATIFS,A PROJETER,DISPERSER OU PULVERISER DES MATIÈRES LIQUIDES OU EN POUDRE,POUR AGRICULTURE OU HOTICULTURE *','AUTRES APPAREILS PORTATIFS,A PROJETER,DISPERSER OU PULVERISER DES MATIÈRES LIQUIDES OU EN POUDRE,POUR AGRICULTURE OU HOTICULTURE *');

--MINEPDED-CCT
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('94042190008', null,null,'MATELATS EN MATIÈRES PLASTIQUES ALVÉOLAIRE,RECOUVERTS OU NON *','MATELATS EN MATIÈRES PLASTIQUES ALVÉOLAIRE,RECOUVERTS OU NON *');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('39100000102', null,null,'SILICONES SOUS FORMES PRIMAIRES OBTENUS PAR RECYCLAGE DES DECHETS,ROGNURES ET DEBRIS DES MATIERES PLASTIQUES *','SILICONES SOUS FORMES PRIMAIRES OBTENUS PAR RECYCLAGE DES DECHETS,ROGNURES ET DEBRIS DES MATIERES PLASTIQUES *');

--MINFOF-CCT
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('44121900000', null,null,'AUTRES BOIS CONTRE-PLAQUES CONSTITUES EXCLUSIVEMENT DE FEUILLES DE BOIS DONT CHACUNE A UNE EPAISSEUR EXCEDANT PAS 6MM*','AUTRES BOIS CONTRE-PLAQUES CONSTITUES EXCLUSIVEMENT DE FEUILLES DE BOIS DONT CHACUNE A UNE EPAISSEUR EXCEDANT PAS 6MM*');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('44041000023', null,null,'BOIS DE CONIFERES,SIMPLEMENT DEGROSSIS OU ARRONDIS,MAIS NON TOURNES NI COURBES NI AUTREMENT TRAVAILLES,POUR CANNES,PARAPLUIES,MANCHES OUTILS OU SIMILAIRES *','BOIS DE CONIFERES,SIMPLEMENT DEGROSSIS OU ARRONDIS,MAIS NON TOURNES NI COURBES NI AUTREMENT TRAVAILLES,POUR CANNES,PARAPLUIES,MANCHES OUTILS OU SIMILAIRES *');

--MINMIDT-CCT
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('26122010003', null,null,'MONAZITE; URANOTHORIANITE ET AUTRES MINERAIS DE THORIUM, UNE TENEUR EN THORIUM SUPÉRIEURE A 20% EN POIDS *','MONAZITE; URANOTHORIANITE ET AUTRES MINERAIS DE THORIUM, UNE TENEUR EN THORIUM SUPÉRIEURE A 20% EN POIDS *');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('84806010001', null,null,'MOULES POUR LE MOULAGE PAR COMPESSION DES MATIERES MINERALES *','MOULES POUR LE MOULAGE PAR COMPESSION DES MATIERES MINERALES *');

--MINSANTE-CCT
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('90301010005', null,null,'INSTRUMENTS ET APPAREILS POUR LA MESURE OU LA DETECTION DES RADIATIONS IONISANTES,DESTINÉS A DES AÉRONEFS CIVILS *','INSTRUMENTS ET APPAREILS POUR LA MESURE OU LA DETECTION DES RADIATIONS IONISANTES,DESTINÉS A DES AÉRONEFS CIVILS *');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('90301090007', null,null,'AUTRES INSTRUMENTS ET APPAREILS POUR LA MESURE OU LA DÉTECTION DES RADIATIONS IONISANTES *','AUTRES INSTRUMENTS ET APPAREILS POUR LA MESURE OU LA DÉTECTION DES RADIATIONS IONISANTES *');

--MINADER-AH
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('28342100104', null,null,'NITRATES DE POTASSIUM A USAGES ENGRAIS *','NITRATES DE POTASSIUM A USAGES ENGRAIS *');

--MINADER-DI
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('28369990015', null,null,'PEROXOCARBONATES (PERCARBONATES) DE POTASSIUM A USAGES ENGRAIS *','PEROXOCARBONATES (PERCARBONATES) DE POTASSIUM A USAGES ENGRAIS *');

--MINADER-EH
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('28342980106', null,null,'NITRATES DE CALCIUM A USAGE ENGRAIS *','NITRATES DE CALCIUM A USAGE ENGRAIS *');

--AT-MINEPIA
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('03022990016', null,null,'RAIES, FRAIS OU RÉFRIGÉRÉS, EXCEPTION DES FILETS ET CHAIR DE POISSONS DU N° 03.04 ET A EXCLUSION DES FOIES,OEUFS ET LAITANCES *','RAIES, FRAIS OU RÉFRIGÉRÉS, EXCEPTION DES FILETS ET CHAIR DE POISSONS DU N° 03.04 ET A EXCLUSION DES FOIES,OEUFS ET LAITANCES *');

--VT-MINEPIA
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('03023390001', null,null,'AUTRES LISTAOS OU BONITES A VENTRE RAYE,FRAIS OU RÉFRIGÉRÉS EXCEPTION DES FILETS ET CHAIR DE POISSONS DU N 03.04 ET EXCLUSION DES FOIES,OEUFS ET LAITANCES *','AUTRES LISTAOS OU BONITES A VENTRE RAYE,FRAIS OU RÉFRIGÉRÉS EXCEPTION DES FILETS ET CHAIR DE POISSONS DU N 03.04 ET EXCLUSION DES FOIES,OEUFS ET LAITANCES *');

--AT-MINSANTE
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('28044000005', null,null,'OXYGENE *','OXYGENE *');

--VTP-MINSANTE
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('29145000008', null,null,'CETONES-PHENOLS ET CETONES CONTENANT AUTRES FONCTIONS OXYGENEES *','CETONES-PHENOLS ET CETONES CONTENANT AUTRES FONCTIONS OXYGENEES *');

--VTD-MINSANTE
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('90192000093', null,null,'PARTIES APPAREILS AZONOTHÉRAPIE, OXYGÉNOTHÉRAPIE, AÉROSOLTHÉRAPIE,APPAREILS RESPIRATOIRES DE RÉANIMATION ET AUTRES APPAREILS DE THÉRAPIE RESPIRATOIRE *','PARTIES APPAREILS AZONOTHÉRAPIE, OXYGÉNOTHÉRAPIE, AÉROSOLTHÉRAPIE,APPAREILS RESPIRATOIRES DE RÉANIMATION ET AUTRES APPAREILS DE THÉRAPIE RESPIRATOIRE *');

--VT-MINEPDED 
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('27111100908', null,null,'AUTRE GAZ NATUREL LIQUEFIÉS *','AUTRE GAZ NATUREL LIQUEFIÉS *');

--MINADER-AE
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('28342100105', null,null,'NITRATES A USAGES ENGRAIS *','NITRATES A USAGES ENGRAIS *');

--NSH Formation
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('01020304050', null,null,'BOIS DE CHAUFFAGE EN RONDINS, BUCHES,RAMILLES, FAGOTS OU SOUS FORMES SIMILAIRES *','BOIS DE CHAUFFAGE EN RONDINS, BUCHES,RAMILLES, FAGOTS OU SOUS FORMES SIMILAIRES *');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('05040302010', null,null,'BOUGIE DE CHAUFFAGE','BOUGIE DE CHAUFFAGE');

--MINCOMMERCE-CCT --> Provisoire
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('94042195555', null,null,'MATELATS *','MATELATS *');
INSERT INTO REP_NSH (GOODS_ITEM_CODE, CUSTOMS_STATUS_CODE, GOODS_ITEM_CHAPTER_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('39100005555', null,null,'SILICONES *','SILICONES *');

INSERT INTO REP_NSH (GOODS_ITEM_CODE, GOODS_ITEM_DESC, GOODS_ITEM_DESC_EN) VALUES ('85168091003', 'AUTRES RESISTANCES CHAUFFANTES,AUTRES QUE CELLES DU N� 85.45,MONTEES SUR UN SUPPORT EN MATIERE ISOLANTE *', 'AUTRES RESISTANCES CHAUFFANTES,AUTRES QUE CELLES DU N� 85.45,MONTEES SUR UN SUPPORT EN MATIERE ISOLANTE *');

COMMIT;

/*==============================================================*/
/* Table : SERVICES_ITEM                                        */
/*==============================================================*/
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '03', 0,'Autres chocolat et artciles en chocolat, fourres','N','18069031004',30);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, NULL, 0, 'Autres biscuits non additionnes d''edulcorants ne contenant pasde cacao ou contenant moins de 20% de cacao', 'N', '19059045922', 30);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, NULL, 0, 'Pâtes alimentaires', 'N', '19059020101', 40);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, NULL, 0, 'Dentifrice', 'N', '33061000006', 40);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, NULL, 0, 'Préparation pour l''hygiène buccale ou dentaire', 'N', '33069000093', 30);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, NULL, 0, 'Sèche cheveux', 'N', '85163190005', 30);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, NULL, 0, 'Sèche cheveux', 'N', '85163190005', 30);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, NULL, 0, 'Cardioscopes', 'N', '90181990024', 30);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '01', 0, 'Grues sur portiques u', 'S', '84263000003', 52);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '01', 0, 'Lindt', 'S', '18069031004', 40);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '02', 0, 'Kinder', 'S', '18069031004', 99);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '01', 0, 'seché cheveux pour coiffure', 'S', '85163190005', 83);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '02', 0, 'seche filas (pour plomberie)', 'S','85163190005', 19);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '02', 0, 'Grue CAT', 'S', '84263000003', 9);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '03', 0, 'Grues sur portiques u', 'S', '84263000003', 190);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '04', 0, 'Grue pour service DPM', 'S', '84263000003', 11);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '01', 0, 'Signal 2', 'S', '33061000006', 68);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '01', 0, 'Sac Bershka', 'S', '44061000013', 183);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '01', 0, 'Pantallon Jean', 'S', '55061002143', 97);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '01', 0, 'Chaise Meublentub', 'S', '66061000874', 70);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '01', 0, 'Pull jaune', 'S', '77061009842', 121);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '01', 0, 'Ecran Acer', 'S', '88061000214', 127);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '01', 0, 'Ray ban', 'S', '99061000214', 159);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '01', 0, 'Dell', 'S', '36061550002', 211);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '02', 0, 'Pomme', 'S', '85061020265', 217);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '01', 0, 'Or', 'S', '55000045458', 251);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '01', 0, 'Argent', 'S', '87884245458', 251);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '01', 0, 'CITES', 'S', '36161000214', 176);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '01', 0, 'Orange', 'S', '36121458214', 247);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '03', 0, 'Bois ', 'S', '56001232133', 176);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '01', 0, 'Bouteille ', 'S', '11111111111', 30);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '02', 0, 'Chaise ', 'S', '11111111111', 30);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '03', 0, 'Stylo ', 'S', '11111111111', 30);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '01', 0, 'Robe ', 'S', '22222222222', 30);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '02', 0, 'Pantallon ', 'S', '22222222222', 30);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '03', 0, 'Chemise ', 'S', '22222222222', 30);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '01', 0, 'Marlboro ', 'S', '33333333333', 30);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '02', 0, 'Inter ', 'S', '33333333333', 30);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '03', 0, 'Mars ', 'S', '33333333333', 30);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '01', 0, 'Tennis ', 'S', '44444444444', 30);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '02', 0, 'Foot', 'S', '44444444444', 30);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '03', 0, 'Baskett', 'S', '44444444444', 30);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, '02', 0, 'Police', 'S', '99061000214', 333);

--SERVICES_ITEM -GUCE

--CO_MINFOF_FAUNE
INSERT INTO SERVICES_ITEM (ID, CODE, DELETED,LABEL,  TYPE, NSH_ID, SERVICE_ID) VALUES (SERVICES_ITEM_SEQ.nextVal,null,0,'TUBES CATHODIQUES POUR RECEPTEURS DE TELEVISION,EN COULEUR,PRESENTANT UN RAPPORT LARGEUR/HAUTEUR DE L''ECRAN INFERIEUR A 1,5 ET DONT LA DIAGONALE DE L''ECRAN N''EXCEDE PAS 42 CM  *','N','85401111017','157');
INSERT INTO SERVICES_ITEM (ID, CODE, DELETED,LABEL,  TYPE, NSH_ID, SERVICE_ID) VALUES (SERVICES_ITEM_SEQ.nextVal,null,'0','AUTRES POSTES TELEPHONIQUES D''USAGERS,A CARACTERES ORNEMENTAL,EN PIERRES DURES,EN BOIS,EN IVOIRE OU EN METAUX COMMUNS PLAQUES OU DOUBLES DE METAUX PRECIEUX *','N','85171990102','157');
-- Example CO_MINFOF_FORET
INSERT INTO SERVICES_ITEM (ID, CODE, DELETED,LABEL,  TYPE, NSH_ID, SERVICE_ID) VALUES (SERVICES_ITEM_SEQ.nextVal,null,0,'TUBES CATHODIQUES POUR RECEPTEURS DE TELEVISION,EN COULEUR,PRESENTANT UN RAPPORT LARGEUR/HAUTEUR DE L''ECRAN INFERIEUR A 1,5 ET DONT LA DIAGONALE DE L''ECRAN N''EXCEDE PAS 42 CM  *','N','40544784438','176');

-- CP_MINEPDED
INSERT INTO SERVICES_ITEM (ID, CODE, DELETED,LABEL,  TYPE, NSH_ID, SERVICE_ID) VALUES (SERVICES_ITEM_SEQ.nextVal,null,0,'Autres engrais d''origine animale ou végétale, même mélangésentre eux ou traités chimiquement, autres engrais résultantdu mélange ou du traitement chimique de produits d''origine animale ou végétale *','N','31010000096','70');
INSERT INTO SERVICES_ITEM (ID, CODE, DELETED,LABEL,  TYPE, NSH_ID, SERVICE_ID) VALUES (SERVICES_ITEM_SEQ.nextVal,null,0,'PHARES DE TOUS GENRES Y COMPRIS LES PROJECTEURS POUR AUTOMOBILES ','N','85122000920','70');
-- AI_MINSTANTE
INSERT INTO SERVICES_ITEM (ID, CODE, DELETED,LABEL,  TYPE, NSH_ID, SERVICE_ID) VALUES (SERVICES_ITEM_SEQ.nextVal,null,0,'PARACETAMOL (DCI) *','N','29242930005','99');

--AS_MINADER	Autorisation Spéciale - MINADER
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'CHARGEURS SPÉCIALEMENT CONÇUS POUR L''EXPLOITATION AGRICOLE,CONÇUS POUR ETRE PORTÉS PAR TRACTEUR AGRICOLE *','N','84289071004',9);
	
--CAT_MINADER	Certification des Appareils de Traitement
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'AUTRES FAUCHEUSES,Y COMPRIS LES BARRES DE COUPE A MOTEUR SUR TRACTEUR *','N','84332090000',11);	

--PIVPSRP_MINADER	Permis d’Importation des végétaux et produits soumis à la réglementation phytosanitaire
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'CRETONS DESTINÉS A ETRE UTILISÉS COMME ENGRAIS *','N','23011000078',19);	

--CEA MINMIDT
INSERT INTO SERVICES_ITEM (ID, CODE, DELETED,LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES (SERVICES_ITEM_SEQ.nextVal,null,0,'ARGENT ET ALLIAGES D''ARGENT,SOUS FORMES BRUTES,PRESENTÉS AUTREMENT,TITRANT 999°/00 OU PLUS *','N','71069110903','190');
-- AI MINMIDAT
INSERT INTO SERVICES_ITEM (ID, CODE, DELETED,LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES (SERVICES_ITEM_SEQ.nextVal,null,0,'COMPOSES D''OR *','N','28433000004','127');

--AS_MINFOF
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'BOIS DE CHAUFFAGE EN RONDINS, BUCHES, RAMILLES, FAGOTS OU SOUS FORMES SIMILAIRES *','N','44011000000',159);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'AUTRES BOUGIES DE CHAUFFAGE','N','85118090016',159);

--DI_MINCOMMERCE
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'VEHICULES AUTOMOBILES SPECIALEMENT CONÇUS','N','87042110116',251);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'AUTRES HUILES ESSENTIELLES ,NON DÉTERPÉNÉES *','N','33012961907',251);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'AUTRES APP. RECEPTEURS DE TÉLÉVISION,EN','N','85281252099',251);

--AS_MINCOMMERCE
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'Voitures de tourisme et autres véhicules automobiles principalement conçus pour le transport de personnes (autres que ceux du n° 87.02), y compris les voitures du type << break >> et les voitures de course.   -§-   -- A un essieu moteur(*)','N','87032310101',247);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'AUTRES MACHINES A FINIR LES ENGRENAGES, TRAVAILLANT PAR ENLEVEMENT DE METAL OU DE CERMETS *','N','84614090002',247);

--DE_MINCOMMERCE
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'CACAO EN FÈVES ET BRISURES DE FÈVES,BRUTS *','N','18010000102',251);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'OXYDES DE FER *','N','28211000013',251);

--IDI MINCOMMERCE
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'FORMULAIRES D''IMPORTATION TEMPORAIRE OU DE CIRCULATION INTERNATIONALE,EXPEDIES AUX ASSOCIATIONS DE TOURISME ACCREDITES PAR LEURS ASSOCIATIONS CORRESPONDANTES OU LES DOUANES ETRANGERES*','N','49119900040',251);

--IDE MINCOMMERCE
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'MOBILIERS ET EFFETS PERSONNELS IMPORTÉS OU EXPORTÉS EN SUITE DE CHAMGEMENT DE RESIDENCE OU POUR RÉSIDENCE SECONDAIRE *','N','98020000007',251);


--BSBE
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'BOIS DE CONIFERES,EN ECLISSES,LAMES,RUBANS ET SIMILAIRES *','N','44041000012',333);

--LVTB
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'BOIS EN PLAQUETTES OU EN PARTICULES,AUTRES QUE DE CONIFERES *','N','44012200006',333);

--AEX_MINMIDT
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'Pulpe d Aloes','N','13021998014',121);

--MINADER-CCT
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'FARINE DE RIZ *','N','11023000002',5);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'AUTRE RIZ, EN GRAINS OU SOUS FORME DE FLOCONS OU AUTRES GRAINS TRAVAILLÉS (EXCEPTION DE LA FARINE,DU GRUAUX ET DE LA SEMOULE),AUTREMENT PRÉPARÉS,NON DENOMMÉS NI COMPRISES AILLEURS *','N','19049010906',5);


--MINADER-CC
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'MACHINES POUR LR NETTOYAGE OU LE TIRAGE DES OEUFS OU AUTRES PRODUITS AGRICOLES *','N','84336000097',217);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'TRACTEURS AGRICOLES ET TRACTEURS FORESTIERS(EXCLUSION DES MOTOCULTEURS),A ROUES,UNE PUISSANCE DE MOTEUR,EXCEDANT 37KW MAIS N''EXCEDANT PAS 59 KW ,NEUFS *','N','87019025008',217);


--MINADER-CQ
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'AUTRES MACHINES ET APPAREILS POUR AGRICULTURE,HORTICULTURE,LA SYLVICULTURE ET APICULTURE,Y COMPRIS LES GERMOIRS COMPORTANT DES DISPOSITIFS MÉCANIQUES OU THERMIQUES *','N','84368099093',211);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'SERRES AGRICOLES EN FONTE,FER OU ACIER*','N','73089099012',211);

--MINEPIA-CCT
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'TRACTEURS AGRICOLES ET TRACTEURS FORESTIERS (EXCLUSION DES MOTOCULTEURS),A ROUES,UNE PUISSANCE DE MOTEUR EXCEDANT 18 KW MAIS EXCEDANT PAS 37 KW, NEUFS *','N','87019020003',30);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'AUTRES APPAREILS PORTATIFS,A PROJETER,DISPERSER OU PULVERISER DES MATIÈRES LIQUIDES OU EN POUDRE,POUR AGRICULTURE OU HOTICULTURE *','N','84248130006',30);

--MINEPDED-CCT
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'MATELATS EN MATIÈRES PLASTIQUES ALVÉOLAIRE,RECOUVERTS OU NON *','N','94042190008',65);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'SILICONES SOUS FORMES PRIMAIRES OBTENUS PAR RECYCLAGE DES DECHETS,ROGNURES ET DEBRIS DES MATIERES PLASTIQUES *','N','39100000102',65);

--MINFOF-CCT
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'AUTRES BOIS CONTRE-PLAQUES CONSTITUES EXCLUSIVEMENT DE FEUILLES DE BOIS DONT CHACUNE A UNE EPAISSEUR EXCEDANT PAS 6MM*','N','44121900000',180);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'BOIS DE CONIFERES,SIMPLEMENT DEGROSSIS OU ARRONDIS,MAIS NON TOURNES NI COURBES NI AUTREMENT TRAVAILLES,POUR CANNES,PARAPLUIES,MANCHES OUTILS OU SIMILAIRES *','N','44041000023',180);

--MINMIDT-CCT
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'MONAZITE; URANOTHORIANITE ET AUTRES MINERAIS DE THORIUM, UNE TENEUR EN THORIUM SUPÉRIEURE A 20% EN POIDS *','N','26122010003',148);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'MOULES POUR LE MOULAGE PAR COMPESSION DES MATIERES MINERALES *','N','84806010001',148);

--MINSANTE-CCT
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'INSTRUMENTS ET APPAREILS POUR LA MESURE OU LA DETECTION DES RADIATIONS IONISANTES,DESTINÉS A DES AÉRONEFS CIVILS *','N','90301010005',113);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'AUTRES INSTRUMENTS ET APPAREILS POUR LA MESURE OU LA DÉTECTION DES RADIATIONS IONISANTES *','N','90301090007',113);

--MINADER-AH
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'NITRATES DE POTASSIUM A USAGES ENGRAIS *','N','28342100104',9);

--MINADER-DI
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'PEROXOCARBONATES (PERCARBONATES) DE POTASSIUM A USAGES ENGRAIS *','N','28369990015',19);

--MINADER-EH
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'NITRATES DE CALCIUM A USAGE ENGRAIS *','N','28342980106',9);

--AT-MINEPIA
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'RAIES, FRAIS OU RÉFRIGÉRÉS, EXCEPTION DES FILETS ET CHAIR DE POISSONS DU N° 03.04 ET A EXCLUSION DES FOIES,OEUFS ET LAITANCES *','N','03022990016',52);

--VT-MINEPIA
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'AUTRES LISTAOS OU BONITES A VENTRE RAYE,FRAIS OU RÉFRIGÉRÉS EXCEPTION DES FILETS ET CHAIR DE POISSONS DU N 03.04 ET EXCLUSION DES FOIES,OEUFS ET LAITANCES *','N','03023390001',40);

--AT-MINSANTE
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'OXYGENE *','N','28044000005',83);

--VTP-MINSANTE
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'CETONES-PHENOLS ET CETONES CONTENANT AUTRES FONCTIONS OXYGENEES *','N','29145000008',97);

--VTD-MINSANTE
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'PARTIES APPAREILS AZONOTHÉRAPIE, OXYGÉNOTHÉRAPIE, AÉROSOLTHÉRAPIE,APPAREILS RESPIRATOIRES DE RÉANIMATION ET AUTRES APPAREILS DE THÉRAPIE RESPIRATOIRE *','N','90192000093',183);

--VT-MINEPDED 
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'AUTRE GAZ NATUREL LIQUEFIÉS *','N','27111100908',68);

--MINADER-AE
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'NITRATES A USAGES ENGRAIS *','N','28342100105',9);

--MINCOMMERCE-CCT --> Provisoire
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'MATELATS EN MATIÈRES PLASTIQUES *','N','94042195555',283);
INSERT INTO SERVICES_ITEM( ID, CODE, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES ( SERVICES_ITEM_SEQ.nextVal, null, 0,'SILICONES SOUS FORMES PRIMAIRES *','N','39100005555',283);
INSERT INTO SERVICES_ITEM (ID, DELETED, LABEL, TYPE, NSH_ID, SERVICE_ID) VALUES (SERVICES_ITEM_SEQ.nextVal, '0', 'AUTRES RESISTANCES CHAUFFANTES,AUTRES QUE CELLES DU N� 85.45,MONTEES SUR UN SUPPORT EN MATIERE ISOLANTE *', 'N', '85168091003', '176');

COMMIT;



/*==============================================================*/
/* Table : HOLIDAY                                              */
/*==============================================================*/
INSERT INTO HOLIDAY(ID, HOLIDAY_DATE, LABEL, DELETED) VALUES (HOLIDAY_SEQ.nextVal, to_date('2015-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Nouvel an', 0);
INSERT INTO HOLIDAY(ID, HOLIDAY_DATE, LABEL, DELETED) VALUES (HOLIDAY_SEQ.nextVal, to_date('2015-01-14 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Fête de la Révolution et de la Jeunesse', 0);
INSERT INTO HOLIDAY(ID, HOLIDAY_DATE, LABEL, DELETED) VALUES (HOLIDAY_SEQ.nextVal, to_date('2015-03-20 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Fête de l Indépendance', 0);
INSERT INTO HOLIDAY(ID, HOLIDAY_DATE, LABEL, DELETED) VALUES (HOLIDAY_SEQ.nextVal, to_date('2015-04-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Journée des Martyrs', 0);
INSERT INTO HOLIDAY(ID, HOLIDAY_DATE, LABEL, DELETED) VALUES (HOLIDAY_SEQ.nextVal, to_date('2015-05-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Fête du Travail', 0);
INSERT INTO HOLIDAY(ID, HOLIDAY_DATE, LABEL, DELETED) VALUES (HOLIDAY_SEQ.nextVal, to_date('2015-07-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Fête de la République', 0);
INSERT INTO HOLIDAY(ID, HOLIDAY_DATE, LABEL, DELETED) VALUES (HOLIDAY_SEQ.nextVal, to_date('2015-08-13 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Fête de la Femme et de la Famille', 0);
INSERT INTO HOLIDAY(ID, HOLIDAY_DATE, LABEL, DELETED) VALUES (HOLIDAY_SEQ.nextVal, to_date('2015-10-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Fête de l Évacuation', 0);
COMMIT;

/*==============================================================*/
/* Table : ANALYSE_TYPE                                         */
/*==============================================================*/
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse DRCQIPA', 'Analyse Type DRCQIPA', 24, 2, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse D-CCT-Minader', 'Analyse Type D-CCT-Minader', 24, 3, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse D-CCT-Minepia', 'Analyse Type D-CCT-Minepia', 24, 28, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse DSV', 'Analyse Type DSV', 24, 31, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse DPAIH', 'Analyse Type DPAIH', 24, 32, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse DDPIA', 'Analyse Type DDPIA', 24, 33, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse DHMPE', 'Analyse Type DHMPE', 24, 66, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse D-CCT-Minader', 'Analyse Type D-CCT-Minader', 24, 3, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse D-CCT-Minepia', 'Analyse Type D-CCT-Minepia', 24, 28, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse D-CCT-Minepded', 'Analyse Type D-CCT-Minepded', 24, 63, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse D-CQ-Minader1', 'Analyse Type D-CQ-Minader1', 24, 209, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse D-CC-Minader2', 'Analyse Type D-CC-Minader1', 24, 209, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse D-CQ-Minader1', 'Analyse Type D-CQ-Minader1', 24, 215, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse D-CQ-Minader2', 'Analyse Type D-CC-Minader2', 24, 215, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse D-CCT1-Minepia', 'Analyse Type D-CCT1-Minepia', 24, 28, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse D-CCT2-Minepia', 'Analyse Type D-CCT2-Minepia', 24, 28, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse D-CQ1-Minepia', 'Analyse Type D-CQ1-Minepia', 24, 28, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse D-CQ2-Minepia', 'Analyse Type D-CQ2-Minepia', 24, 28, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse D-CC1-Minepia', 'Analyse Type D-CC1-Minepia', 24, 28, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse D-CC2-Minepia', 'Analyse Type D-CC2-Minepia', 24, 28, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse D-CCT3-Minepia', 'Analyse Type D-CCT3-Minepia', 24, 28, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse D-CCT4-Minepia', 'Analyse Type D-CCT4-Minepia', 24, 28, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse D-CCT5-Minepia', 'Analyse Type D-CCT5-Minepia', 24, 28, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse D-CCT-Minsante', 'Analyse Type D-CCT-Minsante', 24, 76, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse D-CCT-Minmidt', 'Analyse Type D-CCT-Minmidt', 24, 116, 0);
INSERT INTO ANALYSE_TYPE (ID, LABEL_FR, LABEL_EN, DURATION, ORGANISM_ID, DELETED) VALUES (ANALYSE_TYPE_SEQ.nextVal, 'Type Analyse D-CCT-Minfof', 'Analyse Type D-CCT-Minfof', 24, 151, 0);

COMMIT;

/*==============================================================*/
/* Table : TREATMENT_TYPE                                       */
/*==============================================================*/
INSERT INTO TREATMENT_TYPE (ID,DELETED,DURATION,LABEL_EN,LABEL_FR,ORGANISM_ID) VALUES (TREATMENT_TYPE_SEQ.nextVal,0,24,'Treatment Type DRCQIPA','Type Traitement DRCQIPA', 2);
INSERT INTO TREATMENT_TYPE (ID,DELETED,DURATION,LABEL_EN,LABEL_FR,ORGANISM_ID) VALUES (TREATMENT_TYPE_SEQ.nextVal,0,24,'Treatment Type D-CCT-Minader','Type Traitement D-CCT-Minader', 3);
INSERT INTO TREATMENT_TYPE (ID,DELETED,DURATION,LABEL_EN,LABEL_FR,ORGANISM_ID) VALUES (TREATMENT_TYPE_SEQ.nextVal,0,24,'Treatment Type D-CCT-Minepia','Type Traitement D-CCT-Minepia', 28);
INSERT INTO TREATMENT_TYPE (ID,DELETED,DURATION,LABEL_EN,LABEL_FR,ORGANISM_ID) VALUES (TREATMENT_TYPE_SEQ.nextVal,0,24,'Treatment Type DSV','Type Traitement DSV', 31);
INSERT INTO TREATMENT_TYPE (ID,DELETED,DURATION,LABEL_EN,LABEL_FR,ORGANISM_ID) VALUES (TREATMENT_TYPE_SEQ.nextVal,0,24,'Treatment Type DPAIH','Type Traitement DPAIH', 32);
INSERT INTO TREATMENT_TYPE (ID,DELETED,DURATION,LABEL_EN,LABEL_FR,ORGANISM_ID) VALUES (TREATMENT_TYPE_SEQ.nextVal,0,24,'Treatment Type DDPIA','Type Traitement DDPIA', 33);
INSERT INTO TREATMENT_TYPE (ID,DELETED,DURATION,LABEL_EN,LABEL_FR,ORGANISM_ID) VALUES (TREATMENT_TYPE_SEQ.nextVal,0,24,'Treatment Type DHMPE','Type Traitement DHMPE', 66);
INSERT INTO TREATMENT_TYPE (ID,DELETED,DURATION,LABEL_EN,LABEL_FR,ORGANISM_ID) VALUES (TREATMENT_TYPE_SEQ.nextVal,0,24,'Treatment Type D-CCT-Minader','Type Traitement D-CCT-Minader', 3);
INSERT INTO TREATMENT_TYPE (ID,DELETED,DURATION,LABEL_EN,LABEL_FR,ORGANISM_ID) VALUES (TREATMENT_TYPE_SEQ.nextVal,0,24,'Treatment Type D-CCT-Minepia','Type Traitement D-CCT-Minepia', 28);
INSERT INTO TREATMENT_TYPE (ID,DELETED,DURATION,LABEL_EN,LABEL_FR,ORGANISM_ID) VALUES (TREATMENT_TYPE_SEQ.nextVal,0,24,'Treatment Type D-CCT-Minsante','Type Traitement D-CCT-Minsante', 111);
INSERT INTO TREATMENT_TYPE (ID,DELETED,DURATION,LABEL_EN,LABEL_FR,ORGANISM_ID) VALUES (TREATMENT_TYPE_SEQ.nextVal,0,24,'Treatment Type D-CCT-Minmidt','Type Traitement D-CCT-Minmidt', 146);
INSERT INTO TREATMENT_TYPE (ID,DELETED,DURATION,LABEL_EN,LABEL_FR,ORGANISM_ID) VALUES (TREATMENT_TYPE_SEQ.nextVal,0,24,'Treatment Type D-CCT-Minfof','Type Traitement D-CCT-Minfof', 178);
INSERT INTO TREATMENT_TYPE (ID,DELETED,DURATION,LABEL_EN,LABEL_FR,ORGANISM_ID) VALUES (TREATMENT_TYPE_SEQ.nextVal,0,24,'Treatment Type D-CCT-Minepded','Type Traitement D-CCT-Minepded', 63);
INSERT INTO TREATMENT_TYPE (ID,DELETED,DURATION,LABEL_EN,LABEL_FR,ORGANISM_ID) VALUES (TREATMENT_TYPE_SEQ.nextVal,0,24,'Treatment Type D-CQ-Minader1','Type Traitement D-CQ-Minader1', 209);
INSERT INTO TREATMENT_TYPE (ID,DELETED,DURATION,LABEL_EN,LABEL_FR,ORGANISM_ID) VALUES (TREATMENT_TYPE_SEQ.nextVal,0,24,'Treatment Type D-CQ-Minader2','Type Traitement D-CQ-Minader2', 209);
INSERT INTO TREATMENT_TYPE (ID,DELETED,DURATION,LABEL_EN,LABEL_FR,ORGANISM_ID) VALUES (TREATMENT_TYPE_SEQ.nextVal,0,24,'Treatment Type D-CCT1-Minepia','Type Traitement D-CCT1-Minepia', 28);
INSERT INTO TREATMENT_TYPE (ID,DELETED,DURATION,LABEL_EN,LABEL_FR,ORGANISM_ID) VALUES (TREATMENT_TYPE_SEQ.nextVal,0,24,'Treatment Type D-CCT2-Minepia','Type Traitement D-CCT2-Minepia', 28);
INSERT INTO TREATMENT_TYPE (ID,DELETED,DURATION,LABEL_EN,LABEL_FR,ORGANISM_ID) VALUES (TREATMENT_TYPE_SEQ.nextVal,0,24,'Treatment Type D-CQ1-Minader1','Type Traitement D-CQ1-Minader1', 215);
INSERT INTO TREATMENT_TYPE (ID,DELETED,DURATION,LABEL_EN,LABEL_FR,ORGANISM_ID) VALUES (TREATMENT_TYPE_SEQ.nextVal,0,24,'Treatment Type D-CQ2-Minader2','Type Traitement D-CQ1-Minader2', 215);
INSERT INTO TREATMENT_TYPE (ID,DELETED,DURATION,LABEL_EN,LABEL_FR,ORGANISM_ID) VALUES (TREATMENT_TYPE_SEQ.nextVal,0,24,'Treatment Type D-CCT3-Minepia','Type Traitement D-CCT3-Minepia', 28);
INSERT INTO TREATMENT_TYPE (ID,DELETED,DURATION,LABEL_EN,LABEL_FR,ORGANISM_ID) VALUES (TREATMENT_TYPE_SEQ.nextVal,0,24,'Treatment Type D-CCT4-Minepia','Type Traitement D-CCT4-Minepia', 28);
INSERT INTO TREATMENT_TYPE (ID,DELETED,DURATION,LABEL_EN,LABEL_FR,ORGANISM_ID) VALUES (TREATMENT_TYPE_SEQ.nextVal,0,24,'Treatment Type D-CCT5-Minepia','Type Traitement D-CCT5-Minepia', 28);
INSERT INTO TREATMENT_TYPE (ID,DELETED,DURATION,LABEL_EN,LABEL_FR,ORGANISM_ID) VALUES (TREATMENT_TYPE_SEQ.nextVal,0,24,'Treatment Type D-CCT6-Minepia','Type Traitement D-CCT6-Minepia', 28);


COMMIT;

/*==============================================================*/
/* Table : HOURLY_TYPE                                          */
/*==============================================================*/
INSERT INTO HOURLY_TYPE (ID,LABEL_EN,LABEL_FR) VALUES (HOURLY_TYPE_SEQ.nextVal,'Administratif','Administrative');
INSERT INTO HOURLY_TYPE (ID,LABEL_EN,LABEL_FR) VALUES (HOURLY_TYPE_SEQ.nextVal,'Summer','Eté');
INSERT INTO HOURLY_TYPE (ID,LABEL_EN,LABEL_FR) VALUES (HOURLY_TYPE_SEQ.nextVal,'Ramadan','Ramadan');
COMMIT;

/*==============================================================*/
/* Table : WORK_YEAR_CONFIG                                     */
/*==============================================================*/
INSERT INTO WORK_YEAR_CONFIG (ID, BEGIN_DATE, END_DATE, HOURLY_TYPE_ID) VALUES (WORK_YEAR_CONFIG_SEQ.nextVal, to_date('2015-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2015-05-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO WORK_YEAR_CONFIG (ID, BEGIN_DATE, END_DATE, HOURLY_TYPE_ID) VALUES (WORK_YEAR_CONFIG_SEQ.nextVal, to_date('2015-06-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2015-06-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 2);
INSERT INTO WORK_YEAR_CONFIG (ID, BEGIN_DATE, END_DATE, HOURLY_TYPE_ID) VALUES (WORK_YEAR_CONFIG_SEQ.nextVal, to_date('2015-06-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2015-07-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 3);
INSERT INTO WORK_YEAR_CONFIG (ID, BEGIN_DATE, END_DATE, HOURLY_TYPE_ID) VALUES (WORK_YEAR_CONFIG_SEQ.nextVal, to_date('2015-07-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2015-08-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 2);
INSERT INTO WORK_YEAR_CONFIG (ID, BEGIN_DATE, END_DATE, HOURLY_TYPE_ID) VALUES (WORK_YEAR_CONFIG_SEQ.nextVal, to_date('2015-09-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2015-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO WORK_YEAR_CONFIG (ID, BEGIN_DATE, END_DATE, HOURLY_TYPE_ID) VALUES (WORK_YEAR_CONFIG_SEQ.nextVal, to_date('2016-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2016-05-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
INSERT INTO WORK_YEAR_CONFIG (ID, BEGIN_DATE, END_DATE, HOURLY_TYPE_ID) VALUES (WORK_YEAR_CONFIG_SEQ.nextVal, to_date('2016-06-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2016-06-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 2);
INSERT INTO WORK_YEAR_CONFIG (ID, BEGIN_DATE, END_DATE, HOURLY_TYPE_ID) VALUES (WORK_YEAR_CONFIG_SEQ.nextVal, to_date('2016-06-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2016-07-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 3);
INSERT INTO WORK_YEAR_CONFIG (ID, BEGIN_DATE, END_DATE, HOURLY_TYPE_ID) VALUES (WORK_YEAR_CONFIG_SEQ.nextVal, to_date('2016-07-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2016-08-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 2);
INSERT INTO WORK_YEAR_CONFIG (ID, BEGIN_DATE, END_DATE, HOURLY_TYPE_ID) VALUES (WORK_YEAR_CONFIG_SEQ.nextVal, to_date('2016-09-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2016-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1);
COMMIT;

/*==============================================================*/
/* Table : INSPECTION_WORK_WEEK_CONFIG                          */
/*==============================================================*/
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 1, 2);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 1, 3);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 1, 209);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 1, 215);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 1, 28);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 1, 31);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 1, 32);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 1, 33);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 1, 63);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 2, 66);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 2, 2);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 2, 3);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 2, 209);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 2, 215);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 2, 28);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 2, 31);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 2, 32);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 2, 33);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 2, 63);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 3, 66);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 3, 2);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 3, 3);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 3, 209);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 3, 215);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 3, 28);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 3, 31);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 3, 32);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 3, 33);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 3, 63);
INSERT INTO INSPECTION_WORK_WEEK_CONFIG (ID,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,HOURLY_TYPE_ID,ORGANISM_ID) VALUES (IWWC_SEQ.nextVal, 1, 1, 1, 1, 1, 0, 0, 3, 66);
COMMIT;

/*==============================================================*/
/* Table : INSPECTION_WORK_DAY_CONFIG                           */
/*==============================================================*/
INSERT INTO INSPECTION_WORK_DAY_CONFIG (ID, HOUR, HOURLY_TYPE_ID, ORGANISM_ID) VALUES (IWDC_SEQ.nextVal, 8, 1, 2);
INSERT INTO INSPECTION_WORK_DAY_CONFIG (ID, HOUR, HOURLY_TYPE_ID, ORGANISM_ID) VALUES (IWDC_SEQ.nextVal, 12, 1, 2);
INSERT INTO INSPECTION_WORK_DAY_CONFIG (ID, HOUR, HOURLY_TYPE_ID, ORGANISM_ID) VALUES (IWDC_SEQ.nextVal, 16, 1, 3);
INSERT INTO INSPECTION_WORK_DAY_CONFIG (ID, HOUR, HOURLY_TYPE_ID, ORGANISM_ID) VALUES (IWDC_SEQ.nextVal, 8, 2, 3);
INSERT INTO INSPECTION_WORK_DAY_CONFIG (ID, HOUR, HOURLY_TYPE_ID, ORGANISM_ID) VALUES (IWDC_SEQ.nextVal, 14, 2, 28);
INSERT INTO INSPECTION_WORK_DAY_CONFIG (ID, HOUR, HOURLY_TYPE_ID, ORGANISM_ID) VALUES (IWDC_SEQ.nextVal, 10, 3, 28);
INSERT INTO INSPECTION_WORK_DAY_CONFIG (ID, HOUR, HOURLY_TYPE_ID, ORGANISM_ID) VALUES (IWDC_SEQ.nextVal, 16, 1, 209);
INSERT INTO INSPECTION_WORK_DAY_CONFIG (ID, HOUR, HOURLY_TYPE_ID, ORGANISM_ID) VALUES (IWDC_SEQ.nextVal, 8, 2, 209);
INSERT INTO INSPECTION_WORK_DAY_CONFIG (ID, HOUR, HOURLY_TYPE_ID, ORGANISM_ID) VALUES (IWDC_SEQ.nextVal, 16, 1, 215);
INSERT INTO INSPECTION_WORK_DAY_CONFIG (ID, HOUR, HOURLY_TYPE_ID, ORGANISM_ID) VALUES (IWDC_SEQ.nextVal, 8, 2, 215);
COMMIT;




