
/*==============================================================*/
/* Table : LABORATORY_ANALYSE_TYPE                              */
/*==============================================================*/
INSERT INTO LABORATORY_ANALYSE_TYPE (LABORATORY_ID,ANALYSE_TYPE_ID) VALUES (193,8);
INSERT INTO LABORATORY_ANALYSE_TYPE (LABORATORY_ID,ANALYSE_TYPE_ID) VALUES (195,9);
INSERT INTO LABORATORY_ANALYSE_TYPE (LABORATORY_ID,ANALYSE_TYPE_ID) VALUES (195,15);
INSERT INTO LABORATORY_ANALYSE_TYPE (LABORATORY_ID,ANALYSE_TYPE_ID) VALUES (195,16);
INSERT INTO LABORATORY_ANALYSE_TYPE (LABORATORY_ID,ANALYSE_TYPE_ID) VALUES (195,17);
INSERT INTO LABORATORY_ANALYSE_TYPE (LABORATORY_ID,ANALYSE_TYPE_ID) VALUES (205,18);
INSERT INTO LABORATORY_ANALYSE_TYPE (LABORATORY_ID,ANALYSE_TYPE_ID) VALUES (205,19);
INSERT INTO LABORATORY_ANALYSE_TYPE (LABORATORY_ID,ANALYSE_TYPE_ID) VALUES (205,20);
INSERT INTO LABORATORY_ANALYSE_TYPE (LABORATORY_ID,ANALYSE_TYPE_ID) VALUES (205,16);
INSERT INTO LABORATORY_ANALYSE_TYPE (LABORATORY_ID,ANALYSE_TYPE_ID) VALUES (207,17);
INSERT INTO LABORATORY_ANALYSE_TYPE (LABORATORY_ID,ANALYSE_TYPE_ID) VALUES (207,21);
INSERT INTO LABORATORY_ANALYSE_TYPE (LABORATORY_ID,ANALYSE_TYPE_ID) VALUES (207,22);
INSERT INTO LABORATORY_ANALYSE_TYPE (LABORATORY_ID,ANALYSE_TYPE_ID) VALUES (207,23);
INSERT INTO LABORATORY_ANALYSE_TYPE (LABORATORY_ID,ANALYSE_TYPE_ID) VALUES (195,23);
INSERT INTO LABORATORY_ANALYSE_TYPE (LABORATORY_ID,ANALYSE_TYPE_ID) VALUES (205,22);
INSERT INTO LABORATORY_ANALYSE_TYPE (LABORATORY_ID,ANALYSE_TYPE_ID) VALUES (207,9);

-- MINSTANTE
INSERT INTO LABORATORY_ANALYSE_TYPE (LABORATORY_ID,ANALYSE_TYPE_ID) VALUES (197,9);
INSERT INTO LABORATORY_ANALYSE_TYPE (LABORATORY_ID,ANALYSE_TYPE_ID) VALUES (201,9);



COMMIT;

/*==============================================================*/
/* Table : TREATMENT_COMPANY_TYPE                               */
/*==============================================================*/
INSERT INTO TREATMENT_COMPANY_TYPE (TREATMENT_COMPANY_ID,TREATMENT_TYPE_ID) VALUES (194,8);
INSERT INTO TREATMENT_COMPANY_TYPE (TREATMENT_COMPANY_ID,TREATMENT_TYPE_ID) VALUES (196,16);
INSERT INTO TREATMENT_COMPANY_TYPE (TREATMENT_COMPANY_ID,TREATMENT_TYPE_ID) VALUES (206,16);
INSERT INTO TREATMENT_COMPANY_TYPE (TREATMENT_COMPANY_ID,TREATMENT_TYPE_ID) VALUES (208,17);
INSERT INTO TREATMENT_COMPANY_TYPE (TREATMENT_COMPANY_ID,TREATMENT_TYPE_ID) VALUES (196,17);
INSERT INTO TREATMENT_COMPANY_TYPE (TREATMENT_COMPANY_ID,TREATMENT_TYPE_ID) VALUES (206,20);
INSERT INTO TREATMENT_COMPANY_TYPE (TREATMENT_COMPANY_ID,TREATMENT_TYPE_ID) VALUES (208,20);
INSERT INTO TREATMENT_COMPANY_TYPE (TREATMENT_COMPANY_ID,TREATMENT_TYPE_ID) VALUES (196,21);
INSERT INTO TREATMENT_COMPANY_TYPE (TREATMENT_COMPANY_ID,TREATMENT_TYPE_ID) VALUES (206,21);
INSERT INTO TREATMENT_COMPANY_TYPE (TREATMENT_COMPANY_ID,TREATMENT_TYPE_ID) VALUES (208,22);
INSERT INTO TREATMENT_COMPANY_TYPE (TREATMENT_COMPANY_ID,TREATMENT_TYPE_ID) VALUES (208,22);
INSERT INTO TREATMENT_COMPANY_TYPE (TREATMENT_COMPANY_ID,TREATMENT_TYPE_ID) VALUES (208,23);
INSERT INTO TREATMENT_COMPANY_TYPE (TREATMENT_COMPANY_ID,TREATMENT_TYPE_ID) VALUES (206,23);

COMMIT;

 
/*==============================================================*/
/* Table : CAR                                                  */
/*==============================================================*/
INSERT INTO CAR (ID, DELETED, ENABLED, MODEL, SERIAL_NUMBER, ORGANISM_ID) VALUES (CAR_SEQ.nextVal, 0, 1, 'mazda', '100 TU 70', 2);
INSERT INTO CAR (ID, DELETED, ENABLED, MODEL, SERIAL_NUMBER, ORGANISM_ID) VALUES (CAR_SEQ.nextVal, 0, 1, 'mercedes', '150 TU 60', 3);
INSERT INTO CAR (ID, DELETED, ENABLED, MODEL, SERIAL_NUMBER, ORGANISM_ID) VALUES (CAR_SEQ.nextVal, 0, 1, 'M5', '122 TU 99', 3);
INSERT INTO CAR (ID, DELETED, ENABLED, MODEL, SERIAL_NUMBER, ORGANISM_ID) VALUES (CAR_SEQ.nextVal, 0, 1, 'Citroen', '144 TU 789', 28);
INSERT INTO CAR (ID, DELETED, ENABLED, MODEL, SERIAL_NUMBER, ORGANISM_ID) VALUES (CAR_SEQ.nextVal, 0, 1, 'peugeot', '89 TU 34', 28);
INSERT INTO CAR (ID, DELETED, ENABLED, MODEL, SERIAL_NUMBER, ORGANISM_ID) VALUES (CAR_SEQ.nextVal, 0, 1, 'Citroen', '132 TU 8629', 209);
INSERT INTO CAR (ID, DELETED, ENABLED, MODEL, SERIAL_NUMBER, ORGANISM_ID) VALUES (CAR_SEQ.nextVal, 0, 1, 'Toyota', '100 TU 533', 215);


INSERT INTO CAR (ID, DELETED, ENABLED, MODEL, SERIAL_NUMBER, ORGANISM_ID) VALUES (CAR_SEQ.nextVal, 0, 1, 'Toyota', '100 TU 353', 178);
INSERT INTO CAR (ID, DELETED, ENABLED, MODEL, SERIAL_NUMBER, ORGANISM_ID) VALUES (CAR_SEQ.nextVal, 0, 1, 'Toyota', '100 TU 339', 111);
INSERT INTO CAR (ID, DELETED, ENABLED, MODEL, SERIAL_NUMBER, ORGANISM_ID) VALUES (CAR_SEQ.nextVal, 0, 1, 'Toyota', '100 TU 33', 146);


COMMIT;



