
/*==============================================================*/
/* TABLE : FILE_TYPE_SERVICE                                    */
/*==============================================================*/
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (1, 24, 251);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (2, 25, 251);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (3, 26, 251);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (4, 27, 251);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (5, 35, 251);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (6,32,9);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (7,5,19);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (8,4,11);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (9,3,9);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (10,2,9);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (11,1,9);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (12,15,40);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (13,14,52);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (14,17,70);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (15,16,68);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (16,10,99);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (17,9,183);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (18,8,97);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (19,7,83);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (20,13,190);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (21,12,121);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (22,11,127);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (23,18,159);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (24,31,333);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (25,30,333);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (26,34,176);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (27,28,333);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (28,22,247);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (29,06,19);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (30,33,5);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (31,21,211);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (32,20,217);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (33,19,5);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (34,19,30);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (35,19,65);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (36,19,113);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (37,19,148);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (38,19,180);
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (39,23,NULL);
COMMIT;
