/*===================================================================*/
/* IRMP_MINCOOMERCE                                                 */
/*==================================================================*/

-- FILE_TYPE
INSERT INTO FILE_TYPE (ID, CODE, LABEL_EN, LABEL_FR) VALUES (36, 'IRMP_MINCOMMERCE', 'Subscription to the weight and measure registry', 'Inscription au régistre de poids et mesures');
COMMIT;
-- MINISTRY_FILE_TYPE
INSERT INTO MINISTRY_FILE_TYPE (MINISTRY_ID, FILE_TYPE_ID) VALUES (221, 36);

-- FILE_TYPE_AUTHORITY (IRMP_MINCOOMERCE) --> 5 Cotations
-- 4  -> Superviseur
-- 12 -> Agent de recevabilité
-- 17 -> Signataire
-- 18 -> Responsable de traitement
-- 6  -> Agent de cotation 1
-- 7  -> Agent de cotation 2
-- 8  -> Agent de cotation 3
-- 9  -> Agent de cotation 4
-- 10 -> Agente de cotation 5
INSERT INTO FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES (36, 4);
INSERT INTO FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES (36, 12);
INSERT INTO FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES (36, 17);
INSERT INTO FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES (36, 18);
INSERT INTO FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES (36, 6);
INSERT INTO FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES (36, 7);
INSERT INTO FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES (36, 8);
INSERT INTO FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES (36, 9);
INSERT INTO FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES (36, 10);
COMMIT;

-- FILE_TYPE_FLOW
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Request for subscription to the weight and measure registry','Demande d''inscription au registre des poids et mesures','36','100');
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Additional information for the subscription to the weight and measure registry','Complément d''information inscription au registre de poids et mesures','36','101');
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Rejection for the subscription to the weight and measure registry','Rejet inscription au registre de poids et mesures','36','102');
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Validation for the subscription to the weight and measure registry','Validation inscription au registre de poids et mesures','36','103');
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Rejection for the subscription to the weight and measure registry','Rejet inscription au registre de poids et mesures','36','114');
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Acceptation for the subscription to the weight and measure registry','Acceptation inscription au registre de poids et mesures','36','117');
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Visa authorization for the subscription to the weight and measure registry','Autorisation du visa inscription au registre de poids et mesures','36','122');
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Visa to the assistant director','Visa au sous directeur','36','124');
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Visa to the director','Visa au directeur','36','125');
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Visa to the general secretary','Visa au secretaire general','36','126');
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Visa for signature','Visa pour signature','36','127');
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Additional information for the subscription to the weight and measure registry','Complément d''information inscription au registre de poids et mesures','36','132');
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Desicion refusal - Back to treatment of the subscription to the weight and measure registry','Refus décision - Retour vers étude inscription au registre des poids et mesures','36','136');
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Desicion refusal - Back to treatment of the subscription to the weight and measure registry','Refus décision - Retour vers étude inscription au registre des poids et mesures','36','138');
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Desicion refusal - Back to treatment of the subscription to the weight and measure registry','Refus décision - Retour vers étude inscription au registre des poids et mesures','36','141');
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Desicion refusal - Back to treatment of the subscription to the weight and measure registry','Refus décision - Retour vers étude inscription au registre des poids et mesures','36','145');
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Desicion refusal - Back to treatment of the subscription to the weight and measure registry','Refus décision - Retour vers étude inscription au registre des poids et mesures','36','150');
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Removing the certificate of approval model','Retrait attestation d''approbation de modeles','36','155');
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Answer to the additionnal information request for the subscription to the weight and measure registry after depth study','Réponse au complément d''information d''inscription au régistre de poids et mesures suite etude approfondie','36','160');
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Cancel request for the subscription to the weight and measure registry','Demande d''annulation de l''inscription au registre des poids et mesures','36','162');
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Cancellation for the subscription to the weight and measure registry','Annulation de l''inscription au registre des poids et mesures','36','165');
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Rejection cancellation for the subscription to the weight and measure registry','Rejet annulation de l''inscription au registre des poids et mesures','36','166');
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Cancellation confirmation for the subscription to the weight and measure registry','Confirmation annulation de l''inscription au registre des poids et mesures','36','167');
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Answer to the additionnal information request for the subscription to the weight and measure registry after depth study','Réponse au complément d''information d''inscription au régistre de poids et mesures suite etude approfondie','36','169');
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Refusal to sign the cancellation','Refus de signature de l''annulation','36','168');

COMMIT;

-- FILE_TYPE_FLOW_REPORT
INSERT INTO FILE_TYPE_FLOW_REPORT(ID, REPORT_CLASS_NAME, REPORT_NAME, FILE_FIELD_NAME, FILE_TYPE_ID, FLOW_ID, ORGANISM_ID) VALUES (36, 'org.guce.siat.web.reports.exporter.IrmpExporter', 'IRMP.pdf','NUMERO_AAM_MINCOMMERCE', 36, 122, 222);

-- FILE_TYPE_STEP
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES (36, 100, 0, 'Folder filing for a subscription to the weight and measure registry', 'Dépôt de dossier d''inscription au registre des poids et mesures');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES (36, 101, 0, 'Reject a subscription to the weight and measure registry', 'Rejet de dossier d''inscription au grégistre des poids et mesures');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES (36, 102, 0, 'Validation of the subscription to the weight and measure registry', 'Validation de l''inscription au régistre des poids et mesures');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES (36, 103, 0, 'Removing the certificate of approval model', 'Retrait de l''Attestation d''approbation de modèle');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES (36, 104, 0, 'Admissibility of a subscription to the weight and measure registry', 'Recevabilité de l''inscrition au régistre des poids et mesures');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES (36, 105, 0, 'Quotation step', 'Etape de cotation');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES (36, 106, 0, 'Quotation step', 'Etape de cotation');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES (36, 107, 0, 'Quotation step', 'Etape de cotation');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES (36, 108, 0, 'Quotation step', 'Etape de cotation');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES (36, 109, 0, 'Quotation step', 'Etape de cotation');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES (36, 111, 1, 'Depth study of the file step', 'Etape d''étude approfondie du dossier');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES (36, 112, 0, 'Signature of the certificate of approval model', 'Signature de l''attestation d''approbation de modèle');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES (36, 113, 0, 'Visa step', 'Etape de Visa');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES (36, 114, 0, 'Visa step', 'Etape de Visa');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES (36, 115, 0, 'Visa step', 'Etape de Visa');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES (36, 116, 0, 'Visa step', 'Etape de Visa');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES (36, 118, 0, 'Visa step', 'Etape de Visa');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES (36, 119, 0, 'Stage of the cancellation request study', 'Etape d''étude de la demande d''annulation');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES (36, 120, 0, 'End cancellation step', 'Etape de fin d''annulation');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES (36, 121, 0, 'Signature following a cancellation request step', 'Etape de signature suite une demande d''annulation');
COMMIT;

-- REPORT_ORGANISM
INSERT INTO REPORT_ORGANISM( ID,  SEQUENCE,  VALUE, FILE_TYPE_FLOW_REPORT,  ORGANISM)VALUES( REPORT_ORGANISME_SEQ.nextVal,  0,  '/2017/AAM/MINCOMMERCE',  36,  222);

-- FLOW_GUCE_SIAT
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (1681,'IPM01','FL_AP_85',36);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (1682,'IPM02','FL_AP_86',36);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (1683,'IPM02','FL_AP_113',36);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (1684,'IPM02','FL_AP_114',36);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (1685,'IPM02','FL_AP_115',36);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (1686,'IPM02','FL_AP_116',36);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (1687,'IPM02','FL_AP_117',36);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (1688,'IPM02','FL_AP_118',36);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (1689,'IPM03','FL_AP_87',36);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (1690,'IPM03','FL_AP_95',36);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (1691,'IPM03','FL_AP_96',36);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (1692,'IPM03','FL_AP_97',36);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (1693,'IPM03','FL_AP_98',36);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (1694,'IPM03','FL_AP_99',36);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (1695,'IPM03','FL_AP_100',36);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (1696,'IPM04','FL_AP_107',36);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (1697,'IPM11',NULL,36);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (1698,'IPMA1','FL_AP_147',36);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (1699,'AP_RETRAIT_100','FL_AP_140',36);
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (1700,'IPMA2','FL_AP_152',36);

COMMIT;


-- FILE_FIELD

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6676,36,'CODE_BUREAU','Code Bureau','Office Code',0,1,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6677,36,'TYPE_DEMANDE','Type de Demande','Request Type',0,1,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6678,36,'SIGNATAIRE_NOM','Nom du Signataire','Signatory Name',0,9,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6679,36,'SIGNATAIRE_QUALITE','Qualité du Signataire','Signatory Position',0,9,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6680,36,'SIGNATAIRE_LIEU','Lieu de Signature','Place of Signature',0,9,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6681,36,'SIGNATAIRE_DATE','Date de Signature','Date of  Signature',0,9,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6682,36,'FOURNISSEUR_RAISONSOCIALE','Raison Sociale','Name/Business Name',0,10,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6683,36,'FOURNISSEUR_Sigle','Sigle','Acronym',0,10,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6684,36,'FOURNISSEUR_ADRESSE_ADRESSE1','Adresse (Adresse 1)','Address (Address 1)',0,10,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6685,36,'FOURNISSEUR_ADRESSE_ADRESSE2','Adresse (Adresse 2)','Address (Address 2)',0,10,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6686,36,'FOURNISSEUR_ADRESSE_BP','Adresse (BP)','Address (P.O. Box)',0,10,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6687,36,'FOURNISSEUR_ADRESSE_PAYSADDRESS_CODEPAYS','Adresse Pays (Code Pays)','Address Country (Country Code)',0,10,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6688,36,'FOURNISSEUR_ADRESSE_PAYSADDRESS_NOMPAYS','Adresse Pays (Nom Pays)','Address Country (Country Name)',0,10,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6689,36,'FOURNISSEUR_ADRESSE_VILLE','Adresse (Ville)','Address (City)',0,10,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6690,36,'FOURNISSEUR_ADRESSE_ADRESSEELECTRONIQUE','Adresse (Adresse Électronique)','Address (e-mail Address)',0,10,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6691,36,'FOURNISSEUR_ADRESSE_SITEWEB','Adresse (Site Web)','Address (Web Site)',0,10,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6692,36,'FOURNISSEUR_TELEPHONE_FIXE_INDICATIFPAYS','Téléphone Fixe (Indicatif Pays)','Telephone (Country Dialing Code)',0,10,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6693,36,'FOURNISSEUR_TELEPHONE_FIXE_NUMERO','Téléphone Fixe (Numéro)','Telephone (Number)',0,10,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6694,36,'FOURNISSEUR_TELEPHONE_MOBILE_INDICATIFPAYS','Téléphone Mobile (Indicatif Pays)','Mobile Phone (Country Dialing Code)',0,10,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6695,36,'FOURNISSEUR_TELEPHONE_MOBILE_NUMERO','Téléphone Mobile (Numéro)','Mobile Phone (Number)',0,10,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6696,36,'FOURNISSEUR_FAX_INDICATIFPAYS','Fax (Indicatif Pays)','Fax (Country Dialing Code)',0,10,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6697,36,'FOURNISSEUR_FAX_NUMERO','Fax (Numéro)','Fax (Number)',0,10,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6698,36,'INFORMATIONS_GENERALES_INSCRIPTION_FICHIER_NUMERO','Inscription au fichier(Numero)','Inscription au fichier(Numero)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6699,36,'INFORMATIONS_GENERALES_INSCRIPTION_FICHIER_DATE','Inscription au fichier(Date)','Inscription au fichier(Date)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6700,36,'INFORMATIONS_GENERALES_INSCRIPTION_FICHIER_VALIDITE','Inscription au fichier(Validite)','Inscription au fichier(Validite)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6701,36,'INFORMATIONS_GENERALES_TRANSPORT_MOYEN_TRANSPORT_CODE','Moyen de Transport(Code)','Mean of Transport(Code)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6702,36,'INFORMATIONS_GENERALES_TRANSPORT_MOYEN_TRANSPORT_LIBELLE','Moyen de Transport (Libellé)','Mean of Transport (Label)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6703,36,'INFORMATIONS_GENERALES_TRANSPORT_MODE_TRANSPORT_CODE','Mode de Transport (Code)','Transportation Mode (Code)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6704,36,'INFORMATIONS_GENERALES_TRANSPORT_MODE_TRANSPORT_LIBELLE','Mode de Transport (Libellé)','Transportation Mode (Label)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6705,36,'INFORMATIONS_GENERALES_TRANSPORT_DATE_ARRIVEE_DEPART','Date d''Arrivée/de Départ','Arrival/Departure Date',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6706,36,'INFORMATIONS_GENERALES_TRANSPORT_NUM_CONNAISSEMENT_LTA','Numéro du Connaissement','Bill of Lading Number',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6707,36,'INFORMATIONS_GENERALES_LIEU_CHARGEMENT_UNLOCODE','Lieu de chargement(UN/Locode)','Loading Place(UN/Locode)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6708,36,'INFORMATIONS_GENERALES_LIEU_CHARGEMENT_LIBELLE','Lieu de chargement(Libellé)','Loading Place(Label)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6709,36,'INFORMATIONS_GENERALES_LIEU_TRANSIT_UNLOCODE','Lieu de Transit(UN/Locode)','Transit Place(UN/Locode)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6710,36,'INFORMATIONS_GENERALES_LIEU_TRANSIT_LIBELLE','Lieu de Transit (Libellé)','Transit Place (Label)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6711,36,'INFORMATIONS_GENERALES_LIEU_DECHARGEMENT_UNLOCODE','Lieu de Déchargement (UN/Locode)','Unloading Place (UN/Locode)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6712,36,'INFORMATIONS_GENERALES_LIEU_DECHARGEMENT_LIBELLE','Lieu de déchargement (Libellé)','Unloading Place (Label)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6713,36,'INFORMATIONS_GENERALES_SIGNATAIRE_NOM','Signataire: Nom','Signatory: Name',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6714,36,'INFORMATIONS_GENERALES_SIGNATAIRE_QUALITE','Signataire: Qualité','Signatory: Position',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6715,36,'INFORMATIONS_GENERALES_SIGNATAIRE_LIEU','Signataire: Lieu','Signature: Place',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6716,36,'INFORMATIONS_GENERALES_SIGNATAIRE_DATE','Signature: Date','Signature: Date',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6717,36,'INFORMATIONS_GENERALES_PERMIS_NUMERO_PERMIS','Permis: Numéro','License: Number',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6718,36,'INFORMATIONS_GENERALES_PERMIS_DATE','Permis: Date','License: Date',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6719,36,'INFORMATIONS_GENERALES_PERMIS_DELIVREUR_RAISONSOCIALE','Permis: Délivreur: Raison Sociale','License: Issuer: Name/Business Name',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6720,36,'INFORMATIONS_GENERALES_PERMIS_DELIVREUR_ADRESSE_ADRESSE1','Permis: Délivreur: Adresse (Adresse 1)','License: Issuer: Address (Address 1)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6721,36,'INFORMATIONS_GENERALES_PERMIS_DELIVREUR_ADRESSE_ADRESSE2','Permis: Délivreur: Adresse (Adresse 2)','License: Issuer: Address (Address 2)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6722,36,'INFORMATIONS_GENERALES_PERMIS_DELIVREUR_ADRESSE_BP','Permis: Délivreur: Adresse (BP)','License: Issuer: Address (P.O. Box)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6723,36,'INFORMATIONS_GENERALES_PERMIS_DELIVREUR_ADRESSE_PAYSADDRESS_CODEPAYS','Permis: Délivreur: Pays Adresse (Code Pays)','License: Issuer: Address Country (Country Code)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6724,36,'INFORMATIONS_GENERALES_PERMIS_DELIVREUR_ADRESSE_PAYSADDRESS_NOMPAYS','Permis: Délivreur: Pays Adresse (Nom Pays)','License: Issuer: Address Country (Country Name)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6725,36,'INFORMATIONS_GENERALES_PERMIS_DELIVREUR_ADRESSE_VILLE','Permis: Délivreur: Adresse (Ville)','License: Issuer: Address (City)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6726,36,'INFORMATIONS_GENERALES_PERMIS_DELIVREUR_ADRESSE_ADRESSEELECTRONIQUE','Permis: Délivreur: Adresse (Adresse Électronique)','License: Issuer: Address (e-mail Address)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6727,36,'INFORMATIONS_GENERALES_PERMIS_DELIVREUR_ADRESSE_SITEWEB','Permis: Délivreur: Adresse (Site Web)','License: Issuer: Address (Web Site)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6728,36,'INFORMATIONS_GENERALES_PERMIS_DELIVREUR_TELEPHONE_FIXE_INDICATIFPAYS','Permis: Délivreur: Téléphone Fixe (Indicatif Pays)','License: Issuer: Telephone (Country Dialing Code)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6729,36,'INFORMATIONS_GENERALES_PERMIS_DELIVREUR_TELEPHONE_FIXE_NUMERO','Permis: Délivreur: Téléphone Fixe (Numéro)','License: Issuer: Telephone (Number)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6730,36,'INFORMATIONS_GENERALES_PERMIS_DELIVREUR_TELEPHONE_MOBILE_INDICATIFPAYS','Permis: Délivreur: Téléphone Mobile (Indicatif Pays)','License: Issuer: Mobile Phone (Country Dialing Code)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6731,36,'INFORMATIONS_GENERALES_PERMIS_DELIVREUR_TELEPHONE_MOBILE_NUMERO','Permis: Délivreur: Téléphone Mobile (Numéro)','License: Issuer: Mobile Phone (Number)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6732,36,'INFORMATIONS_GENERALES_PERMIS_DELIVREUR_FAX_INDICATIFPAYS','Permis: Délivreur: Fax (Indicatif Pays)','License: Issuer: Fax (Country Dialing Code)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6733,36,'INFORMATIONS_GENERALES_PERMIS_DELIVREUR_FAX_NUMERO','Permis: Délivreur: Fax (Numéro)','License: Issuer: Fax (Number)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6734,36,'INFORMATIONS_GENERALES_PERMIS_PAYS_CODEPAYS','Permis: Pays (Code Pays)','License: Country (Country Code)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6738,36,'INFORMATIONS_GENERALES_PERMIS_PAYS_NOMPAYS','Permis: Pays (Nom Pays)','License: Country (Country Name)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6739,36,'INFORMATIONS_GENERALES_LETTRE_TRANSPORT_NUMERO_ESCALE','Lettre de Transport: Numéro d''Escale','Lading Bill: Stopover Number',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6740,36,'INFORMATIONS_GENERALES_LETTRE_TRANSPORT_TYPE_LETTRE_TRANSPORT','Lettre de Transport: Type','Lading Bill: Type',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6741,36,'INFORMATIONS_GENERALES_LETTRE_TRANSPORT_NUMERO_Lettre_TRANSPORT','Lettre de Transport: Numéro','Lading Bill: Number',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6742,36,'INFORMATIONS_GENERALES_LETTRE_TRANSPORT_DATE_LETTRE_TRANSPORT','Lettre de Transport: Date','Lading Bill: Date',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6743,36,'INFORMATIONS_GENERALES_PAYS_TRANSIT_CODEPAYS','Pays de Transit (Code Pays)','Transit Country (Country Code)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6744,36,'INFORMATIONS_GENERALES_PAYS_TRANSIT_NOMPAYS','Pays de Transit (Nom Pays)','Transit Country (Country Name)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6745,36,'INFORMATIONS_GENERALES_CONDITIONS','Conditions','Conditions',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6746,36,'INFORMATIONS_GENERALES_TERMES_VENTE_CODE','Termes de Vente (Code)','Sales Terms (Code)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6747,36,'INFORMATIONS_GENERALES_TERMES_VENTE_LIBELLE','Termes de Vente (Libellé)','Sales Terms (Label)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6748,36,'INFORMATIONS_GENERALES_TERMES_VENTE_CODE_DEVISE','Termes de Vente (Code Devise)','Sales Terms (Currency Code)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6749,36,'INFORMATIONS_GENERALES_TERMES_VENTE_MONTANT','Termes de Vente (Montant)','Sales Terms (Amount)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6750,36,'INFORMATIONS_GENERALES_TERMES_VENTE_MONTANT_TOTAL_DEVISE','Termes de Vente (Montant Total Par Devise)','Sales Terms (Total Amount Per Currency)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6751,36,'INFORMATIONS_GENERALES_TERMES_MONTANT_TOTAL_FCFA','Termes De Vente (Montant Total Par FCFA)','Sales Terms (Total Amount Per FCFA)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6752,36,'INFORMATIONS_GENERALES_POINT_ENTREE_UNLOCODE','Point d''Entrée(unlocode)','Entry Point(UN/Locode)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6753,36,'INFORMATIONS_GENERALES_POINT_ENTREE_LIBELLE','Point d''Entrée(Libellé)','Entry Point(Label)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6754,36,'INFORMATIONS_GENERALES_AGREMENT_TYPE','Agrément (Type)','Approval (Type)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6755,36,'INFORMATIONS_GENERALES_AGREMENT_REFERENCE','Agrément (Référence)','Approval (Reference)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6756,36,'INFORMATIONS_GENERALES_AGREMENT_DATE','Agrément (Date)','Approval (Date)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6757,36,'INFORMATIONS_GENERALES_PERMIS_EXPLOITATION_NUMERO_FACTURE','Permis d''Exploitation (Numéro Facture)','Operating License (Invoice Number)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6758,36,'INFORMATIONS_GENERALES_PERMIS_EXPLOITATION_DATE_FACTURE','Permis d''Exploitation (Date Facture)','Operating License (Invoice Date)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6759,36,'INFORMATIONS_GENERALES_PERMIS_EXPLOITATION_VALIDITE','Permis d''Exploitation (Validité)','Operating License (Validity)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6760,36,'INFORMATIONS_GENERALES_PERMIS_EXPLOITATION_TITULAIRE','Permis d''Exploitation (Titulaire)','Operating License (Holder)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6761,36,'INFORMATIONS_GENERALES_DESTINATAIRE_RAISONSOCIALE','Destinataire: Raison Sociale','Recipient: Name/Business Name',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6762,36,'INFORMATIONS_GENERALES_DESTINATAIRE_ADRESSE_ADRESSE1','Destinataire: Adresse  (Adresse 1)','Recipient: Address (Address 1)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6763,36,'INFORMATIONS_GENERALES_DESTINATAIRE_ADRESSE_ADRESSE2','Destinataire: Adresse (Adresse 2)','Recipient: Address (Address 2)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6764,36,'INFORMATIONS_GENERALES_DESTINATAIRE_ADRESSE_BP','Destinataire: Adresse (BP)','Recipient: Address (P.O. Box)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6765,36,'INFORMATIONS_GENERALES_DESTINATAIRE_ADRESSE_PAYSADDRESS_CODEPAYS','Destinataire: Adresse Pays (Code Pays)','Recipient: Address Country (Country Code)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6766,36,'INFORMATIONS_GENERALES_DESTINATAIRE_ADRESSE_PAYSADDRESS_NOMPAYS','Destinataire: Adresse Pays (Nom Pays)','Recipient: Address Country (Country Name)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6767,36,'INFORMATIONS_GENERALES_DESTINATAIRE_ADRESSE_VILLE','Adresse (Ville)','Recipient: Address (City)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6768,36,'INFORMATIONS_GENERALES_DESTINATAIRE_ADRESSE_ADRESSEELECTRONIQUE','Adresse (Adresse Électronique)','Recipient: Address (e-mail Address)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6769,36,'INFORMATIONS_GENERALES_DESTINATAIRE_ADRESSE_SITEWEB','Destinataire: Adresse (Site Web)','Recipient: Address (Web Site)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6770,36,'INFORMATIONS_GENERALES_DESTINATAIRE_TELEPHONE_FIXE_INDICATIFPAYS','Destinataire: Téléphone Fixe (Indicatif Pays)','Recipient: Telephone (Country Dialing Code)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6771,36,'INFORMATIONS_GENERALES_DESTINATAIRE_TELEPHONE_FIXE_NUMERO','Téléphone Fixe (Numéro)','Telephone (Number)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6772,36,'INFORMATIONS_GENERALES_DESTINATAIRE_TELEPHONE_MOBILE_INDICATIFPAYS','Destinataire: Téléphone Mobile (Indicatif Pays)','Recipient: Mobile Phone (Country Dialing Code)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6773,36,'INFORMATIONS_GENERALES_DESTINATAIRE_TELEPHONE_MOBILE_NUMERO','Destinataire: Téléphone Mobile (Numéro)','Recipient: Mobile Phone (Number)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6774,36,'INFORMATIONS_GENERALES_DESTINATAIRE_FAX_INDICATIFPAYS','Destinataire: Fax (Indicatif Pays)','Recipient: Fax (Country Dialing Code)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6775,36,'INFORMATIONS_GENERALES_DESTINATAIRE_FAX_NUMERO','Destinataire: Fax (Numéro)','Recipient: Fax (Number)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6776,36,'INFORMATIONS_GENERALES_LIEU_DELIVRANCE_LIEU_DELIVRANCE','Lieu de Délivrance','Place of Issue',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6777,36,'INFORMATIONS_GENERALES_LIEU_DELIVRANCE_ORGANISME','Lieu de délivrance: Organisme','Place of Issue: Organization',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6778,36,'INFORMATIONS_GENERALES_PAYS_ORIGINE_CODE_PAYS','Pays d''Origine (Code Pays)','Origin Country (Country Code)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6779,36,'INFORMATIONS_GENERALES_PAYS_ORIGINE_NOM_PAYS','Pays d''Origine (Nom Pays)','Origin Country (Country Name)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6780,36,'INFORMATIONS_GENERALES_PAYS_DESTINATION_CODE_PAYS','Pays de Destination (Code Pays)','Destination Country (Country Code)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6781,36,'INFORMATIONS_GENERALES_PAYS_DESTINATION_NOM_PAYS','Pays de Destination (Nom Pays)','Destination Country (Country Name)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6782,36,'INFORMATIONS_GENERALES_PAYS_PROVENANCE_CODE_PAYS','Pays de Provenance (Code Pays)','Country of Provenance (Country Code)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6783,36,'INFORMATIONS_GENERALES_PAYS_PROVENANCE_NOM_PAYS','Pays de Provenance (Nom Pays)','Country of Provenance (Country Name)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (6784,36,'NUMERO_ARRETE_APPROBATION','Arrêté d''approbation (Numéro)','Order of Approval (Number)',0,1,1);

COMMIT;

-- FILE_ITEM_FIELD
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (6418,36,'NOM_COMMERCIAL','Nom Commercial',' Nom Commercia',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (6419,36,'NOM_SCIENTIFIQUE','Nom Scientifique',' Nom Scientifique',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (6420,36,'PRESENTATION','Formule chimique','Chemical formula',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (6421,36,'SPECIFICATION_TECHNIQUE','Spécification technique','Technical Specification',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (6422,36,'UNITE','Unité', 'Unité',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (6423,36,'POIDS','Poids','Weight',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (6424,36,'VOLUME','Volume','Volume',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (6425,36,'MARQUE','Marque','Brand',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (6426,36,'CATEGORIE','Catégorie','Category',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (6427,36,'MODE_EMBALLAGE','Mode d''emballage','Packaging mode',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (6428,36,'PAYS_ORIGINE_CODE_PAYS','Code pays','Origin country (Code)',34,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (6429,36,'PAYS_ORIGINE_NOM_PAYS','Nom pays','Origin country (Name)',34,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (6430,36,'VALEUR_CAF','Valeur CAF','CAF Value',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (6431,36,'LIEU_ESSAI','Lieu des essais','Place of testing',1,1,0);