/**
 * Author:  tadzotsa
 * Created: 14 mai 2020
 */

ALTER TABLE SIAT_CT.FILE_TYPE ADD CONSTRAINT FILE_TYPE_UK_CODE UNIQUE (CODE) ENABLE;

UPDATE SIAT_CT.FILE_TYPE SET LABEL_FR = 'Procès Verbal Empotage', LABEL_EN = 'Potting Report' WHERE CODE = 'CCT_CT_E_PVE';
INSERT INTO SIAT_CT.FILE_TYPE (ID,CODE,LABEL_EN,LABEL_FR,PAYMENT_FILE_TYPE) VALUES (SIAT_CT.FILE_TYPE_SEQ.NEXTVAL,'CCT_CT_E_PVE','Potting Report','Procès Verbal Empotage','FPVE');

--
INSERT INTO SIAT_CT.STEP (ID,IS_FINAL,LABELEN,LABELFR,CODE) VALUES (SIAT_CT.STEP_SEQ.NEXTVAL,0,'Cotation','Cotation','ST_CT_58');
INSERT INTO SIAT_CT.STEP (ID,IS_FINAL,LABELEN,LABELFR,CODE) VALUES (SIAT_CT.STEP_SEQ.NEXTVAL,0,'Study after appointment notification for potting','Etude suite notification de RDV pour empotage','ST_CT_59');

--
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_45'),0,'Potting File Submission','Dépôt Dossier Empotage');
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_46'),0,'Admissibility after Potting File Submission','Recevabilité suite Dépôt Dossier Empotage');
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_57'),0,'Invoice Validation','Validation Facture');
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_42'),0,'Payment','Encaissement');
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_47'),0,'Cotation','Cotation');
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_48'),0,'Study after appointment request for potting','Etude suite demande de RDV pour empotage');
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_04'),0,'Potting Report Validation','Validation Procès Verbal Empotage');
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_31'),0,'Potting Report Signature','Signature Procès Verbal Empotage');
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_06'),0,'Potting Report End','Fin Procès Verbal Empotage');

--
INSERT INTO SIAT_CT.FLOW (ID,CODE,DURATION,IS_COTA,LABELEN,LABELFR,OUTGOING,FROM_STEP,TO_STEP) VALUES (SIAT_CT.FLOW_SEQ.NEXTVAL,'FL_CT_127',24,0,'Further informations request','Demande de complément d''informations',1,(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_48'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_45'));

--
INSERT INTO SIAT_CT.DATA_TYPE (ID,FLOW_ID,LABEL,REQUIRED,TYPE) VALUES (SIAT_CT.DATA_TYPE_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_127'),'Observation',1,'inputTextarea');

--
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Potting Request','Demande Empotage',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_99'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Validation without invoice','Validation sans facture',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_100'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Billing','Facturation',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_124'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Invoice Authorization','Autorisation Facture',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_121'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Back to billing','Retour à la facturation',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_125'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Payment','Encaissement',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_126'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Cotation','Cotation',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_103'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Further informations request','Demande de complément d''informations',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_127'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Appointment Confirmation','Confirmation rendez-vous',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_104'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Further informations request','Demande de complément d''informations',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_24'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Potting report for signature','Procès verbal pour signature',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_07'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Back to validation','Retour à la validation',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_76'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Potting report authorization','Autorisation Procès Verbal',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_08'));

--
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'E001','FL_CT_99',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'E021',NULL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'E002','FL_CT_24',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'E002','FL_CT_127',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'E601','FL_CT_121',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'E602','FL_CT_126',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'E003','FL_CT_104',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'E005','FL_CT_08',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'));