/**
 * Author:  ht
 * Created: 10-Nov-2020
 */

-- CCT_CT_E
-- ST_CT_01
UPDATE SIAT_CT.FILE_TYPE_STEP FTS SET FTS.LABEL_EN = 'File deposit', FTS.LABEL_FR = 'Dépôt dossier' WHERE FTS.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E') AND FTS.STEP_ID = (SELECT S.ID FROM SIAT_CT.STEP S WHERE S.CODE = 'ST_CT_01');
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'Technical control certificate request', FTF.LABEL_FR = 'Demande de certificat de contrôle technique' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_01');
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'Further information', FTF.LABEL_FR = 'Complément d''information' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_03');
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'Further information', FTF.LABEL_FR = 'Complément d''information' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_68');

-- ST_CT_02
UPDATE SIAT_CT.FILE_TYPE_STEP FTS SET FTS.LABEL_EN = 'Admissibility', FTS.LABEL_FR = 'Recevabilité' WHERE FTS.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E') AND FTS.STEP_ID = (SELECT S.ID FROM SIAT_CT.STEP S WHERE S.CODE = 'ST_CT_02');
-- FL_CT_05
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'File Admission', FTF.LABEL_FR = 'Admission dossier' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_05');
-- FL_CT_02
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'Further information request', FTF.LABEL_FR = 'Demande de complément d''information' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_02');
-- FL_CT_04
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'Rejection', FTF.LABEL_FR = 'Rejet' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_04');

-- ST_CT_04
-- FL_CT_151
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'Validation after study', FTF.LABEL_FR = 'Validation suite étude' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_151');
-- FL_CT_24
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'Further information request', FTF.LABEL_FR = 'Demande de complément d''information' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_24');
-- FL_CT_91
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'Rejection', FTF.LABEL_FR = 'Rejet' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_91');

-- ST_CT_31
UPDATE SIAT_CT.FILE_TYPE_STEP FTS SET FTS.LABEL_EN = 'Signature', FTS.LABEL_FR = 'Signature' WHERE FTS.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E') AND FTS.STEP_ID = (SELECT S.ID FROM SIAT_CT.STEP S WHERE S.CODE = 'ST_CT_31');
-- FL_CT_08
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'Supervision file Authorization', FTF.LABEL_FR = 'Autorisation fiche de supervision' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_08');
-- FL_CT_154
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'Return for further study', FTF.LABEL_FR = 'Retour pour ré-étude' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_154');
