/**
 * Author:  ht
 * Created: 18-Nov-2020
 */

-- CCT_CT_E_PVI
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (FILE_TYPE_ID,FLOW_ID,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_128'),'Further information','Complément d''information');
-- CCT_CT_E_FSTP
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (FILE_TYPE_ID,FLOW_ID,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_128'),'Further information','Complément d''information');
-- CCT_CT_E_ATP
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (FILE_TYPE_ID,FLOW_ID,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_ATP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_03'),'Further information','Complément d''information');
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (FILE_TYPE_ID,FLOW_ID,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_ATP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_68'),'Further information','Complément d''information');
-- CCT_CT_E
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'Further information request', FTF.LABEL_FR = 'Demande de complément d''information' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_03');
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'Further information request', FTF.LABEL_FR = 'Demande de complément d''information' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_68');
