/**
 * Author:  tadzotsa
 * Created: 21 avr. 2020
 */

INSERT INTO SIAT_CT.AUTHORITY (ID,ROLE,LABEL_FR,LABEL_EN,AUTHORITY_TYPE) VALUES ((SELECT MAX(ID) + 1 FROM SIAT_CT.AUTHORITY),'GA','Gestion des Agents','Agents Management','ADMINISTRATION');
INSERT INTO SIAT_CT.POSITION_AUTHORITY (POSITION_TYPE,AUTHORITY_ID) VALUES ('AGENT',(SELECT ID FROM SIAT_CT.AUTHORITY WHERE ROLE = 'GA'));
--
COMMIT;


