/**
 * This change.log is related to version 2.3.0 of siat-ct-core
 *
 * Author:  ht
 * Created: 5 oct. 2020
 */

-- NEW POSITION_AUTHORITY : VALIDATION_SIGNATURE & AGENT
INSERT INTO SIAT_CT.POSITION_AUTHORITY (POSITION_TYPE,AUTHORITY_ID) VALUES ('AGENT',(SELECT ID FROM SIAT_CT.AUTHORITY WHERE ROLE = 'VS'));

-- UNLINK DECISIONS FL_CT_07 AND FL_CT_76 WITH PROCESS CCT_CT_E
DELETE FROM SIAT_CT.FILE_TYPE_FLOW FTF WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E')
AND FTF.FLOW_ID IN (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE IN ('FL_CT_07','FL_CT_76'));

-- ASSOCIATION FLOW WITH FILE_TYPE
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization after study','Autorisation suite étude',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_151'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Return on study','Retour pour ré-examen',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_152'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Validation for signature','Validation pour signature',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_153'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Return on study','Retour pour ré-examen',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_154'));

-- PARAMS FOR BUREAUX FOR WHICH AUTOMATIC DECISION WILL BE TAKEN
--INSERT INTO SIAT_CT.PARAMS (ID,NAME,VALUE,CATEGORY) VALUES (SIAT_CT.PARAMS_SEQ.NEXTVAL,'system.automatic.decison.KRIBIAIREPORT.CCT_CT_E.ST_CT_65','FL_CT_153','GN');

