/**
 * Author:  tadzotsa
 * Created: 5 mai 2020
 */

-- mise à jour de séquences : SIAT_CT.FILE_ITEM_FIELD_SEQ
-- SELECT 'DROP SEQUENCE SIAT_CT.FILE_ITEM_FIELD_SEQ;CREATE SEQUENCE SIAT_CT.FILE_ITEM_FIELD_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH '||(SELECT MAX(ID) + 1 FROM SIAT_CT.FILE_ITEM_FIELD)||' CACHE 20 NOORDER NOCYCLE;' FROM DUAL;

-- création de séquences : SIAT_CT.INVOICE_LINE_SEQ
--CREATE SEQUENCE SIAT_CT.INVOICE_LINE_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE ;

--
INSERT INTO SIAT_CT.AUTHORITY (ID,ROLE,LABEL_FR,LABEL_EN,AUTHORITY_TYPE) VALUES ((SELECT MAX(ID) + 1 FROM SIAT_CT.AUTHORITY),'VF','Validation Facture','Invoice Validation','DECISION');
INSERT INTO SIAT_CT.POSITION_AUTHORITY (POSITION_TYPE,AUTHORITY_ID) VALUES ('AGENT',(SELECT ID FROM SIAT_CT.AUTHORITY WHERE ROLE = 'VF'));

-- STEPs
INSERT INTO SIAT_CT.STEP (ID,IS_FINAL,LABELEN,LABELFR,CODE) VALUES (SIAT_CT.STEP_SEQ.NEXTVAL,0,'Invoice Validation','Validation Facture','ST_CT_57');

-- assiciation STEPs avec FILE_TYPE CCT_CT_E et CCT_CT_E_ATP
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_57'),0,'Invoice Validation','Validation Facture');
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_ATP'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_57'),0,'Invoice Validation','Validation Facture');
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_57'),0,'Invoice Validation','Validation Facture');
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_57'),0,'Invoice Validation','Validation Facture');
-- assiciation du STEP ST_CT_42 avec avec FILE_TYPE CCT_CT_E_ATP
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_ATP'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_42'),0,'Encaissement','Payment');
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_42'),0,'Encaissement','Payment');
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_42'),0,'Encaissement','Payment');

-- assiciation STEPs avec rôles
INSERT INTO SIAT_CT.STEP_AUTHORITY (STEP_ID, AUTHORITY_ID) VALUES ((SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_57'), (SELECT ID FROM SIAT_CT.AUTHORITY WHERE ROLE = 'VF'));

-- FLOWs
INSERT INTO SIAT_CT.FLOW (ID,CODE,DURATION,IS_COTA,LABELEN,LABELFR,OUTGOING,FROM_STEP,TO_STEP) VALUES (SIAT_CT.FLOW_SEQ.NEXTVAL,'FL_CT_120',24,0,'Billing','Facturation',0,(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_02'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_57'));
INSERT INTO SIAT_CT.FLOW (ID,CODE,DURATION,IS_COTA,LABELEN,LABELFR,OUTGOING,FROM_STEP,TO_STEP) VALUES (SIAT_CT.FLOW_SEQ.NEXTVAL,'FL_CT_121',24,0,'Invoice Authorization','Autorisation Facture',1,(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_57'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_42'));
INSERT INTO SIAT_CT.FLOW (ID,CODE,DURATION,IS_COTA,LABELEN,LABELFR,OUTGOING,FROM_STEP,TO_STEP) VALUES (SIAT_CT.FLOW_SEQ.NEXTVAL,'FL_CT_122',24,0,'Back to billing','Retour à la facturation',0,(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_57'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_02'));
INSERT INTO SIAT_CT.FLOW (ID,CODE,DURATION,IS_COTA,LABELEN,LABELFR,OUTGOING,FROM_STEP,TO_STEP) VALUES (SIAT_CT.FLOW_SEQ.NEXTVAL,'FL_CT_123',24,0,'Payment','Encaissement',1,(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_42'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_03'));
INSERT INTO SIAT_CT.FLOW (ID,CODE,DURATION,IS_COTA,LABELEN,LABELFR,OUTGOING,FROM_STEP,TO_STEP) VALUES (SIAT_CT.FLOW_SEQ.NEXTVAL,'FL_CT_124',24,0,'Billing','Facturation',0,(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_46'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_57'));
INSERT INTO SIAT_CT.FLOW (ID,CODE,DURATION,IS_COTA,LABELEN,LABELFR,OUTGOING,FROM_STEP,TO_STEP) VALUES (SIAT_CT.FLOW_SEQ.NEXTVAL,'FL_CT_125',24,0,'Back to billing','Retour à la facturation',0,(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_57'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_46'));
INSERT INTO SIAT_CT.FLOW (ID,CODE,DURATION,IS_COTA,LABELEN,LABELFR,OUTGOING,FROM_STEP,TO_STEP) VALUES (SIAT_CT.FLOW_SEQ.NEXTVAL,'FL_CT_126',24,0,'Payment','Encaissement',1,(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_42'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_47'));

-- assiciation FLOWs avec FILE_TYPE CCT_CT_E et CCT_CT_E_ATP
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Billing','Facturation',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_120'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Billing','Facturation',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_ATP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_120'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Billing','Facturation',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_124'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Billing','Facturation',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_124'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Invoice Authorization','Autorisation Facture',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_121'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Invoice Authorization','Autorisation Facture',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_ATP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_121'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Invoice Authorization','Autorisation Facture',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_121'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Invoice Authorization','Autorisation Facture',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_121'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Back to billing','Retour à la facturation',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_122'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Back to billing','Retour à la facturation',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_ATP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_122'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Back to billing','Retour à la facturation',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_125'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Back to billing','Retour à la facturation',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_125'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Payment','Encaissement',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_123'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Payment','Encaissement',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_ATP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_123'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Payment','Encaissement',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_126'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Payment','Encaissement',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_126'));

-- création DATA_TYPEs pour les FLOWs
INSERT INTO SIAT_CT.DATA_TYPE (ID,FLOW_ID,LABEL,REQUIRED,TYPE) VALUES (SIAT_CT.DATA_TYPE_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_121'),'Observation',0,'inputTextarea');
INSERT INTO SIAT_CT.DATA_TYPE (ID,FLOW_ID,LABEL,REQUIRED,TYPE) VALUES (SIAT_CT.DATA_TYPE_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_122'),'Observation',1,'inputTextarea');
INSERT INTO SIAT_CT.DATA_TYPE (ID,FLOW_ID,LABEL,REQUIRED,TYPE) VALUES (SIAT_CT.DATA_TYPE_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_125'),'Observation',1,'inputTextarea');

-- création FILE_TYPE_FLOW_REPORT pour le FLOW de validation de facture
INSERT INTO SIAT_CT.FILE_TYPE_FLOW_REPORT (ID,REPORT_CLASS_NAME,REPORT_NAME,FILE_FIELD_NAME,FILE_TYPE_ID,FLOW_ID,ORGANISM_ID) VALUES (SIAT_CT.FILE_TYPE_FLOW_REPORT_SEQ.NEXTVAL, 'org.guce.siat.web.reports.exporter.CteInvoiceExporter', 'CCT_CT_E_INV.pdf','NUMERO_FACTURE', (SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E'), (SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_121'), 3);
INSERT INTO SIAT_CT.FILE_TYPE_FLOW_REPORT (ID,REPORT_CLASS_NAME,REPORT_NAME,FILE_FIELD_NAME,FILE_TYPE_ID,FLOW_ID,ORGANISM_ID) VALUES (SIAT_CT.FILE_TYPE_FLOW_REPORT_SEQ.NEXTVAL, 'org.guce.siat.web.reports.exporter.CteInvoiceExporter', 'CCT_CT_E_INV.pdf','NUMERO_FACTURE', (SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_ATP'), (SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_121'), 3);
INSERT INTO SIAT_CT.FILE_TYPE_FLOW_REPORT (ID,REPORT_CLASS_NAME,REPORT_NAME,FILE_FIELD_NAME,FILE_TYPE_ID,FLOW_ID,ORGANISM_ID) VALUES (SIAT_CT.FILE_TYPE_FLOW_REPORT_SEQ.NEXTVAL, 'org.guce.siat.web.reports.exporter.CteInvoiceExporter', 'CCT_CT_E_INV.pdf','NUMERO_FACTURE', (SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'), (SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_121'), 3);
INSERT INTO SIAT_CT.FILE_TYPE_FLOW_REPORT (ID,REPORT_CLASS_NAME,REPORT_NAME,FILE_FIELD_NAME,FILE_TYPE_ID,FLOW_ID,ORGANISM_ID) VALUES (SIAT_CT.FILE_TYPE_FLOW_REPORT_SEQ.NEXTVAL, 'org.guce.siat.web.reports.exporter.CteInvoiceExporter', 'CCT_CT_E_INV.pdf','NUMERO_FACTURE', (SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'), (SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_121'), 3);

-- FILE_FIELDs pour NUMERO_FACTURE
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM FILE_TYPE WHERE CODE = 'CCT_CT_E'),'NUMERO_FACTURE','Numéro Facture','Invoice Number',0,10,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM FILE_TYPE WHERE CODE = 'CCT_CT_E_ATP'),'NUMERO_FACTURE','Numéro Facture','Invoice Number',0,10,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'),'NUMERO_FACTURE','Numéro Facture','Invoice Number',0,10,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),'NUMERO_FACTURE','Numéro Facture','Invoice Number',0,10,0);

-- assiciation FLOWs GUCE avec FLOWs SIAT pour FILE_TYPE CCT_CT_E et CCT_CT_E_ATP
DELETE FROM SIAT_CT.FLOW_GUCE_SIAT WHERE FLOW_GUCE IN ('CTE601','CTE602');
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'CTE601','FL_CT_121',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'CTE601','FL_CT_121',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_ATP'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'CTE601','FL_CT_121',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'CTE601','FL_CT_121',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'CTE602','FL_CT_123',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'CTE602','FL_CT_123',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_ATP'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'CTE602','FL_CT_126',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'CTE602','FL_CT_126',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'));

-- FILE_TYPE PAYMENT
INSERT INTO SIAT_CT.FILE_TYPE (ID, CODE, LABEL_EN, LABEL_FR) VALUES (SIAT_CT.FILE_TYPE_SEQ.NEXTVAL, 'PAYMENT', 'Payment', 'Paiement');
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'PAY601',NULL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'PAYMENT'));
-- INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'PAY602',NULL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'PAYMENT'));

--
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E'),'CLIENT_PERSONNE_A_CONTACTER','Personne à contacter','Person to contact',0,1,1);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_ATP'),'CLIENT_PERSONNE_A_CONTACTER','Personne à contacter','Person to contact',0,1,1);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'),'CLIENT_PERSONNE_A_CONTACTER','Personne à contacter','Person to contact',0,1,1);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),'CLIENT_PERSONNE_A_CONTACTER','Personne à contacter','Person to contact',0,1,1);
--
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E'),'TRANSITAIRE_ADRESSE_EMAIL','Email','Email',0,7,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_ATP'),'TRANSITAIRE_ADRESSE_EMAIL','Email','Email',0,7,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'),'TRANSITAIRE_ADRESSE_EMAIL','Email','Email',0,7,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),'TRANSITAIRE_ADRESSE_EMAIL','Email','Email',0,7,0);
--
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (SIAT_CT.FILE_ITEM_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_ATP'),'NOMBRE_SACS','Nombre de sacs','Number of bags',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (SIAT_CT.FILE_ITEM_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'),'NOMBRE_SACS','Nombre de sacs','Number of bags',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (SIAT_CT.FILE_ITEM_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),'NOMBRE_SACS','Nombre de sacs','Number of bags',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (SIAT_CT.FILE_ITEM_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_ATP'),'NOMBRE_GRUMES','Nombre de grumes','Number of logs',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (SIAT_CT.FILE_ITEM_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'),'NOMBRE_GRUMES','Nombre de grumes','Number of logs',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (SIAT_CT.FILE_ITEM_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),'NOMBRE_GRUMES','Nombre de grumes','Number of logs',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (SIAT_CT.FILE_ITEM_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'),'VOLUME','Volume','Volume',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (SIAT_CT.FILE_ITEM_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'),'POIDS','Poids','Weight',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (SIAT_CT.FILE_ITEM_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),'POIDS','Poids','Weight',1,1,0);

--COMMIT;
