

INSERT INTO FIELD_GROUP (ID, LABEL_FR, LABEL_EN) VALUES (64, 'Autre Information', 'Additional information');

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'AUTRE_INFORMATION_DECLARATION_ADDITIONNELLE','Déclaration additionnelle','Additional declaration',0,64,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'AUTRE_INFORMATION_DATE_TRAITEMENT','Date de traitement','Treatment date',0,64,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'AUTRE_INFORMATION_TYPE_TRAITEMENT','Type de traitement','Treatment type',0,64,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'AUTRE_INFORMATION_DUREE_TRAITEMENT','Durée de traitement','Treatment duration',0,64,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'AUTRE_INFORMATION_TEMPERATURE','Température','Temperature',0,64,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'AUTRE_INFORMATION_TRAITEMENT_EFFECTUE','Traitements effectués','Treatments performed',0,64,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'AUTRE_INFORMATION_PRODUIT_CHIMIQUE','Produit chimique (Matière Active)','Chimical product (Active ingredient)',0,64,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'AUTRE_INFORMATION_CONCENTRATION','Concentration','Concentration',0,64,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'AUTRE_INFORMATION_RENSEIGNEMENT_COMPLEMENTAIRE','Renseignement complémentaire','Extra information',0,64,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'AUTRE_INFORMATION_FUMIGATION','Fumigation','Fumigation',0,64,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),33,'AUTRE_INFORMATION_DESINFECTION','Désinfection','Disinfection',0,64,1);
