/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  guce
 * Created: 6 juin 2017
 */

CREATE SEQUENCE GUCE_SIAT_BUREAU_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE  NOORDER  CACHE 20;

INSERT INTO  POSITION_AUTHORITY  (POSITION_TYPE, AUTHORITY_ID) VALUES ('MINISTRE', 4);
INSERT INTO  POSITION_AUTHORITY  (POSITION_TYPE, AUTHORITY_ID) VALUES ('DIRECTEUR', 4);
INSERT INTO  POSITION_AUTHORITY  (POSITION_TYPE, AUTHORITY_ID) VALUES ('SOUS_DIRECTEUR', 4);
INSERT INTO  POSITION_AUTHORITY  (POSITION_TYPE, AUTHORITY_ID) VALUES ('CHEF_SERVICE', 4);
INSERT INTO  POSITION_AUTHORITY  (POSITION_TYPE, AUTHORITY_ID) VALUES ('CHEF_BUREAU', 4);
INSERT INTO  POSITION_AUTHORITY  (POSITION_TYPE, AUTHORITY_ID) VALUES ('AGENT', 4);
COMMIT;

UPDATE FILE_FIELD SET CODE='FOURNISSEUR_SIGLE' WHERE ID='418';
UPDATE FILE_FIELD SET CODE='DETENTEUR_MARQUE_FAX_NUMERO' WHERE ID='444';
UPDATE FILE_ITEM_FIELD SET LABEL_FR='Dénomination commune internationale', LABEL_EN='International name' WHERE ID='412';
INSERT INTO FIELD_GROUP (ID, LABEL_FR, LABEL_EN) VALUES (63, 'Facture', 'Invoice');
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (2868,9,'DATE_VALIDITE','Date validité','Validity date',0,1,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (3066,8,'DATE_VALIDITE','Date validité','Validity date',0,1,1);
COMMIT;

/*UPDATE ON 16/09/2019 - DEFAULT CONFIG ON PARAM CCT CP (PHYTO)*/
INSERT INTO "SIAT_CT"."PARAMS_CCT_CP" (ID, LABEL_ATTACHMENT, MAX_CONTAINER_NUMBER, MAX_GOODS_LINES_NUMBER, MAX_PACKAGE_NUMBER) VALUES ('1', 'Voir Pièce jointe', '18', '6', '6');