/**
 * This change.log is related to version 2.3.0 of siat-ct-core
 *
 * Author:  ht
 * Created: 5 oct. 2020
 */

-- NEW AUTHORITY : VALIDATION_SIGNATURE
INSERT INTO SIAT_CT.AUTHORITY (ID,ROLE,LABEL_FR,LABEL_EN,AUTHORITY_TYPE) VALUES ((SELECT MAX(ID) + 1 FROM SIAT_CT.AUTHORITY),'VS','Validation Signature','Signature Validation','DECISION');
INSERT INTO SIAT_CT.POSITION_AUTHORITY (POSITION_TYPE,AUTHORITY_ID) VALUES ('CHEF_SECTEUR',(SELECT ID FROM SIAT_CT.AUTHORITY WHERE ROLE = 'VS'));
INSERT INTO SIAT_CT.POSITION_AUTHORITY (POSITION_TYPE,AUTHORITY_ID) VALUES ('AGENT',(SELECT ID FROM SIAT_CT.AUTHORITY WHERE ROLE = 'VS'));

-- NEW SIGNATURE VALIDATION STEP
INSERT INTO SIAT_CT.STEP (ID,IS_FINAL,LABELEN,LABELFR,CODE) VALUES (SIAT_CT.STEP_SEQ.NEXTVAL,0,'Validation for signature','Validation pour signature','ST_CT_65');
-- ASSOCIATION STEP WITH AUTHORITY
INSERT INTO SIAT_CT.STEP_AUTHORITY (STEP_ID, AUTHORITY_ID) VALUES ((SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_65'), (SELECT ID FROM SIAT_CT.AUTHORITY WHERE ROLE = 'VS'));
-- ASSOCIATION STEP WITH FILE_TYPE
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_65'),0,'Validation for signature','Validation pour signature');

-- UNLINK DECISIONS FL_CT_07 AND FL_CT_76 WITH PROCESS CCT_CT_E
DELETE FROM SIAT_CT.FILE_TYPE_FLOW FTF WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E')
AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_07');
DELETE FROM SIAT_CT.FILE_TYPE_FLOW FTF WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E')
AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_76');
DELETE FROM SIAT_CT.FILE_TYPE_FLOW FTF WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E')
AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_106');

-- NEW FLOWS
INSERT INTO SIAT_CT.FLOW (ID,CODE,DURATION,IS_COTA,LABELEN,LABELFR,OUTGOING,FROM_STEP,TO_STEP) VALUES (SIAT_CT.FLOW_SEQ.NEXTVAL,'FL_CT_151',24,0,'Authorization after study','Autorisation suite étude',0,(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_04'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_65'));
INSERT INTO SIAT_CT.FLOW (ID,CODE,DURATION,IS_COTA,LABELEN,LABELFR,OUTGOING,FROM_STEP,TO_STEP) VALUES (SIAT_CT.FLOW_SEQ.NEXTVAL,'FL_CT_152',24,0,'Return on study','Retour pour ré-examen',0,(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_65'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_04'));
INSERT INTO SIAT_CT.FLOW (ID,CODE,DURATION,IS_COTA,LABELEN,LABELFR,OUTGOING,FROM_STEP,TO_STEP) VALUES (SIAT_CT.FLOW_SEQ.NEXTVAL,'FL_CT_153',24,0,'Validation for signature','Validation pour signature',0,(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_65'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_31'));
INSERT INTO SIAT_CT.FLOW (ID,CODE,DURATION,IS_COTA,LABELEN,LABELFR,OUTGOING,FROM_STEP,TO_STEP) VALUES (SIAT_CT.FLOW_SEQ.NEXTVAL,'FL_CT_154',24,0,'Return on study','Retour pour ré-examen',0,(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_31'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_65'));

-- ASSOCIATION FLOW WITH FILE_TYPE
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Authorization after study','Autorisation suite étude',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_151'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Return on study','Retour pour ré-examen',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_152'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Validation for signature','Validation pour signature',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_153'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Return on study','Retour pour ré-examen',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_154'));

-- DATA_TYPE
INSERT INTO SIAT_CT.DATA_TYPE (ID,FLOW_ID,LABEL,REQUIRED,TYPE) VALUES (SIAT_CT.DATA_TYPE_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_151'),'Observation',0,'inputTextarea');
INSERT INTO SIAT_CT.DATA_TYPE (ID,FLOW_ID,LABEL,REQUIRED,TYPE) VALUES (SIAT_CT.DATA_TYPE_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_152'),'Observation',1,'inputTextarea');
INSERT INTO SIAT_CT.DATA_TYPE (ID,FLOW_ID,LABEL,REQUIRED,TYPE) VALUES (SIAT_CT.DATA_TYPE_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_153'),'Observation',0,'inputTextarea');
INSERT INTO SIAT_CT.DATA_TYPE (ID,FLOW_ID,LABEL,REQUIRED,TYPE) VALUES (SIAT_CT.DATA_TYPE_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_154'),'Observation',1,'inputTextarea');

-- PARAMS FOR BUREAUX FOR WHICH AUTOMATIC DECISION WILL BE TAKEN
INSERT INTO SIAT_CT.PARAMS (ID,NAME,VALUE,CATEGORY) VALUES (SIAT_CT.PARAMS_SEQ.NEXTVAL,'system.automatic.decison.KRIBIAIREPORT.CCT_CT_E.ST_CT_65','FL_CT_153','GN');

