/**
 * Author:  tadzotsa
 * Created: 13 mai 2020
 */

UPDATE SIAT_CT.FILE_TYPE SET PAYMENT_FILE_TYPE = 'FCTE' WHERE CODE = 'CCT_CT_E';
UPDATE SIAT_CT.FILE_TYPE SET PAYMENT_FILE_TYPE = 'FAT' WHERE CODE = 'CCT_CT_E_ATP';
UPDATE SIAT_CT.FILE_TYPE SET PAYMENT_FILE_TYPE = 'FPVI' WHERE CODE = 'CCT_CT_E_PVI';
UPDATE SIAT_CT.FILE_TYPE SET PAYMENT_FILE_TYPE = 'FSTP' WHERE CODE = 'CCT_CT_E_FSTP';
