/**
 * Author:  ht
 * Created: 05-Nov-2020
 */

INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'CTE303','FL_CT_129',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'CTE103','FL_CT_129',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'CTE302','FL_CT_127',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'CTE102','FL_CT_127',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'CTE302','FL_CT_24',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'CTE102','FL_CT_24',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'));

UPDATE SIAT_CT.FILE_ITEM FI SET FI.DRAFT = 1, FI.STEP_ID = 4 WHERE FI.FILE_ID = (SELECT F.ID FROM SIAT_CT.FILES F WHERE F.NUMERO_DOSSIER = 'CTE009217');
INSERT INTO SIAT_CT.PARAMS(ID, NAME, CATEGORY, VALUE) VALUES (SIAT_CT.PARAMS_SEQ.NEXTVAL, 'backup.received.messages', 'GN', 'true');
