/**
 * Author:  tadzotsa
 * Created: 14 mai 2020
 */

--
UPDATE SIAT_CT.MINISTRY SET CODE = 'MINADER' WHERE ID = 1;

--
UPDATE SIAT_CT.MINISTRY_FILE_TYPE SET AUTOMATIC_COTATION_ALLOWED = 1 WHERE MINISTRY_ID = 1 AND FILE_TYPE_ID IN (SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE IN ('CCT_CT_E','CCT_CT_E_ATP','CCT_CT_E_PVI','CCT_CT_E_FSTP'));
