/**
 * Author:  ht
 * Created: 26 oct. 2020
 */

-- CCT_CT_E_PVI
DELETE FROM SIAT_CT.FILE_TYPE_FLOW WHERE FILE_TYPE_ID = (SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI') AND FLOW_ID = (SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_107');
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (FILE_TYPE_ID,FLOW_ID,LABEL_FR,LABEL_EN) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_104'),'Appointment Confirmation','Confirmation RDV pour inspection');
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (FILE_TYPE_ID,FLOW_ID,LABEL_FR,LABEL_EN) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_127'),'Further informations request','Demande de complément d''informations');
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (FILE_TYPE_ID,FLOW_ID,LABEL_FR,LABEL_EN) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_129'),'Rejection','Rejet');
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (FILE_TYPE_ID,FLOW_ID,LABEL_FR,LABEL_EN) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_24'),'Further informations request','Demande de complément d''informations');
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (FILE_TYPE_ID,FLOW_ID,LABEL_FR,LABEL_EN) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_91'),'Rejection','Rejet');
--
INSERT INTO SIAT_CT.FILE_TYPE_STEP (LABEL_EN,LABEL_FR,FILE_TYPE_ID,STEP_ID) VALUES ('Inspection request deposit', 'Dépôt demande d''inspection',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE ='ST_CT_01'));

-- CCT_CT_E_FSTP
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (FILE_TYPE_ID,FLOW_ID,LABEL_FR,LABEL_EN) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_101'),'Further informations request','Demande de complément d''informations');
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (FILE_TYPE_ID,FLOW_ID,LABEL_FR,LABEL_EN) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_102'),'Rejection','Rejet');
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (FILE_TYPE_ID,FLOW_ID,LABEL_FR,LABEL_EN) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_104'),'Appointment Confirmation','Confirmation RDV pour traitement');
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (FILE_TYPE_ID,FLOW_ID,LABEL_FR,LABEL_EN) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_127'),'Further informations request','Demande de complément d''informations');
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (FILE_TYPE_ID,FLOW_ID,LABEL_FR,LABEL_EN) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_129'),'Rejection','Rejet');
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (FILE_TYPE_ID,FLOW_ID,LABEL_FR,LABEL_EN) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_24'),'Further informations request','Demande de complément d''informations');
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (FILE_TYPE_ID,FLOW_ID,LABEL_FR,LABEL_EN) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_91'),'Rejection','Rejet');
--
INSERT INTO SIAT_CT.FILE_TYPE_STEP (LABEL_EN,LABEL_FR,FILE_TYPE_ID,STEP_ID) VALUES ('Supervision file request deposit', 'Dépôt demande de fiche de supervision',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE ='ST_CT_01'));

-- CCT_CT_E_ATP
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (FILE_TYPE_ID,FLOW_ID,LABEL_FR,LABEL_EN) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_ATP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_24'),'Further informations request','Demande de complément d''informations');
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (FILE_TYPE_ID,FLOW_ID,LABEL_FR,LABEL_EN) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_ATP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_91'),'Rejection','Rejet');

-- CCT_CT_E_PVE
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'E002','FL_CT_101',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'));
