---

CREATE OR REPLACE FORCE VIEW "SIAT_CT"."FILES_PROCESSING" ("ID", "CREATED", "RECEIVED", "SENT", "UNREAD", "FILE_ITEM_ID", "FLOW_ID", "SENDER_ID", "MESSAGE_ID", "ASSIGNED_USER_ID", "FLOW_CODE", "DATE_DEBUT", "DATE_FIN") AS 
  SELECT itf."ID",itf."CREATED",itf."RECEIVED",itf."SENT",itf."UNREAD",itf."FILE_ITEM_ID",itf."FLOW_ID",itf."SENDER_ID",itf."MESSAGE_ID",itf."ASSIGNED_USER_ID", fl.CODE FLOW_CODE, (SELECT MAX(CREATED) FROM ITEM_FLOW WHERE FILE_ITEM_ID = itf.FILE_ITEM_ID AND CREATED < itf.CREATED) DATE_DEBUT, itf.CREATED DATE_FIN
FROM ITEM_FLOW itf
JOIN FLOW fl ON fl.ID = itf.FLOW_ID;

---

CREATE OR REPLACE FORCE VIEW "SIAT_CT"."MINADER_FILE_ITEM" ("ID", "DRAFT", "VALEUR_FOB", "FICTIVE", "LINE_NUMBER", "NUM_EBMS_MSG", "NUM_EBMS_MSG_ANNULATION", "NUM_EBMS_MSG_PAIEMENT", "QUANTITY", "FILE_ID", "NSH_ID", "STEP_ID", "SUBFAMILY_ID", "GOODS_ITEM_DESC", "NOMBRE_GRUMES", "NOMBRE_SACS", "VOLUME", "POIDS_BRUT", "POIDS_NET") AS 
  SELECT fi."ID",fi."DRAFT",fi."VALEUR_FOB",fi."FICTIVE",fi."LINE_NUMBER",fi."NUM_EBMS_MSG",fi."NUM_EBMS_MSG_ANNULATION",fi."NUM_EBMS_MSG_PAIEMENT",fi."QUANTITY",fi."FILE_ID",fi."NSH_ID",fi."STEP_ID",fi."SUBFAMILY_ID", n.GOODS_ITEM_DESC,
(SELECT fifv.VALUE FROM FILE_ITEM_FIELD_VALUE fifv JOIN FILE_ITEM_FIELD fif ON fif.ID = fifv.FILE_ITEM_FIELD_ID WHERE fifv.FILE_ITEM_ID = fi.id AND fif.CODE = 'NOMBRE_GRUMES') NOMBRE_GRUMES,
(SELECT fifv.VALUE FROM FILE_ITEM_FIELD_VALUE fifv JOIN FILE_ITEM_FIELD fif ON fif.ID = fifv.FILE_ITEM_FIELD_ID WHERE fifv.FILE_ITEM_ID = fi.id AND fif.CODE = 'NOMBRE_SACS') NOMBRE_SACS,
(SELECT fifv.VALUE FROM FILE_ITEM_FIELD_VALUE fifv JOIN FILE_ITEM_FIELD fif ON fif.ID = fifv.FILE_ITEM_FIELD_ID WHERE fifv.FILE_ITEM_ID = fi.id AND fif.CODE = 'VOLUME') VOLUME,
(SELECT fifv.VALUE FROM FILE_ITEM_FIELD_VALUE fifv JOIN FILE_ITEM_FIELD fif ON fif.ID = fifv.FILE_ITEM_FIELD_ID WHERE fifv.FILE_ITEM_ID = fi.id AND fif.CODE = 'POIDS_BRUT') POIDS_BRUT,
(SELECT fifv.VALUE FROM FILE_ITEM_FIELD_VALUE fifv JOIN FILE_ITEM_FIELD fif ON fif.ID = fifv.FILE_ITEM_FIELD_ID WHERE fifv.FILE_ITEM_ID = fi.id AND fif.CODE = 'POIDS') POIDS_NET
FROM FILE_ITEM fi JOIN REP_NSH n ON fi.NSH_ID = n.GOODS_ITEM_CODE
JOIN FILES f ON fi.FILE_ID = f.ID 
WHERE f.FILE_TYPE_ID IN (33, 36, 37, 39);

---

  CREATE OR REPLACE FORCE VIEW "SIAT_CT"."MINADER_FILES" ("ID", "CREATED_DATE", "DESTINATAIRE", "EMETTEUR", "FILE_TYPE_GUCE", "FILE_TYPE_GUCE_ANNULATION", "FILE_TYPE_GUCE_PAIEMENT", "NUMERO_DEMANDE", "NUMERO_DEMANDE_ANNULATION", "NUMERO_DEMANDE_PAIEMENT", "NUMERO_DOSSIER", "REFERENCE_GUCE", "REFERENCE_GUCE_ANNULATION", "REFERENCE_GUCE_PAIEMENT", "REFERENCE_SIAT", "ASSIGNED_USER_ID", "BUREAU_ID", "CLIENT_ID", "COUNTRY_OF_DESTINATION", "COUNTRY_OF_ORIGIN", "COUNTRY_OF_PROVENANCE", "FILE_TYPE_ID", "SIGNATURE_DATE", "VALIDITY_DATE", "SIGNATORY_USER_ID", "LAST_DECISION_DATE", "TYPE_OPERATION", "TYPE_PRODUIT_CODE", "TYPE_PRODUIT_NOM", "DATE_REJET", "CODE_BUREAU", "NOM_BUREAU", "FILE_TYPE_NAME") AS 
  SELECT DISTINCT f."ID",f."CREATED_DATE",f."DESTINATAIRE",f."EMETTEUR",f."FILE_TYPE_GUCE",f."FILE_TYPE_GUCE_ANNULATION",f."FILE_TYPE_GUCE_PAIEMENT",f."NUMERO_DEMANDE",f."NUMERO_DEMANDE_ANNULATION",f."NUMERO_DEMANDE_PAIEMENT",f."NUMERO_DOSSIER",f."REFERENCE_GUCE",f."REFERENCE_GUCE_ANNULATION",f."REFERENCE_GUCE_PAIEMENT",f."REFERENCE_SIAT",f."ASSIGNED_USER_ID",f."BUREAU_ID",f."CLIENT_ID",f."COUNTRY_OF_DESTINATION",f."COUNTRY_OF_ORIGIN",f."COUNTRY_OF_PROVENANCE",f."FILE_TYPE_ID",f."SIGNATURE_DATE",f."VALIDITY_DATE",f."SIGNATORY_USER_ID",f."LAST_DECISION_DATE" , 
(SELECT ffv.VALUE FROM FILE_FIELD_VALUE ffv JOIN FILE_FIELD ff ON ff.ID = ffv.FILE_FIELD_ID WHERE ffv.FILE_ID = f.id AND ff.CODE = 'TYPE_DOSSIER_EGUCE') TYPE_OPERATION,
(SELECT ffv.VALUE FROM FILE_FIELD_VALUE ffv JOIN FILE_FIELD ff ON ff.ID = ffv.FILE_FIELD_ID WHERE ffv.FILE_ID = f.id AND ff.CODE = 'TYPE_PRODUIT_CODE') TYPE_PRODUIT_CODE,
(SELECT ffv.VALUE FROM FILE_FIELD_VALUE ffv JOIN FILE_FIELD ff ON ff.ID = ffv.FILE_FIELD_ID WHERE ffv.FILE_ID = f.id AND ff.CODE = 'TYPE_PRODUIT_NOM') TYPE_PRODUIT_NOM,
(SELECT MIN(itf.CREATED) FROM FILE_ITEM fi
    JOIN ITEM_FLOW itf ON itf.FILE_ITEM_ID = fi.ID
    JOIN FLOW flow ON flow.ID = itf.FLOW_ID
    WHERE fi.FILE_ID = f.ID AND flow.TO_STEP = 5) DATE_REJET,
    ent.CODE CODE_BUREAU, adm.LABEL_FR NOM_BUREAU,
    ft.LABEL_FR FILE_TYPE_NAME
FROM FILES f
JOIN FILE_TYPE ft ON ft.ID = f.FILE_TYPE_ID
LEFT JOIN ENTITY ent ON ent.ID = f.BUREAU_ID
LEFT JOIN ADMINISTRATION adm ON adm.ID = f.BUREAU_ID
WHERE f.FILE_TYPE_ID IN (33, 36, 37, 39);


