INSERT INTO REPORT_ORGANISM(ID, SEQUENCE, VALUE, FILE_TYPE_FLOW_REPORT, ORGANISM)
VALUES (REPORT_ORGANISME_SEQ.nextVal, 0, '/VTP/MINSANTE', 38, 90);

INSERT INTO REPORT_ORGANISM(ID, SEQUENCE, VALUE, FILE_TYPE_FLOW_REPORT, ORGANISM)
VALUES (REPORT_ORGANISME_SEQ.nextVal, 0, 'VTD/MINSANTE', 39, 90);



INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),8,'INFORMATIONS_GENERALES_PAYS_PROVENANCE_CODEPAYS','Pays de provenance (Code)','Country of origin (Code)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),8,'INFORMATIONS_GENERALES_PAYS_PROVENANCE_NOMPAYS','Pays de provenance (Libellé)','Country of origin (Label)',0,12,1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),8,'INFORMATIONS_GENERALES_PAYS_ORIGINE_CODEPAYS','Pays d''origine (Code)','Native country (Code)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),8,'INFORMATIONS_GENERALES_PAYS_ORIGINE_NOMPAYS','Pays d''origine (Libellé)','Native country (Label)',0,12,1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),8,'INFORMATIONS_GENERALES_PAYS_DESTINATION_CODEPAYS','Pays de destination (Code)','Country of destination (Code)',0,12,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),8,'INFORMATIONS_GENERALES_PAYS_DESTINATION_NOMPAYS','Pays de destination (Libellé)','Country of destination (Label)',0,12,1);

COMMIT;
