/**
 * Author:  tadzotsa
 * Created: 14 mai 2020
 */

-- SEQUENCES à mettre à jour : SIAT_CT.FILE_TYPE_SERVICE_SEQ, SIAT_CT.FIELD_GROUP_SEQ
--DROP SEQUENCE SIAT_CT.FILE_TYPE_SERVICE_SEQ;
--CREATE SEQUENCE  SIAT_CT.FILE_TYPE_SERVICE_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH (SELECT MAX(ID) + 1 FROM SIAT_CT.FILE_TYPE_SERVICE) CACHE 20 NOORDER NOCYCLE;
--DROP SEQUENCE SIAT_CT.FIELD_GROUP_SEQ;
--CREATE SEQUENCE  SIAT_CT.FIELD_GROUP_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH (SELECT MAX(ID) + 1 FROM SIAT_CT.FIELD_GROUP) CACHE 20 NOORDER NOCYCLE;

ALTER TABLE SIAT_CT.FILE_TYPE ADD CONSTRAINT FILE_TYPE_UK_CODE UNIQUE (CODE) ENABLE;

UPDATE SIAT_CT.FILE_TYPE SET LABEL_FR = 'Procès Verbal Empotage', LABEL_EN = 'Potting Report', PAYMENT_FILE_TYPE = 'FPVE' WHERE CODE = 'CCT_CT_E_PVE';
INSERT INTO SIAT_CT.FILE_TYPE (ID,CODE,LABEL_EN,LABEL_FR,PAYMENT_FILE_TYPE) VALUES (SIAT_CT.FILE_TYPE_SEQ.NEXTVAL,'CCT_CT_E_PVE','Potting Report','Procès Verbal Empotage','FPVE');
INSERT INTO SIAT_CT.FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (SIAT_CT.FILE_TYPE_SERVICE_SEQ.NEXTVAL, (SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'), 5);
INSERT INTO SIAT_CT.MINISTRY_FILE_TYPE (MINISTRY_ID,FILE_TYPE_ID,AUTOMATIC_COTATION_ALLOWED) VALUES (1,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),1);

--
INSERT INTO SIAT_CT.FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'), (SELECT ID FROM SIAT_CT.AUTHORITY WHERE ROLE = 'SUPER'));
INSERT INTO SIAT_CT.FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'), (SELECT ID FROM SIAT_CT.AUTHORITY WHERE ROLE = 'AC1'));
INSERT INTO SIAT_CT.FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'), (SELECT ID FROM SIAT_CT.AUTHORITY WHERE ROLE = 'AR'));
INSERT INTO SIAT_CT.FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'), (SELECT ID FROM SIAT_CT.AUTHORITY WHERE ROLE = 'INS'));
INSERT INTO SIAT_CT.FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'), (SELECT ID FROM SIAT_CT.AUTHORITY WHERE ROLE = 'SIGN'));
INSERT INTO SIAT_CT.FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'), (SELECT ID FROM SIAT_CT.AUTHORITY WHERE ROLE = 'IMP'));

--
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_01'),0,'Potting File Submission','Dépôt Dossier Empotage');
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_45'),0,'Potting File Submission','Dépôt Dossier Empotage');
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_46'),0,'Admissibility after Potting File Submission','Recevabilité suite Dépôt Dossier Empotage');
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_57'),0,'Invoice Validation','Validation Facture');
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_42'),0,'Payment','Encaissement');
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_47'),0,'Cotation','Cotation');
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_48'),0,'Study after appointment request for potting','Etude suite demande de RDV pour empotage');
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_04'),0,'Potting Report Validation','Validation Procès Verbal Empotage');
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_31'),0,'Potting Report Signature','Signature Procès Verbal Empotage');
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_06'),0,'Potting Report End','Fin Procès Verbal Empotage');
INSERT INTO SIAT_CT.FILE_TYPE_STEP (FILE_TYPE_ID,STEP_ID,IS_AP_DECISION,LABEL_EN,LABEL_FR) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_05'),0,'Rejection End','Fin Rejet');

--
INSERT INTO SIAT_CT.FLOW (ID,CODE,DURATION,IS_COTA,LABELEN,LABELFR,OUTGOING,FROM_STEP,TO_STEP) VALUES (SIAT_CT.FLOW_SEQ.NEXTVAL,'FL_CT_127',24,0,'Further informations request','Demande de complément d''informations',1,(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_48'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_45'));
INSERT INTO SIAT_CT.FLOW (ID,CODE,DURATION,IS_COTA,LABELEN,LABELFR,OUTGOING,FROM_STEP,TO_STEP) VALUES (SIAT_CT.FLOW_SEQ.NEXTVAL,'FL_CT_128',24,0,'Further informations','Complément d''informations',0,(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_45'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_48'));
INSERT INTO SIAT_CT.FLOW (ID,CODE,DURATION,IS_COTA,LABELEN,LABELFR,OUTGOING,FROM_STEP,TO_STEP) VALUES (SIAT_CT.FLOW_SEQ.NEXTVAL,'FL_CT_129',24,0,'Rejection','Rejet',1,(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_48'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_05'));

--
INSERT INTO SIAT_CT.DATA_TYPE (ID,FLOW_ID,LABEL,REQUIRED,TYPE) VALUES (SIAT_CT.DATA_TYPE_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_127'),'Observation',1,'inputTextarea');
INSERT INTO SIAT_CT.DATA_TYPE (ID,FLOW_ID,LABEL,REQUIRED,TYPE) VALUES (SIAT_CT.DATA_TYPE_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_129'),'Observation',1,'inputTextarea');

--
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Potting Request','Demande Empotage',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_99'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Validation without invoice','Validation sans facture',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_100'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Billing','Facturation',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_124'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Invoice Authorization','Autorisation Facture',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_121'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Back to billing','Retour à la facturation',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_125'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Payment','Encaissement',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_126'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Cotation','Cotation',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_103'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Further informations request','Demande de complément d''informations',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_127'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Appointment Confirmation','Confirmation rendez-vous',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_104'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Further informations request','Demande de complément d''informations',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_24'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Potting report for signature','Procès verbal pour signature',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_07'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Back to validation','Retour à la validation',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_76'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Potting report authorization','Autorisation Procès Verbal',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_08'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Rejection','Rejet',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_129'));

--
--UPDATE SIAT_CT.DATA_TYPE SET PROPS = 'fileTypes=CCT_CT_E,CCT_CT_E_ATP,CCT_CT_E_FSTP,CCT_CT_E_PVI' WHERE FLOW_ID = (SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_101');
-- FL_CT_104
UPDATE SIAT_CT.DATA_TYPE SET CODE = 'DATE_RDV', PROPS = 'pattern=dd/MM/yyyy HH:mm
fileTypes=CCT_CT_E_FSTP,CCT_CT_E_PVI' WHERE FLOW_ID = (SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_104');
/*INSERT INTO SIAT_CT.DATA_TYPE (ID,FLOW_ID,LABEL,LABEL_EN,REQUIRED,TYPE,CODE,PROPS) VALUES (SIAT_CT.DATA_TYPE_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_104'),'Date Rendez-vous effective','Effective Appointement Date',1,'calendar','DATE_RDV_FINALE','pattern=dd/MM/yyyy HH:mm:ss
fileTypes=CCT_CT_E_PVE');*/
/*INSERT INTO SIAT_CT.DATA_TYPE (ID,FLOW_ID,LABEL,LABEL_EN,REQUIRED,TYPE,CODE,PROPS) VALUES (SIAT_CT.DATA_TYPE_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_104'),'Date Fin Empotage','Potting End Date',1,'calendar','DATE_EMPOTAGE_EFFECTIF','pattern=dd/MM/yyyy HH:mm:ss
fileTypes=CCT_CT_E_PVE');
INSERT INTO SIAT_CT.DATA_TYPE (ID,FLOW_ID,LABEL,LABEL_EN,REQUIRED,TYPE,CODE,PROPS) VALUES (SIAT_CT.DATA_TYPE_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_104'),'Observations','Observations',1,'inputTextarea',null,'fileTypes=CCT_CT_E_PVE');
*/
-- FL_CT_118
UPDATE SIAT_CT.DATA_TYPE SET PROPS = 'pattern=dd/MM/yyyy HH:mm
fileTypes=CCT_CT_E_FSTP,CCT_CT_E_PVI' WHERE FLOW_ID = (SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_118');
/*INSERT INTO SIAT_CT.DATA_TYPE (ID,FLOW_ID,LABEL,LABEL_EN,REQUIRED,TYPE,CODE,PROPS) VALUES (SIAT_CT.DATA_TYPE_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_118'),'Date Rendez-vous effective','Effective Appointement Date',1,'calendar','DATE_RDV_FINALE','pattern=dd/MM/yyyy HH:mm:ss
fileTypes=CCT_CT_E_PVE');*/
/*INSERT INTO SIAT_CT.DATA_TYPE (ID,FLOW_ID,LABEL,LABEL_EN,REQUIRED,TYPE,CODE,PROPS) VALUES (SIAT_CT.DATA_TYPE_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_118'),'Date Fin Empotage','Potting End Date',1,'calendar','DATE_EMPOTAGE_EFFECTIF','pattern=dd/MM/yyyy HH:mm:ss
fileTypes=CCT_CT_E_PVE');*/
/*INSERT INTO SIAT_CT.DATA_TYPE (ID,FLOW_ID,LABEL,LABEL_EN,REQUIRED,TYPE,CODE,PROPS) VALUES (SIAT_CT.DATA_TYPE_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_118'),'Observations','Observations',1,'inputTextarea',null,'fileTypes=CCT_CT_E_PVE');
*/
-- FL_CT_07
/*INSERT INTO SIAT_CT.DATA_TYPE (ID,FLOW_ID,LABEL,LABEL_EN,REQUIRED,TYPE,CODE,PROPS) VALUES (SIAT_CT.DATA_TYPE_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_07'),'Numéro Autorisation','Authorization Number',1,'inputText','NUMERO_AUTORISATION','fileTypes=CCT_CT_E_PVE');
INSERT INTO SIAT_CT.DATA_TYPE (ID,FLOW_ID,LABEL,LABEL_EN,REQUIRED,TYPE,CODE,PROPS) VALUES (SIAT_CT.DATA_TYPE_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_07'),'Supervisor Opération','Supervisor',1,'inputText','SUPERVISEUR_OPERATION','fileTypes=CCT_CT_E_PVE');
INSERT INTO SIAT_CT.DATA_TYPE (ID,FLOW_ID,LABEL,LABEL_EN,REQUIRED,TYPE,CODE,PROPS) VALUES (SIAT_CT.DATA_TYPE_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_07'),'Date Autorisation','Authorization Date',0,'calendar','DATE_AUTORISATION','pattern=yyyyMMdd
fileTypes=CCT_CT_E_PVE');
INSERT INTO SIAT_CT.DATA_TYPE (ID,FLOW_ID,LABEL,LABEL_EN,REQUIRED,TYPE,CODE,PROPS) VALUES (SIAT_CT.DATA_TYPE_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_07'),'Numéro Procès Verbal','Potting Report Number',1,'inputText','PV_EMPOTAGE_NUMERO','fileTypes=CCT_CT_E_PVE');
INSERT INTO SIAT_CT.DATA_TYPE (ID,FLOW_ID,LABEL,LABEL_EN,REQUIRED,TYPE,CODE,PROPS) VALUES (SIAT_CT.DATA_TYPE_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_07'),'Numéro Attestation Traitement','Treatment Certificate Number',0,'inputText','PV_EMPOTAGE_NUMERO_AT','fileTypes=CCT_CT_E_PVE');
INSERT INTO SIAT_CT.DATA_TYPE (ID,FLOW_ID,LABEL,LABEL_EN,REQUIRED,TYPE,CODE,PROPS) VALUES (SIAT_CT.DATA_TYPE_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_07'),'Date Attestation Traitement','Treatment Certificate Date',0,'calendar','PV_EMPOTAGE_DATE_AT','pattern=yyyyMMdd
fileTypes=CCT_CT_E_PVE');*/

--
INSERT INTO SIAT_CT.FILE_TYPE_FLOW_REPORT (ID,REPORT_CLASS_NAME,REPORT_NAME,FILE_FIELD_NAME,FILE_TYPE_ID,FLOW_ID,ORGANISM_ID) VALUES (SIAT_CT.FILE_TYPE_FLOW_REPORT_SEQ.NEXTVAL, 'org.guce.siat.web.reports.exporter.CteInvoiceExporter', 'CCT_CT_E_INV.pdf','NUMERO_FACTURE', (SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'), (SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_121'), 3);
INSERT INTO SIAT_CT.FILE_TYPE_FLOW_REPORT (ID,REPORT_CLASS_NAME,REPORT_NAME,FILE_FIELD_NAME,FILE_TYPE_ID,FLOW_ID,ORGANISM_ID) VALUES (SIAT_CT.FILE_TYPE_FLOW_REPORT_SEQ.NEXTVAL, 'org.guce.siat.web.reports.exporter.CtCctPveExporter', 'CCT_CT_E_PVE.pdf','PV_EMPOTAGE_NUMERO', (SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'), (SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_08'), 3);
INSERT INTO SIAT_CT.FILE_TYPE_FLOW_REPORT (ID,REPORT_CLASS_NAME,REPORT_NAME,FILE_FIELD_NAME,FILE_TYPE_ID,FLOW_ID,ORGANISM_ID) VALUES (SIAT_CT.FILE_TYPE_FLOW_REPORT_SEQ.NEXTVAL, 'org.guce.siat.web.reports.exporter.CtCctPveExporter', 'CCT_CT_E_PVE.pdf','PV_EMPOTAGE_NUMERO', (SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'), (SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_89'), 3);

--
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'E001','FL_CT_99',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'E021',NULL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'E002','FL_CT_24',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'E002','FL_CT_127',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'E601','FL_CT_121',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'E602','FL_CT_126',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'E003','FL_CT_104',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'E023','FL_CT_118',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'E005','FL_CT_08',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'));
INSERT INTO SIAT_CT.FLOW_GUCE_SIAT (ID,FLOW_GUCE,FLOW_SIAT,FILE_TYPE_ID) VALUES (SIAT_CT.FLOW_GUCE_SIAT_SEQ.NEXTVAL,'E004','FL_CT_129',(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'));

--
UPDATE SIAT_CT.FILE_FIELD SET HIDDEN = 1 WHERE CODE = 'TYPE_PRODUIT_CODE';
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'NUMERO_FACTURE','Numéro Facture','Invoice Number',0,10,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'CODE_BUREAU','Code Bureau','Office Code',0,1,0);
INSERT INTO SIAT_CT.FIELD_GROUP (ID,LABEL_EN,LABEL_FR) VALUES (SIAT_CT.FIELD_GROUP_SEQ.NEXTVAL,'Potting Report','Procès Verbal Empotage');
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'NUMERO_AUTORISATION','Numéro Autorisation','Authorization Number',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),1);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'DATE_AUTORISATION','Date Autorisation','Authorization Date',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),1);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'SUPERVISEUR_OPERATION','Superviseur Opération','Supervisor',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),1);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'PV_EMPOTAGE_NUMERO','Numéro','Number',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),1);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'PV_EMPOTAGE_SIGNATAIRE','Signataire','Signatory',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),1);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'PV_EMPOTAGE_DATE','Date','Date',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),1);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'PV_EMPOTAGE_NUMERO_AT','Numéro Attestaion Traitement','Treatment Certificate Number',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),1);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'PV_EMPOTAGE_DATE_AT','Date Attestaion Traitement','Treatment Certificate Date',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),1);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'LIEU_DESTINATION_UNLOCODE','Code Lieu Destination','Destination Place Code',0,12,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'LIEU_DESTINATION_LIBELLE','Libellé Lieu Destination','Destination Place Label',0,12,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'LIEU_EMBARQUEMENT_UNLOCODE','Code Lieu Embarquement','Boarding Place Code',0,12,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'LIEU_EMBARQUEMENT_LIBELLE','Libellé Lieu Embarquement','Boarding Place Label',0,12,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'LIEU_DEDOUANEMENT_UNLOCODE','Code Lieu Dédouanement','Clearing Place Code',0,12,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'LIEU_DEDOUANEMENT_LIBELLE','Libellé Lieu Dédouanement','Clearing Place Label',0,12,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'NAVIRE_CODE','Code Navire','Vessel Code',0,12,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'NAVIRE_LIBELLE','Nom Navire','Vessel Name',0,12,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'MODE_TRANSPORT_CODE','Code Mode Transport','Transport Mode Code',0,12,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'MODE_TRANSPORT_LIBELLE','Libellé Mode Transport','Transport Mode Name',0,12,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE,HIDDEN) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'TYPE_PRODUIT_CODE','Code Type Produit','Product Type Code',0,1,0,1);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'TYPE_PRODUIT_NOM','Libellé Type Produit','Product Type Label',0,1,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE,HIDDEN) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'TYPE_PRODUIT_DETAIL','Détail','Detail',0,1,0,1);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE)
SELECT SIAT_CT.FILE_FIELD_SEQ.NEXTVAL ID,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE') FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,0 UPDATABLE FROM SIAT_CT.FILE_FIELD WHERE FILE_TYPE_ID = 33 AND CODE LIKE 'TRANSITAIRE_%';
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE)
SELECT SIAT_CT.FILE_FIELD_SEQ.NEXTVAL ID,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE') FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,0 UPDATABLE FROM SIAT_CT.FILE_FIELD WHERE FILE_TYPE_ID = 33 AND CODE LIKE 'SIGNATAIRE_%';
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE)
SELECT SIAT_CT.FILE_FIELD_SEQ.NEXTVAL ID,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE') FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,0 UPDATABLE FROM SIAT_CT.FILE_FIELD WHERE FILE_TYPE_ID = 33 AND CODE LIKE 'DESTINATAIRE_%';
INSERT INTO SIAT_CT.FIELD_GROUP (ID,LABEL_EN,LABEL_FR) VALUES (SIAT_CT.FIELD_GROUP_SEQ.NEXTVAL,'Potting','Empotage');
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'DATE_SIGNATURE_RAPPORT','Date Signature Rapport','Report Signature Date',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'DATE_RDV_FINALE','Date Rendez-vous finale','FInal Appointment Date',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'DATE_RDV_PROPOSEE','Date Rendez-vous proposée','Proposed appointment date',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'DATE_EMPOTAGE_EFFECTIF','Date Fin Empotage','Potting End Date',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),0);
--INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'SUPERVISEUR_OPERATION','Superviseur Empotage','Potting Operation Supervisor',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE,HIDDEN) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'ADMINISTRATION_TECHNIQUE_CODE','Code Administration Technique','Technical Administration Code',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),0,1);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'ADMINISTRATION_TECHNIQUE_NOM','Administration Technique','Technical Administration',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE,HIDDEN) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'SITE_EMPOTAGE_CODE','Code Site Empotage','Potting Site Code',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),0,1);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'SITE_EMPOTAGE_NOM','Site Empotage','Potting Site',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'SITE_EMPOTAGE_VILLE','Ville Site Empotage','Potting Site Town',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'SITE_EMPOTAGE_CODE_REGION','Code Région Site Empotage','Potting Site Region Code',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'SITE_EMPOTAGE_NOM_REGION','Nom Région Site Empotage','Potting Site Region Name',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE,HIDDEN) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'POSTE_CONTROLE_CODE','Code Poste Contrôle','Control Post Code',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),0,1);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'POSTE_CONTROLE_NOM','Poste Contrôle','Control Post',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'POSTE_CONTROLE_DELEGATION','Délégation Poste Contrôle','Control Post Délégation',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'POSTE_CONTROLE_CODE_REGION','Code Région Poste Contrôle','Control Post Region Code',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'POSTE_CONTROLE_NOM_REGION','Nom Région Poste Contrôle','Control Post Region Name',0,(SELECT MAX(ID) FROM SIAT_CT.FIELD_GROUP),0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'CEMAC','Produit CEMAC','CEMAC Product',0,1,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'DEBITES','Débités','Débités',0,1,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'PLACAGE','Placage','Placage',0,1,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'CONTRE_PLAQUE','Contre Plaque','Contre Plaque',0,1,0);