/**
 * Author:  ht
 * Created: 16 juil. 2020
 */

--
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),'TYPE_DOSSIER_EGUCE','Type de dossier e-GUCE','e-GUCE file type',0,1,0);

/*

-- BIEN VOULOIR LA REQUETE CI-DESSOUS (SOUS L'INSTANCE DE WEBGUCE) ET EXECUTER LES RESULTATS SOUS L'INSTANCE DE SIAT

SELECT 'INSERT INTO SIAT_CT.FILE_FIELD_VALUE (FILE_FIELD_ID,FILE_ID,VALUE) VALUES ('||FF.ID||','||F.ID||','''||EXPRED.FILE_TYPE||''');' FROM WEBGUCE.EMP_REGISTRATION EMP
JOIN WEBGUCE.CORE_RECORD R ON R.RECORD_ID = EMP.RECORD_ID
JOIN WEBGUCE.CORE_RECORD REPC ON REPC.RECORD_ID = R.RECORD_PARENT
JOIN WEBGUCE.CORE_RECORD REXP ON REXP.RECORD_ID = REPC.RECORD_PARENT
JOIN WEBGUCE.CORE_RECORD REXPRED ON REXPRED.RECORD_ID = REXP.RECORD_PARENT
JOIN WEBGUCE.EXPRED_REGISTRATION EXPRED ON EXPRED.RECORD_ID = REXPRED.RECORD_ID
JOIN SIAT_CT.FILES@SIAT_DBLINK F ON F.NUMERO_DOSSIER = EMP.RECORD_ID
JOIN SIAT_CT.FILE_FIELD@SIAT_DBLINK FF ON FF.FILE_TYPE_ID = F.FILE_TYPE_ID AND FF.CODE = 'TYPE_DOSSIER_EGUCE';

*/
