/**
 * Author:  ht
 * Created: 10-Nov-2020
 */

-- CCT_CT_E_FSTP
-- ST_CT_45
UPDATE SIAT_CT.FILE_TYPE_STEP FTS SET FTS.LABEL_EN = 'File deposit', FTS.LABEL_FR = 'Dépôt dossier' WHERE FTS.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E_FSTP') AND FTS.STEP_ID = (SELECT S.ID FROM SIAT_CT.STEP S WHERE S.CODE = 'ST_CT_45');
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (FILE_TYPE_ID,FLOW_ID,LABEL_FR,LABEL_EN) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_99'),'Treatment supervision request','Demande de supervision de traitement');

-- ST_CT_46
UPDATE SIAT_CT.FILE_TYPE_STEP FTS SET FTS.LABEL_EN = 'Admissibility', FTS.LABEL_FR = 'Recevabilité' WHERE FTS.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E_FSTP') AND FTS.STEP_ID = (SELECT S.ID FROM SIAT_CT.STEP S WHERE S.CODE = 'ST_CT_46');
-- FL_CT_100
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'File Admission', FTF.LABEL_FR = 'Admission dossier' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E_FSTP') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_100');
-- FL_CT_101
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'Further information request', FTF.LABEL_FR = 'Demande de complément d''information' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E_FSTP') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_101');
-- FL_CT_102
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'Rejection', FTF.LABEL_FR = 'Rejet' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E_FSTP') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_102');

-- ST_CT_48
UPDATE SIAT_CT.FILE_TYPE_STEP FTS SET FTS.LABEL_EN = 'Appointment request study', FTS.LABEL_FR = 'Etude demande de rendez-vous' WHERE FTS.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E_FSTP') AND FTS.STEP_ID = (SELECT S.ID FROM SIAT_CT.STEP S WHERE S.CODE = 'ST_CT_48');
-- FL_CT_104
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'Appointment validation', FTF.LABEL_FR = 'Validation rendez-vous' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E_FSTP') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_104');
-- FL_CT_127
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'Further information request', FTF.LABEL_FR = 'Demande de complément d''information' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E_FSTP') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_127');
-- FL_CT_129
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'Rejection', FTF.LABEL_FR = 'Rejet' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E_FSTP') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_129');

-- ST_CT_04
-- FL_CT_07
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'Validation after study', FTF.LABEL_FR = 'Validation suite étude' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E_FSTP') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_07');
-- NEW FLOWS FOR FURTHER INFORMATION REQUEST : FL_CT_155 & FL_CT_156
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (FILE_TYPE_ID,FLOW_ID,LABEL_FR,LABEL_EN) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_155'),'Further information request','Demande de complément d''information');
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (FILE_TYPE_ID,FLOW_ID,LABEL_FR,LABEL_EN) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_156'),'Further information','Complément d''information');
DELETE FROM SIAT_CT.FILE_TYPE_FLOW WHERE FILE_TYPE_ID = (SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP') AND FLOW_ID = (SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_24');

-- ST_CT_31
UPDATE SIAT_CT.FILE_TYPE_STEP FTS SET FTS.LABEL_EN = 'Signature', FTS.LABEL_FR = 'Signature' WHERE FTS.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E_FSTP') AND FTS.STEP_ID = (SELECT S.ID FROM SIAT_CT.STEP S WHERE S.CODE = 'ST_CT_31');
-- FL_CT_08
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'Supervision file Authorization', FTF.LABEL_FR = 'Autorisation fiche de supervision' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E_FSTP') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_08');
-- FL_CT_76
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'Return for further study', FTF.LABEL_FR = 'Retour pour ré-étude' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E_FSTP') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_76');
