/**
 * Author:  ht
 * Created: 10-Nov-2020
 */

-- CCT_CT_E_ATP
-- ST_CT_01
UPDATE SIAT_CT.FILE_TYPE_STEP FTS SET FTS.LABEL_EN = 'File deposit', FTS.LABEL_FR = 'Dépôt dossier' WHERE FTS.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E_ATP') AND FTS.STEP_ID = (SELECT S.ID FROM SIAT_CT.STEP S WHERE S.CODE = 'ST_CT_01');
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (FILE_TYPE_ID,FLOW_ID,LABEL_FR,LABEL_EN) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_ATP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_01'),'Treatment certificate request','Demande d''attestation de traitement');

-- ST_CT_02
UPDATE SIAT_CT.FILE_TYPE_STEP FTS SET FTS.LABEL_EN = 'Admissibility', FTS.LABEL_FR = 'Recevabilité' WHERE FTS.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E_ATP') AND FTS.STEP_ID = (SELECT S.ID FROM SIAT_CT.STEP S WHERE S.CODE = 'ST_CT_02');
-- FL_CT_05
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'File Admission', FTF.LABEL_FR = 'Admission dossier' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E_ATP') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_05');
-- FL_CT_02
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'Further information request', FTF.LABEL_FR = 'Demande de complément d''information' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E_ATP') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_02');
-- FL_CT_04
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (FILE_TYPE_ID,FLOW_ID,LABEL_FR,LABEL_EN) VALUES ((SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_ATP'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_04'),'Rejection','Rejet');

-- ST_CT_04
-- FL_CT_07
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'Validation after study', FTF.LABEL_FR = 'Validation suite étude' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E_ATP') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_07');

-- ST_CT_31
UPDATE SIAT_CT.FILE_TYPE_STEP FTS SET FTS.LABEL_EN = 'Signature', FTS.LABEL_FR = 'Signature' WHERE FTS.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E_ATP') AND FTS.STEP_ID = (SELECT S.ID FROM SIAT_CT.STEP S WHERE S.CODE = 'ST_CT_31');
-- FL_CT_08
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'Supervision file Authorization', FTF.LABEL_FR = 'Autorisation fiche de supervision' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E_ATP') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_08');
-- FL_CT_76
UPDATE SIAT_CT.FILE_TYPE_FLOW FTF SET FTF.LABEL_EN = 'Return for further study', FTF.LABEL_FR = 'Retour pour ré-étude' WHERE FTF.FILE_TYPE_ID = (SELECT FT.ID FROM SIAT_CT.FILE_TYPE FT WHERE FT.CODE = 'CCT_CT_E_ATP') AND FTF.FLOW_ID = (SELECT F.ID FROM SIAT_CT.FLOW F WHERE F.CODE = 'FL_CT_76');
