INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_ITEM_FIELD),9,'AMM','Amm','Amm',1,1,0);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),9,'NUMERO_DI','Numéro DI','DI number',0,1,1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),9,'NUMERO_VTP','Numéro VTP','VTP number',0,1,1);

COMMIT;
