/**
 * Author:  ht
 * Created: 29 sept. 2020
 */
-- THE OLD TO STEP FOR FL_CT_130 IS ST_CT_59
UPDATE SIAT_CT.FLOW SET TO_STEP = (SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_62') WHERE CODE = 'FL_CT_130';
-- ADD NEW FLOW FL_CT_149
INSERT INTO SIAT_CT.FLOW (ID,CODE,DURATION,IS_COTA,LABELEN,LABELFR,OUTGOING,FROM_STEP,TO_STEP) VALUES (SIAT_CT.FLOW_SEQ.NEXTVAL,'FL_CT_149',24,0,'Potting Request','Demande Empotage',0,(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_45'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_47'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ((SELECT LABELEN FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_149'),(SELECT LABELFR FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_149'),(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_149'));
-- THE OLD FLOW SIAT FOR E001 IS FL_CT_99
UPDATE SIAT_CT.FLOW_GUCE_SIAT SET FLOW_SIAT = 'FL_CT_149' WHERE FILE_TYPE_ID = (SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE') AND FLOW_GUCE = 'E001';
-- ADD NEW FLOW FL_CT_150
INSERT INTO SIAT_CT.FLOW (ID,CODE,DURATION,IS_COTA,LABELEN,LABELFR,OUTGOING,FROM_STEP,TO_STEP) VALUES (SIAT_CT.FLOW_SEQ.NEXTVAL,'FL_CT_150',24,0,'Potting Modification Request','Demande Modification Empotage',0,(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_51'),(SELECT ID FROM SIAT_CT.STEP WHERE CODE = 'ST_CT_53'));
INSERT INTO SIAT_CT.FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ((SELECT LABELEN FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_150'),(SELECT LABELFR FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_150'),(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE'),(SELECT ID FROM SIAT_CT.FLOW WHERE CODE = 'FL_CT_150'));
-- THE OLD FLOW SIAT FOR E009 AND E030 IS FL_CT_110
UPDATE SIAT_CT.FLOW_GUCE_SIAT SET FLOW_SIAT = 'FL_CT_150' WHERE FILE_TYPE_ID = (SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVE') AND FLOW_GUCE IN ('E009','E030');
