INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_CT_118', 24, 0, 'Renouvellement RDV', 'Renouvellement RDV', 1, null, 4);

INSERT INTO FILE_TYPE_FLOW (LABEL_EN, LABEL_FR, FILE_TYPE_ID, FLOW_ID) VALUES ('Renouvellement RDV pour traitement', 'Renouvellement RDV pour traitement', 39, (SELECT MAX(ID) FROM FLOW WHERE CODE='FL_CT_118'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN, LABEL_FR, FILE_TYPE_ID, FLOW_ID) VALUES ('Renouvellement RDV pour inspection', 'Renouvellement RDV pour inspection', 36, (SELECT MAX(ID) FROM FLOW WHERE CODE='FL_CT_118'));


INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, LABEL_EN, REQUIRED, TYPE, PROPS) VALUES ((SELECT MAX(ID) + 1 FROM DATA_TYPE), (SELECT ID FROM FLOW WHERE CODE = 'FL_CT_118'), 'Date de rendez-vous', 'Appointment date',  1, 'calendar', 'pattern=dd/MM/yyyy HH:mm');
INSERT INTO FLOW_GUCE_SIAT (ID, FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES ((SELECT MAX(ID) + 1 FROM FLOW_GUCE_SIAT), 'CTE115', 'FL_CT_118', 36);
INSERT INTO FLOW_GUCE_SIAT (ID, FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES ((SELECT MAX(ID) + 1 FROM FLOW_GUCE_SIAT), 'CTE315', 'FL_CT_118', 39);


INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES ((SELECT MAX(ID) + 1 FROM FLOW), 'FL_CT_119', 24, 0, 'Inspection physique', 'Inspection physique', 1, null, 4);
INSERT INTO FILE_TYPE_FLOW (LABEL_EN, LABEL_FR, FILE_TYPE_ID, FLOW_ID) VALUES ('Inspection physique', 'Inspection physique', 33, (SELECT MAX(ID) FROM FLOW WHERE CODE='FL_CT_119'));
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, LABEL_EN, REQUIRED, TYPE, PROPS) VALUES ((SELECT MAX(ID) + 1 FROM DATA_TYPE), (SELECT ID FROM FLOW WHERE CODE = 'FL_CT_119'), 'Date de rendez-vous', 'Appointment date',  1, 'calendar', 'pattern=dd/MM/yyyy HH:mm');
INSERT INTO FLOW_GUCE_SIAT (ID, FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES ((SELECT MAX(ID) + 1 FROM FLOW_GUCE_SIAT), 'CTE015', 'FL_CT_119', 33);