UPDATE SIAT_CT.MINISTRY m SET m.CODE = 'MINSANTE' WHERE m.ID = 75;
/*========================= Ajout de la proc�dure Certificat de contr�le MINSANTE =============================*/
INSERT INTO FILE_TYPE (ID, CODE, LABEL_EN, LABEL_FR) VALUES (FILE_TYPE_SEQ.nextVal,'CCS_MINSANTE', 'Certificat de contr�le sanitaire MINSANTE', 'Certificat de contr�le MINSANTE');
/*========================= Affecter la proc�dure CCS_MINSANTE au Minist�re MINSANTE ===================*/
INSERT INTO MINISTRY_FILE_TYPE (MINISTRY_ID, FILE_TYPE_ID) VALUES ((SELECT m.ID FROM SIAT_CT.MINISTRY m WHERE m.CODE='MINSANTE'), (SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'));
/*========================  Affecter la proc�dure CCS_MINSANTE � un service =========================================*/
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (FILE_TYPE_SERVICE_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),(SELECT ser.ID FROM SIAT_CT.SERVICE ser WHERE ser.ABREVIATION='SCCT-Minsante'));
/*========================= D�finir les r�les qui ont acc�s � la proc�dure ================================*/
INSERT INTO FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'), (SELECT auth.ID FROM SIAT_CT.AUTHORITY auth WHERE auth.ROLE = 'SUPER'));
INSERT INTO FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'), (SELECT auth.ID FROM SIAT_CT.AUTHORITY auth WHERE auth.ROLE = 'AR'));
INSERT INTO FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'), (SELECT auth.ID FROM SIAT_CT.AUTHORITY auth WHERE auth.ROLE = 'AC1'));
INSERT INTO FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'), (SELECT auth.ID FROM SIAT_CT.AUTHORITY auth WHERE auth.ROLE = 'INS'));
INSERT INTO FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'), (SELECT auth.ID FROM SIAT_CT.AUTHORITY auth WHERE auth.ROLE = 'CA'));
INSERT INTO FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'), (SELECT auth.ID FROM SIAT_CT.AUTHORITY auth WHERE auth.ROLE = 'SIGN'));
/*======================== D�finir les �tapes de la proc�dure, si elles n'existent pas il faut les cr�er, ensuite affecter � ces �tapes les r�les qui ont acc�s � ces derni�res et enfin affecter ces �tapes � la
proc�dure CCS_MINSANTE =========================================*/

---- 1- ST_CT_01 (D�p�t des certificat de contr�le sanitaire). Elle existe d�j�. -----------------------
---- 2- ST_CT_02 (Recevabilit�). Elle existe d�j�. -----------------------------------
---- 3- ST_CT_03 (Cotation). Elle existe d�j�. ----------------------------------------
---- 4- ST_CT_04 (Etude approfondie). Elle existe d�j�. ------------------------------
---- 5- ST_CT_42 (Paiement). Elle existe d�j�. ------------------------------
---- 6- ST_CT_54 (Signature du certificat de contr�le sanitaire). Elle existe d�j�. --------------------
---- 7- ST_CT_05 (Rejet de la demande de certificat de contr�le sanitaire). Elle existe d�j�. ----------
---- 8- ST_CT_06 (Autorisation du certificat de contr�le sanitaire). Elle existe d�j�. ----------------

------------ Les r�les n�cessaires ont d�j� �t� affect�es � ces diff�rentes �tapes --------------------------

------------ Affecter ces �tapes � la proc�dure CCS_MINSANTE ----------------------------------------------
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_CT_DECISION, LABEL_EN, LABEL_FR) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_CT_01'), 0, 'Folder filing for a Control Certificate', 'D�p�t de dossier du Certificat de contr�le');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_CT_DECISION, LABEL_EN, LABEL_FR) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_CT_05'), 0, 'Reject a Control Certificate file', 'Rejet de dossier de Certificat de contr�le');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_CT_DECISION, LABEL_EN, LABEL_FR) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_CT_06'), 0, 'Validation of the Control Certificate', 'Validation de Certificat de contr�le');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_CT_DECISION, LABEL_EN, LABEL_FR) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_CT_02'), 0, 'Admissibility of a Control Certificate', 'Recevabilit� de Certificat de contr�le');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_CT_DECISION, LABEL_EN, LABEL_FR) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_CT_03'), 0, 'Quotation step', 'Etape de cotation');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_CT_DECISION, LABEL_EN, LABEL_FR) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_CT_04'), 0, 'Depth study of the file step', 'Etape d''�tude approfondie du dossier');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_CT_DECISION, LABEL_EN, LABEL_FR) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_CT_42'), 0, 'Certificat Fees Payment', 'Paiement des frais du certficat');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_CT_DECISION, LABEL_EN, LABEL_FR) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_CT_31'), 0, 'Signature of the of Health Control Certificate', 'Signature du Certificat de contr�le sanitaire');

/*======================== D�finir les d�cisions de la proc�dure, si elles n'existent pas il faut les cr�er et enfin affecter ces d�cisions � la
proc�dure CCS_MINSANTE =========================================*/


---- Cr�ation d'un nouveau flow pour retourner un dossier de l'�tape d'�tude approfondie � une �tape de cotation --------------
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES (FLOW_SEQ.nextVal, 'FL_CT_157',24, 0,'Validation of the Control Certificate for Depth study', 'Validation du certificat pour �tude approfondie', 0, (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_CT_02'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_CT_04'));

---- Cr�ation d'un nouveau flow de facturation pour passer de l'�tape d'�tude approfondie � l'�tape de paiement --------------
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES (FLOW_SEQ.nextVal, 'FL_CT_158',24, 0,'Facturation des frais du certificat', 'Facturation des frais du certificat', 1, (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_CT_04'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_CT_42'));

------ Cr�ation des COPY_RECIPIENTS pour le FLOW FL_CT_158 ----------------------
NSERT INTO COPY_RECIPIENT (ID, FLOW_ID, TO_AUTHORITY_ID) VALUES (COPY_RECIPIENT_SEQ.nextVal, (SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_CT_158'), (SELECT auth.ID FROM SIAT_CT.AUTHORITY auth WHERE auth.ROLE = 'CON'));


---- Cr�ation d'un nouveau flow d'encaissement pour passer de l'�tape de paiement pour passer � l'�tape de signature --------------
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES (FLOW_SEQ.nextVal, 'FL_CT_160',24, 0,'Encaissement', 'Encaissement', 1, (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_CT_42'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_CT_04'));

---- Ajout des champs � renseigner lors de la prise de cette d�cision ----------------

INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_CT_158'), 'Observation',  0, 'inputTextarea' );

INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_CT_160'), 'Observation',  0, 'inputTextarea' );

INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_CT_08'), 'Num�ro du CCS',  1, 'inputText' );

---- 1- ST_CT_01 (D�p�t des certificat de contr�le sanitaire). Elle existe d�j�. -----------------------
    ----- 1- FL_CT_01 (Certificat de contr�le du MINSANTE)
---- 2- ST_CT_02 (Recevabilit�). Elle existe d�j�. -----------------------------------
    ----- 1- FL_CT_02 (Compl�ment d'information suite recevabilit�) ------------------
    ----- 2- FL_CT_04 (Rejet du Certificat de contr�le suite recevabilit�) -------------------
    ----- 3- FL_CT_05 (Validation du Certificat de contr�le pour cotation) -------------------
	----- 4- FL_CT_157 (Validation du certificat pour �tude approfondie) --------------------------------
---- 3- ST_CT_03 (Cotation). Elle existe d�j�. ----------------------------------------
    ----- 1- FL_CT_06 (Cotation pour �tude) ------------------------------------------
---- 4- ST_CT_04 (Etude approfondie). Elle existe d�j�. -------------------------------------
    ----- 1- FL_CT_91 (Rejet Certificat de contr�le suite �tude ------------------------------
    ----- 2- FL_CT_07 (Acception Certificat de contr�le suite �tude) ------------------------ 
    ----- 3- FL_CT_24 (Compl�ment d'information suite �tude) ------------------------
	----- 4- FL_CT_158 (Facturation) --------------------------------
---- 5- ST_CT_42 (Paiement). Elle existe d�j�. --------------------
    ---- 1- FL_CT_160 (Encaissement) ----------------------------------
---- 6- ST_CT_31 (Signature du certificat de contr�le sanitaire). Elle existe d�j�. --------------------
    ---- 1- FL_CT_08 (Autorisation Certificat de contr�le) ----------------------------------
    ---- 2- FL_CT_76 (Refus Signature - Retour vers �tude approfondie ---------------
---- 7- ST_CT_05 (Fin Rejet de la demande de certificat de contr�le sanitaire). Elle existe d�j�. ----------
---- 8- ST_CT_06 (Fin signature du certificat de contr�le sanitaire). Elle existe d�j�. ----------------

---- 1- ST_CT_01 (D�p�t des certificat de contr�le sanitaire). Elle existe d�j�. -----------------------
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Request for Sanitary Control Certificate','Demande de Certificat de contr�le sanitaire',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),(SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_CT_01'));
---- 2- ST_CT_02 (Recevabilit�). Elle existe d�j�. -----------------------------------
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Additional information for the Control Certificate','Compl�ment d''information de Certificat de contr�le',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),(SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_CT_02'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Rejection of Control Certificate','Rejet de Certificat de contr�le',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),(SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_CT_04'));
---- INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Validation of the Control Certificate for Quotation','Validation de Certificat de contr�le pour cotation',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),(SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_CT_05'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Validation of Certificate for Depth study','Validation du certificat pour �tude approfondie',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),(SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_CT_157'));
---- 3- ST_CT_03 (Cotation). Elle exite d�j�. ----------------------------------------
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Cancel Quotation','Annulation de la cotation',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),(SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_CT_06'));
---- 4- ST_CT_04 (Etude approfondie). Elle existe d�j�. -------------------------------------
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Rejection of the Control Certificate','Rejet suite de Certificat de contr�le ',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),(SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_CT_91'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Validate request for signature','Validation de la demande pour signature',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),(SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_CT_07'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Additional information for the Control Certificate','Compl�ment d''information de Certificat de contr�le',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),(SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_CT_24'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Billing certificate Fees','Facturation des frais du certificat',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),(SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_CT_158'));
---- 5- ST_CT_64 (Paiement). Elle existe d�j�. -------------------------------------
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Encaissement des frais du certificat','Encaissement des frais du certficat',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),(SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_CT_160'));

---- 6- ST_CT_54 (Signature du certificat de contr�le sanitaire). Elle existe d�j�. --------------------
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Decision Refusal - Back to treatment of the Control Certificate','Refus D�cision - Retour vers �tude de  Certificat de contr�le',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),(SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_CT_76'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Validation of the Control Certificate','Validation du certificat de contr�le',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),(SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_CT_08'));

/*========================  D�finir les infirmations n�cessaires pour l'impression des livrable de la proc�dure CCS_MINSANTE =========================================*/
INSERT INTO FILE_TYPE_FLOW_REPORT(ID, REPORT_CLASS_NAME, REPORT_NAME, FILE_FIELD_NAME, FILE_TYPE_ID, FLOW_ID, ORGANISM_ID) VALUES (FILE_TYPE_FLOW_REPORT_SEQ.nextVal, 'org.guce.siat.web.reports.exporter.CcsMinsanteFormExporter', 'CCS_MINSANTE.pdf','NUMERO_CCS_MINSANTE', (SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'), (SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_CT_08'), (SELECT org.ID FROM SIAT_CT.ORGANISM org WHERE org.ABREVIATION = 'D-CCT-Minsante'));

/*========================  D�finir les correspondances entre les flows SIAT et les flux entrants et sortants de orchestra pour la proc�dure CCS_MINSANTE =========================================*/
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (FLOW_GUCE_SIAT_SEQ.nextVal,'CCS001','FL_CT_01',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'));
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (FLOW_GUCE_SIAT_SEQ.nextVal,'CCS002','FL_CT_02',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'));
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (FLOW_GUCE_SIAT_SEQ.nextVal,'CCS002','FL_CT_24',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'));
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (FLOW_GUCE_SIAT_SEQ.nextVal,'CCS003','FL_CT_04',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'));
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (FLOW_GUCE_SIAT_SEQ.nextVal,'CCS003','FL_CT_91',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'));
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (FLOW_GUCE_SIAT_SEQ.nextVal,'CCS004','FL_CT_08',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'));
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (FLOW_GUCE_SIAT_SEQ.nextVal,'CCS601','FL_CT_158',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'));
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (FLOW_GUCE_SIAT_SEQ.nextVal,'CCS602','FL_CT_160',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'));
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (FLOW_GUCE_SIAT_SEQ.nextVal,'CCS011',NULL,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'));

/*========================  D�finir la correspondances entre les informations pour la g�n�ration du certificat de contr�le sanitaire et  =========================================*/
INSERT INTO REPORT_ORGANISM( ID,  SEQUENCE,  VALUE, FILE_TYPE_FLOW_REPORT, ORGANISM)VALUES( REPORT_ORGANISME_SEQ.nextVal,  0,  '/MINSANTE/D-CCT-Minsante/SDCCT-Minsante/',  (SELECT ftfr.ID FROM SIAT_CT.FILE_TYPE_FLOW_REPORT ftfr WHERE ftfr.FILE_FIELD_NAME ='NUMERO_CCS_MINSANTE'),  (SELECT org.ID FROM SIAT_CT.ORGANISM org WHERE org.ABREVIATION='D-CCT-Minsante'));

/*======================== D�finir les champs suppl�mentaires des dossiers pour la proc�dure CCS_MINSANTE =========================================*/
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'CODE_BUREAU','Code Bureau','Office Code',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'General'),1);


---------------------------------- EXPORTATEUR --------------
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'EXPORTATEUR_RAISONSOCIALE','Raison Sociale','Name/Business Name',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'EXPORTATEUR_Sigle','Sigle','Acronym',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'EXPORTATEUR_ADRESSE_ADRESSE1','Adresse (Adresse 1)','Address (Address 1)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'EXPORTATEUR_ADRESSE_ADRESSE2','Adresse (Adresse 2)','Address (Address 2)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'EXPORTATEUR_ADRESSE_BP','Adresse (BP)','Address (P.O. Box)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'EXPORTATEUR_ADRESSE_PAYSADDRESS_CODEPAYS','Adresse Pays (Code Pays)','Address Country (Country Code)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'EXPORTATEUR_ADRESSE_PAYSADDRESS_NOMPAYS','Adresse Pays (Nom Pays)','Address Country (Country Name)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'EXPORTATEUR_ADRESSE_VILLE','Adresse (Ville)','Address (City)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'EXPORTATEUR_ADRESSE_ADRESSEELECTRONIQUE','Adresse (Adresse �lectronique)','Address (e-mail Address)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'EXPORTATEUR_ADRESSE_SITEWEB','Adresse (Site Web)','Address (Web Site)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'EXPORTATEUR_TELEPHONE_FIXE_INDICATIFPAYS','T�l�phone Fixe (Indicatif Pays)','Telephone (Country Dialing Code)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'EXPORTATEUR_TELEPHONE_FIXE_NUMERO','T�l�phone Fixe (Num�ro)','Telephone (Number)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'EXPORTATEUR_TELEPHONE_MOBILE_INDICATIFPAYS','T�l�phone Mobile (Indicatif Pays)','Mobile Phone (Country Dialing Code)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'EXPORTATEUR_TELEPHONE_MOBILE_NUMERO','T�l�phone Mobile (Num�ro)','Mobile Phone (Number)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'EXPORTATEUR_FAX_INDICATIFPAYS','Fax (Indicatif Pays)','Fax (Country Dialing Code)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'EXPORTATEUR_FAX_NUMERO','Fax (Num�ro)','Fax (Number)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);


---------------------------------- TRANSITAIRE --------------

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSITAIRE_RAISONSOCIALE','Raison Sociale','Name/Business Name',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSITAIRE_Sigle','Sigle','Acronym',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSITAIRE_ADRESSE_ADRESSE1','Adresse (Adresse 1)','Address (Address 1)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSITAIRE_ADRESSE_ADRESSE2','Adresse (Adresse 2)','Address (Address 2)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSITAIRE_ADRESSE_BP','Adresse (BP)','Address (P.O. Box)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSITAIRE_ADRESSE_PAYSADDRESS_CODEPAYS','Adresse Pays (Code Pays)','Address Country (Country Code)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSITAIRE_ADRESSE_PAYSADDRESS_NOMPAYS','Adresse Pays (Nom Pays)','Address Country (Country Name)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSITAIRE_ADRESSE_VILLE','Adresse (Ville)','Address (City)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSITAIRE_ADRESSE_ADRESSEELECTRONIQUE','Adresse (Adresse �lectronique)','Address (e-mail Address)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSITAIRE_ADRESSE_SITEWEB','Adresse (Site Web)','Address (Web Site)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSITAIRE_TELEPHONE_FIXE_INDICATIFPAYS','T�l�phone Fixe (Indicatif Pays)','Telephone (Country Dialing Code)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSITAIRE_TELEPHONE_FIXE_NUMERO','T�l�phone Fixe (Num�ro)','Telephone (Number)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSITAIRE_TELEPHONE_MOBILE_INDICATIFPAYS','T�l�phone Mobile (Indicatif Pays)','Mobile Phone (Country Dialing Code)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSITAIRE_TELEPHONE_MOBILE_NUMERO','T�l�phone Mobile (Num�ro)','Mobile Phone (Number)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSITAIRE_FAX_INDICATIFPAYS','Fax (Indicatif Pays)','Fax (Country Dialing Code)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSITAIRE_FAX_NUMERO','Fax (Num�ro)','Fax (Number)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);


---------------------------------- FACTURE --------------
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'FACTURE_NUMERO_FACTURE','Num�ro facture','Bill number',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Bill'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'FACTURE_DATE_FACTURE','Date de la facture','Bill Date',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Bill'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'FACTURE_MONTANT_FACTURE','Montant Facture','Bill Amount',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Bill'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'FACTURE_DEVISE_FACTURE_CODE','Code Devise','Currency Code',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Bill'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'FACTURE_DEVISE_FACTURE_LIBELLE','Libell� Devise','Currency Label',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Bill'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'FACTURE_MONTANT_CFA_FACTURE','Montant FCFA','XAF Amount',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Bill'),1);

---------------------------------- TRANSPORT --------------
 ------------------FIELD_GROUP-----------------------------
INSERT INTO SIAT_CT.FIELD_GROUP (ID,LABEL_EN,LABEL_FR) VALUES (SIAT_CT.FIELD_GROUP_SEQ.NEXTVAL,'Transport','Transport');

------------------FILE_FIELD-------------------------------

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSPORT_MOYEN_TRANSPORT_CODE','Code Moyen Transport','Transport Way Code',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Transport'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSPORT_MOYEN_TRANSPORT_LIBELLE','Libell� Moyen Transport','Transport Way Label',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Transport'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSPORT_MOYEN_TRANSPORT_IMMO','Code IMMO','IMMO Code',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Transport'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSPORT_MOYEN_TRANSPORT_MMSC','Code MMSC','MMSC Code',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Transport'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSPORT_MODE_TRANSPORT_CODE','Code Mode Transport','Transport Mode Code',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Transport'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSPORT_MODE_TRANSPORT_LIBELLE','Libell� MOde Transport','Transport Mode Label',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Transport'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSPORT_NUMERO_BL','Numero BL','BL Number',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Transport'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSPORT_LIEU_DEDOUANEMENT_UNLOCODE','Code Lieu Dedouanement','Discharging Place Code',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Transport'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSPORT_LIEU_DEDOUANEMENT_LIBELLE','Libell� Lieu D�douanement','Dischargin Place Label',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Transport'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSPORT_PAYS_ORIGINE_CODE_PAYS','Pays Origine (Code)','Origin Country (Code)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Transport'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSPORT_PAYS_ORIGINE_NOM_PAYS','Pays Origine (Nom)','Origin Country (Code)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Transport'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSPORT_PAYS_PROVENANCE_CODE_PAYS','Pays Provenance (Code)','Country Of origin (Code)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Transport'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSPORT_PAYS_PROVENANCE_NOM_PAYS','Pays Provenance (Nom)','Country of Origin (Name)',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Transport'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSPORT_NB_CONTENEUR20','Nombre conteneur 20','Number of container 20',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Transport'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'TRANSPORT_NB_CONTENEUR40','Nombre conteneur 40','Number of container 40',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Transport'),1);


------GENERAL ----------------------------------------------------
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'NUMERO_CCS_MINSANTE','Num�ro Certificat','Certificat number',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'General'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'CCS_MINSANTE_DATE','Date de signature','Signature date',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'General'),1);
------SIGNATAIRE ----------------------------------------------------
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'SIGNATAIRE_NOM','Nom Signataire','Signatory Name',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Signatory'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'SIGNATAIRE_QUALITE','Qualit� Signataire','Signatory Function',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Signatory'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'SIGNATAIRE_LIEU','Lieu Signature','Signature Place',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Signatory'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'SIGNATAIRE_DATE','Date Signature','Signature Date',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Signatory'),1);

------DOCUMENTS ----------------------------------------------------
INSERT INTO SIAT_CT.FIELD_GROUP (ID,LABEL_EN,LABEL_FR) VALUES (SIAT_CT.FIELD_GROUP_SEQ.NEXTVAL,'Documents','Documents');

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'DOCUMENTS_NUMERO_DI','Num�ro DI','DI Number',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Documents'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'DOCUMENTS_NUMERO_VTP','Num�ro VTP','VTP Number',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Documents'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'DOCUMENTS_NUMERO_VTD','Num�ro VTD','VTD Number',0,(SELECT fg.ID FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Documents'),1);

/*======================== D�finir les champs suppl�mentaires des marchandises des dossiers pour la proc�dure CCS_MINSANTE =========================================*/
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (FILE_ITEM_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'AMM','AMM','AMM',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (FILE_ITEM_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'MODE_EMBALAGE','Mode emballage','Packaging Mode',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (FILE_ITEM_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'DESCRIPTION','Description','Description',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (FILE_ITEM_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'POIDS','Poids','Weight',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (FILE_ITEM_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'UNITE','Unit�','Unit',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (FILE_ITEM_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'VOLUME','Volume','Volume',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (FILE_ITEM_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'NOM_COMMERCIAL','Nom Commercial','Trade Name',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (FILE_ITEM_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='CCS_MINSANTE'),'NOMBRE_COLIS','Nombre de colis','Packages count',1,1,0);
