UPDATE SIAT_CT.MINISTRY m SET m.CODE = 'MINEPIA' WHERE m.ID = 27;
/*========================= Ajout de la procédure Visa Technique MINEPIA =============================*/
---UPDATE SIAT_CT.FILE_TYPE ft SET ft.CODE = 'VT_MINEPIA_BACKUP' WHERE ft.CODE = 'VT_MINEPIA';
---INSERT INTO FILE_TYPE (ID, CODE, LABEL_EN, LABEL_FR) VALUES (FILE_TYPE_SEQ.nextVal,'VT_MINEPIA', 'Visa Technique MINEPIA', 'Visa Technique MINEPIA');
/*========================= Affecter la procédure VT_MINEPIA au Ministère MINEPIA ===================*/
INSERT INTO MINISTRY_FILE_TYPE (MINISTRY_ID, FILE_TYPE_ID) VALUES ((SELECT m.ID FROM SIAT_CT.MINISTRY m WHERE m.CODE='MINEPIA'), (SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'));
/*========================  Affecter la procédure VT_MINEPIA à un service =========================================*/
INSERT INTO FILE_TYPE_SERVICE (ID,FILE_TYPE_ID,SERVICE_ID) VALUES (FILE_TYPE_SERVICE_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),(SELECT ser.ID FROM SIAT_CT.SERVICE ser WHERE ser.ABREVIATION='SSAD'));
/*========================= Définir les rôles qui ont accès à la procédure ================================*/
INSERT INTO FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'), (SELECT auth.ID FROM SIAT_CT.AUTHORITY auth WHERE auth.ROLE = 'SUPER'));
INSERT INTO FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'), (SELECT auth.ID FROM SIAT_CT.AUTHORITY auth WHERE auth.ROLE = 'AR'));
INSERT INTO FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'), (SELECT auth.ID FROM SIAT_CT.AUTHORITY auth WHERE auth.ROLE = 'CA'));
INSERT INTO FILE_TYPE_AUTHORITY (FILE_TYPE_ID, AUTHORITY_ID) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'), (SELECT auth.ID FROM SIAT_CT.AUTHORITY auth WHERE auth.ROLE = 'SIGN'));
/*======================== Définir les étapes de la procédure, si elles n'existent pas il faut les créer, ensuite affecter à ces étapes les rôles qui ont accès à ces dernières et enfin affecter ces étapes à la
procédure VT_MINEPIA =========================================*/
---- Création de l'étape de signature de la modification pour la procédure visa technique MINEPIA -----------------
INSERT INTO STEP (ID, IS_FINAL, LABELEN, LABELFR, CODE) VALUES (STEP_SEQ.nextVal, 0, 'Signature Modification of Technical Visa', 'Signature Modification du visa techique', 'ST_AP_VT1_01' );

--- Definition des roles succeptibles d'exécuter cette étape de la procédure ----------------------------
INSERT INTO STEP_AUTHORITY (STEP_ID, AUTHORITY_ID) VALUES ((SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_AP_VT1_01'), (SELECT auth.ID FROM SIAT_CT.AUTHORITY auth WHERE auth.ROLE = 'SIGN'));

---- 1- ST_AP_42 (Dépôt des visa technique). Elle existe déjà. -----------------------
---- 2- ST_AP_46 (Recevabilité). Elle existe déjà. -----------------------------------
---- 5- ST_AP_64 (Paiement). Elle existe déjà. ------------------------------
---- 4- ST_AP_54 (Signature du visa technique). Elle existe déjà. --------------------
---- 5- ST_AP_VT1_01 (Signature Demande de modification). Elle n'existe pas. -----------------------------------
---- 6- ST_AP_43 (Rejet de la demande de visa technique). Elle existe déjà. ----------
---- 7- ST_AP_44 (Authorisation du visa technique). Elle existe déjà. ----------------

------------ Les rôles nécessaires ont déjà été affectées à ces différentes étapes --------------------------

-------Suppression des steps existantes de la procédure VT_MINEPIA -------------------
DELETE FROM SIAT_CT.FILE_TYPE_STEP fts WHERE fts.FILE_TYPE_ID = (SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE = 'VT_MINEPIA');
------------ Affecter ces étapes à la procédure VT_MINEPIA ----------------------------------------------
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_AP_42'), 0, 'Folder filing for a Technical Visa', 'Dépôt de dossier du Visa Technique');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_AP_43'), 0, 'Reject a Technical Visa file', 'Rejet de dossier de Visa Technique');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_AP_44'), 0, 'Validation of the Technical Visa', 'Validation de Visa Technique');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_AP_46'), 0, 'Admissibility of a Technical Visa', 'Recevabilité de Visa Technique');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_AP_64'), 1, 'Visa Fees Payment', 'Paiement des frais de visa');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_AP_54'), 0, 'Signature of the of Technical Visa file', 'Signature du dossier de Visa Technique');
INSERT INTO FILE_TYPE_STEP (FILE_TYPE_ID, STEP_ID, IS_AP_DECISION, LABEL_EN, LABEL_FR) VALUES ((SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_AP_VT1_01'), 0, 'Signature of the of Modification Technical Visa', 'Signature Modification du visa technique');

/*======================== Définir les décisions de la procédure, si elles n'existent pas il faut les créer et enfin affecter ces décisions à la
procédure VT_MINEPIA =========================================*/

---Création du flow pour passer de l'étape de dépôt à l'étape de paiement ----------------
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES (FLOW_SEQ.nextVal, 'FL_AP_VT1_01',24, 0,'Request technical visa', 'Demande de visa technique', 0, (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_AP_42'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_AP_64'));

---Création du flow pour passer de l'étape de recevabilité à l'étape de signature ----------------
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES (FLOW_SEQ.nextVal, 'FL_AP_VT1_02',24, 0,'Validation technical visa request for signature', 'Validation de demande de visa technique pour signature', 0, (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_AP_46'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_AP_54'));

---- Création d'un nouveau flow d'encaissement pour passer de l'étape de paiement à l'étape de recevabilité --------------
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES (FLOW_SEQ.nextVal, 'FL_AP_VT1_03',24, 0,'Encaissement des frais de visa', 'Payment visa fees', 1, (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_AP_64'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_AP_46'));

---- Création d'un nouveau flow pour retourner un dossier de sigature à un retour à l'étape de recevabilité --------------
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES (FLOW_SEQ.nextVal, 'FL_AP_VT1_04',24, 0,'Decision Refusal - Back to admissibility', 'Refus Décision - Retour à la recevabilité', 0, (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_AP_54'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_AP_46'));

---- Création d'un nouveau flow de reception de la demande de modification pour envoie à la recevabilité --------------
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES (FLOW_SEQ.nextVal, 'FL_AP_VT1_05',24, 0,'Modification Request Technical Visa', 'Demande de modifcation du visa technique', 0, (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_AP_42'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_AP_VT1_01'));

---- Création d'un nouveau flow de validation de la demande de modification du visa technique --------------
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES (FLOW_SEQ.nextVal, 'FL_AP_VT1_06',24, 0,'Validation Modification Request of Technical Visa', 'Validation Modification du visa technique', 1, (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_AP_VT1_01'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_AP_44'));

---- Création d'un nouveau flow de rejet de la demande de modification du visa technique --------------
INSERT INTO FLOW (ID, CODE, DURATION, IS_COTA, LABELEN, LABELFR, OUTGOING, FROM_STEP, TO_STEP) VALUES (FLOW_SEQ.nextVal, 'FL_AP_VT1_07',24, 0,'Rejection of Modification Request of Technical Visa', 'Rejet Modification du visa technique', 1, (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_AP_VT1_01'), (SELECT st.ID FROM SIAT_CT.STEP st WHERE st.CODE = 'ST_AP_43'));

---- Ajout des champs à renseigner lors de la prise de cette décision ----------------
INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, LABEL_EN, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_AP_VT1_02'), 'Observation', 'Observation',  0, 'inputTextarea' );

INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, LABEL_EN, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_AP_VT1_04'), 'Observation', 'Observation',  0, 'inputTextarea' );

INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, LABEL_EN, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_AP_VT1_05'), 'Observation', 'Observation',  0, 'inputTextarea' );

INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, LABEL_EN, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_AP_VT1_06'), 'Observation', 'Observation',  0, 'inputTextarea' );

INSERT INTO DATA_TYPE (ID, FLOW_ID, LABEL, LABEL_EN, REQUIRED, TYPE) VALUES (DATA_TYPE_SEQ.nextVal, (SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_AP_VT1_07'), 'Observation', 'Observation',  0, 'inputTextarea' );

---- 1- ST_AP_42 (Dépôt des visa technique). Elle existe déjà. -----------------------
    ----- 1- FL_AP_VT1_01 (Visa Technique du MINEPIA)
	----- 1- FL_AP_VT1_05 (Demande de modification visa technique)
---- 2- ST_AP_46 (Recevabilité). Elle existe déjà. -----------------------------------
    ----- 1- FL_AP_86 (Complément d'information suite recevabilité) ------------------
    ----- 2- FL_AP_87 (Rejet du Visa Technique suite recevabilité) -------------------
    ----- 3- FL_AP_VT1_02 (Validation du Visa Technique pour signature) -------------------
---- 3- ST_AP_64 (Paiement). Elle existe déjà. --------------------
    ---- 1- FL_AP_VT1_03 (Encaissement) ----------------------------------
---- 4- ST_AP_54 (Signature du visa technique). Elle existe déjà. --------------------
    ---- 1- FL_AP_107 (Autorisation Visa Technique) ----------------------------------
    ---- 2- FL_AP_VT1_04 (Refus Signature - Retour vers recevabilité ---------------
---- 5- ST_AP_VT1_01 (Signature Demande de modification). Elle n'existe pas. --------------------
    ---- 1- FL_AP_VT1_06 (Autorisation Modification Visa Technique ) ----------------------------------
    ---- 2- FL_AP_VT1_07 (Rejet Demande de modification du Visa) ---------------
---- 6- ST_AP_43 (Rejet de la demande de visa technique). Elle existe déjà. ----------
---- 7- ST_AP_44 (Authorisation du visa technique). Elle existe déjà. ----------------

--------------Suppression des flows de la procédure VT_MINEPIA -----------------------
DELETE FROM SIAT_CT.FILE_TYPE_FLOW ftf WHERE ftf.FILE_TYPE_ID = (SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE = 'VT_MINEPIA');
---- 1- ST_AP_42 (Dépôt des visa technique). Elle existe déjà. -----------------------
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Request for Technical Visa','Demande de Visa Technique',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),(SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_AP_85'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Request Modification of Technical Visa','Demande modification du Visa Technique',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),(SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_AP_VT1_05'));
---- 2- ST_AP_46 (Recevabilité). Elle existe déjà. -----------------------------------
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Additional information for the Technical Visa','Complément d''information de Visa Technique',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),(SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_AP_86'));
---- INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Rejection of Technical Visa','Rejet de Visa Technique',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),(SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_AP_87'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Validation of the Technical Visa','Validation de Visa Technique',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),(SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_AP_VT1_02'));

---- 3- ST_AP_64 (Paiement). Elle existe déjà. -------------------------------------
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Payment visa fees','Encaissement des frais de visa',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),(SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_AP_VT1_03'));

---- 4- ST_AP_54 (Signature du visa technique). Elle existe déjà. --------------------
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Decision Refusal - Back to admissibility Visa','Refus Décision - Retour la recevabilité',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),(SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_AP_VT1_04'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Validation of the Technical Visa','Validation de Visa Technique',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),(SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_AP_107'));

---- 5- ST_AP_VT1_01 (Signature Demande de modification). Elle n'existe pas. --------------------
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Validation Modification Request of Technical Visa','Validation Modification du visa technique',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),(SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_AP_VT1_06'));
INSERT INTO FILE_TYPE_FLOW (LABEL_EN,LABEL_FR,FILE_TYPE_ID,FLOW_ID) VALUES ('Rejection of Modification Request of Technical Visa','Rejet Modification du visa technique',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),(SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_AP_VT1_07'));



/*========================  Définir les infirmations nécessaires pour l'impression des livrable de la procédure VT_MINEPIA =========================================*/
INSERT INTO FILE_TYPE_FLOW_REPORT(ID, REPORT_CLASS_NAME, REPORT_NAME, FILE_FIELD_NAME, FILE_TYPE_ID, FLOW_ID, ORGANISM_ID) VALUES (FILE_TYPE_FLOW_REPORT_SEQ.nextVal, 'org.guce.siat.web.reports.exporter.VtMINEPIAExporter', 'VT_MINEPIA.pdf','NUMERO_VT_MINEPIA', (SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'), (SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_AP_107'), (SELECT org.ID FROM SIAT_CT.ORGANISM org WHERE org.ABREVIATION = 'DSV'));

INSERT INTO FILE_TYPE_FLOW_REPORT(ID, REPORT_CLASS_NAME, REPORT_NAME, FILE_FIELD_NAME, FILE_TYPE_ID, FLOW_ID, ORGANISM_ID) VALUES (FILE_TYPE_FLOW_REPORT_SEQ.nextVal, 'org.guce.siat.web.reports.exporter.VtMINEPIAExporter', 'VT_MINEPIA.pdf','NUMERO_VT_MINEPIA', (SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'), (SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_AP_VT1_06'), (SELECT org.ID FROM SIAT_CT.ORGANISM org WHERE org.ABREVIATION = 'DSV'));

--------------Suppression des flows guce siat de la procédure VT_MINEPIA -----------------------
DELETE FROM SIAT_CT.FLOW_GUCE_SIAT fgs WHERE fgs.FILE_TYPE_ID = (SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE = 'VT_MINEPIA');
/*========================  Définir les correspondances entre les flows SIAT et les flux entrants et sortants de orchestra pour la procédure VT_MINEPIA =========================================*/
--- UPDATE SIAT_CT.FLOW_GUCE_SIAT fgs SET fgs.FLOW_GUCE = fgs.FLOW_GUCE||'-OLD' WHERE fgs.FILE_TYPE_ID = (SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA');
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (FLOW_GUCE_SIAT_SEQ.nextVal,'VT101','FL_AP_85',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'));
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (FLOW_GUCE_SIAT_SEQ.nextVal,'VT102','FL_AP_86',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'));
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (FLOW_GUCE_SIAT_SEQ.nextVal,'VT103','FL_AP_87',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'));
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (FLOW_GUCE_SIAT_SEQ.nextVal,'VT104','FL_AP_107',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'));
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (FLOW_GUCE_SIAT_SEQ.nextVal,'VT1601','FL_AP_VT1_01',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'));
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (FLOW_GUCE_SIAT_SEQ.nextVal,'VT1602','FL_AP_VT1_03',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'));
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (FLOW_GUCE_SIAT_SEQ.nextVal,'VT109','FL_AP_VT1_05',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'));
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (FLOW_GUCE_SIAT_SEQ.nextVal,'VT110','FL_AP_VT1_06',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'));
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (FLOW_GUCE_SIAT_SEQ.nextVal,'VT103','FL_AP_VT1_07',(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'));
INSERT INTO FLOW_GUCE_SIAT (ID,FLOW_GUCE, FLOW_SIAT, FILE_TYPE_ID) VALUES (FLOW_GUCE_SIAT_SEQ.nextVal,'VT111',NULL,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'));

/*========================  Définir la correspondances entre les informations pour la génération du visa technique et  =========================================*/
INSERT INTO REPORT_ORGANISM( ID,  SEQUENCE,  VALUE, FILE_TYPE_FLOW_REPORT, ORGANISM)VALUES( REPORT_ORGANISME_SEQ.nextVal,  0,  '/VTMINEPIA/MINEPIA/DSV/SDPSE/SSAD/',  (SELECT ftfr.ID FROM SIAT_CT.FILE_TYPE_FLOW_REPORT ftfr WHERE ftfr.FILE_FIELD_NAME ='NUMERO_VT_MINEPIA' AND FLOW_ID = (SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_AP_107')),  (SELECT org.ID FROM SIAT_CT.ORGANISM org WHERE org.ABREVIATION='DSV'));

INSERT INTO REPORT_ORGANISM( ID,  SEQUENCE,  VALUE, FILE_TYPE_FLOW_REPORT, ORGANISM)VALUES( REPORT_ORGANISME_SEQ.nextVal,  0,  '/VTMINEPIA/MINEPIA/DSV/SDPSE/SSAD/',  (SELECT ftfr.ID FROM SIAT_CT.FILE_TYPE_FLOW_REPORT ftfr WHERE ftfr.FILE_FIELD_NAME ='NUMERO_VT_MINEPIA'  AND FLOW_ID = (SELECT f.ID FROM SIAT_CT.FLOW f WHERE f.CODE = 'FL_AP_VT1_06')),  (SELECT org.ID FROM SIAT_CT.ORGANISM org WHERE org.ABREVIATION='DSV'));

/*======================== Définir les champs supplémentaires des dossiers pour la procédure VT_MINEPIA =========================================*/
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'CODE_BUREAU','Code Bureau','Office Code',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'General'),1);



---------------------------------- FOURNISSEUR --------------
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'FOURNISSEUR_RAISONSOCIALE','Raison Sociale','Name/Business Name',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'FOURNISSEUR_Sigle','Sigle','Acronym',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'FOURNISSEUR_ADRESSE_ADRESSE1','Adresse (Adresse 1)','Address (Address 1)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'FOURNISSEUR_ADRESSE_ADRESSE2','Adresse (Adresse 2)','Address (Address 2)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'FOURNISSEUR_ADRESSE_BP','Adresse (BP)','Address (P.O. Box)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'FOURNISSEUR_ADRESSE_PAYSADDRESS_CODEPAYS','Adresse Pays (Code Pays)','Address Country (Country Code)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'FOURNISSEUR_ADRESSE_PAYSADDRESS_NOMPAYS','Adresse Pays (Nom Pays)','Address Country (Country Name)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'FOURNISSEUR_ADRESSE_VILLE','Adresse (Ville)','Address (City)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'FOURNISSEUR_ADRESSE_ADRESSEELECTRONIQUE','Adresse (Adresse Électronique)','Address (e-mail Address)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'FOURNISSEUR_ADRESSE_SITEWEB','Adresse (Site Web)','Address (Web Site)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'FOURNISSEUR_TELEPHONE_FIXE_INDICATIFPAYS','Téléphone Fixe (Indicatif Pays)','Telephone (Country Dialing Code)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'FOURNISSEUR_TELEPHONE_FIXE_NUMERO','Téléphone Fixe (Numéro)','Telephone (Number)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'FOURNISSEUR_TELEPHONE_MOBILE_INDICATIFPAYS','Téléphone Mobile (Indicatif Pays)','Mobile Phone (Country Dialing Code)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'FOURNISSEUR_TELEPHONE_MOBILE_NUMERO','Téléphone Mobile (Numéro)','Mobile Phone (Number)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'FOURNISSEUR_FAX_INDICATIFPAYS','Fax (Indicatif Pays)','Fax (Country Dialing Code)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'FOURNISSEUR_FAX_NUMERO','Fax (Numéro)','Fax (Number)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Provider'),1);


---------------------------------- TRANSITAIRE --------------

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'TRANSITAIRE_RAISONSOCIALE','Raison Sociale','Name/Business Name',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'TRANSITAIRE_Sigle','Sigle','Acronym',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'TRANSITAIRE_ADRESSE_ADRESSE1','Adresse (Adresse 1)','Address (Address 1)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'TRANSITAIRE_ADRESSE_ADRESSE2','Adresse (Adresse 2)','Address (Address 2)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'TRANSITAIRE_ADRESSE_BP','Adresse (BP)','Address (P.O. Box)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'TRANSITAIRE_ADRESSE_PAYSADDRESS_CODEPAYS','Adresse Pays (Code Pays)','Address Country (Country Code)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'TRANSITAIRE_ADRESSE_PAYSADDRESS_NOMPAYS','Adresse Pays (Nom Pays)','Address Country (Country Name)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'TRANSITAIRE_ADRESSE_VILLE','Adresse (Ville)','Address (City)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'TRANSITAIRE_ADRESSE_ADRESSEELECTRONIQUE','Adresse (Adresse Électronique)','Address (e-mail Address)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'TRANSITAIRE_ADRESSE_SITEWEB','Adresse (Site Web)','Address (Web Site)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'TRANSITAIRE_TELEPHONE_FIXE_INDICATIFPAYS','Téléphone Fixe (Indicatif Pays)','Telephone (Country Dialing Code)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'TRANSITAIRE_TELEPHONE_FIXE_NUMERO','Téléphone Fixe (Numéro)','Telephone (Number)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'TRANSITAIRE_TELEPHONE_MOBILE_INDICATIFPAYS','Téléphone Mobile (Indicatif Pays)','Mobile Phone (Country Dialing Code)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'TRANSITAIRE_TELEPHONE_MOBILE_NUMERO','Téléphone Mobile (Numéro)','Mobile Phone (Number)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'TRANSITAIRE_FAX_INDICATIFPAYS','Fax (Indicatif Pays)','Fax (Country Dialing Code)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'TRANSITAIRE_FAX_NUMERO','Fax (Numéro)','Fax (Number)',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Freight Forwarder'),1);


---------------------------------- FACTURE --------------
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'FACTURE_NUMERO_FACTURE','Numéro facture','Bill number',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Bill'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'FACTURE_DATE_FACTURE','Date de la facture','Bill Date',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Bill'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'FACTURE_NUMERO_BL','Numero BL','BL Number',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Bill'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'FACTURE_NUMERO_VOYAGE','Numero Voyage','Travel Number',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Bill'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'FACTURE_DATE_ARRIVEE','Date arrivée','Arrival Date',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Bill'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'FACTURE_DATE_DEPART','Date depart','Departure Date',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Bill'),1);

---------------------------------- TRANSPORT --------------
 ------------------FIELD_GROUP-----------------------------
INSERT INTO SIAT_CT.FIELD_GROUP (ID,LABEL_EN,LABEL_FR) VALUES (SIAT_CT.FIELD_GROUP_SEQ.NEXTVAL,'Transport','Transport');

------------------FILE_FIELD-------------------------------

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'TRANSPORT_MODE_TRANSPORT_CODE','Code Mode Transport','Transport Mode Code',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Transport'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'TRANSPORT_MODE_TRANSPORT_LIBELLE','Libellé MOde Transport','Transport Mode Label',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Transport'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'TRANSPORT_LIEU_CHARGEMENT_UNLOCODE','Code Lieu chargement','charging Place Code',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Transport'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'TRANSPORT_LIEU_CHARGEMENT_LIBELLE','Libellé Lieu chargement','charging Place Label',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Transport'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'TRANSPORT_LIEU_DEDOUANEMENT_UNLOCODE','Code Lieu Dedouanement','Discharging Place Code',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Transport'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'TRANSPORT_LIEU_DEDOUANEMENT_LIBELLE','Libellé Lieu Dédouanement','Dischargin Place Label',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Transport'),1);

------GENERAL ----------------------------------------------------
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'NUMERO_VT_MINEPIA','Numéro Certificat','Certificat number',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'General'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'VT_MINEPIA_DATE','Date de signature','Signature date',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'General'),1);
------SIGNATAIRE ----------------------------------------------------
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'SIGNATAIRE_NOM','Nom Signataire','Signatory Name',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Signatory'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'SIGNATAIRE_QUALITE','Qualité Signataire','Signatory Function',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Signatory'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'SIGNATAIRE_LIEU','Lieu Signature','Signature Place',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Signatory'),1);
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'SIGNATAIRE_DATE','Date Signature','Signature Date',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Signatory'),1);

------OBSERVATION ----------------------------------------------------
INSERT INTO SIAT_CT.FIELD_GROUP (ID,LABEL_EN,LABEL_FR) VALUES (SIAT_CT.FIELD_GROUP_SEQ.NEXTVAL,'Observations','Observations');
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'INFORMATIONS_GENERALES_OBSERVATIONS','Observations','Observations',0,(SELECT MAX(fg.ID) FROM SIAT_CT.FIELD_GROUP fg WHERE fg.LABEL_EN = 'Observations'),1);

/*======================== Définir les champs supplémentaires des marchandises des dossiers pour la procédure VT_MINEPIA =========================================*/
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (FILE_ITEM_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'AMM','AMM','AMM',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (FILE_ITEM_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'MODE_EMBALAGE','Mode emballage','Packaging Mode',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (FILE_ITEM_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'DESCRIPTION','Description','Description',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (FILE_ITEM_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'POIDS','Poids','Weight',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (FILE_ITEM_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'UNITE','Unité','Unit',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (FILE_ITEM_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'VOLUME','Volume','Volume',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (FILE_ITEM_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'NOM_COMMERCIAL','Nom Commercial','Trade Name',1,1,0);
INSERT INTO FILE_ITEM_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,GROUP_ID,UPDATABLE,REPEATABLE) VALUES (FILE_ITEM_FIELD_SEQ.nextVal,(SELECT ft.ID FROM SIAT_CT.FILE_TYPE ft WHERE ft.CODE='VT_MINEPIA'),'NOMBRE_COLIS','Nombre de colis','Packages count',1,1,0);



INSERT INTO BUREAU_GUCE_SIAT (BUREAU_GUCE, BUREAU_SIAT) VALUES ('MINEPIA_DLA', 'BC-SSAD');
INSERT INTO BUREAU_GUCE_SIAT (BUREAU_GUCE, BUREAU_SIAT) VALUES ('MINEPIA_KRIBI', 'BC-SSAD');