UPDATE SIAT_CT.FILE_FIELD SET GROUP_ID = 91 WHERE CODE LIKE 'TRANSPORT%' AND FILE_TYPE_ID = 60;
UPDATE SIAT_CT.FILE_FIELD SET GROUP_ID = 92 WHERE CODE LIKE 'DOCUMENTS%' AND FILE_TYPE_ID = 60;
UPDATE SIAT_CT.FILE_FIELD SET GROUP_ID = 12 WHERE CODE LIKE 'INFORMATIONS_GENERALES_REFERENCE_OBSERVATIONS' AND FILE_TYPE_ID = 60;
