/**
 * Author:  tadzotsa
 * Created: 10-Feb-2021
 */

-- PAYS_ORIGINE
-- CODE
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'),'INFORMATIONS_GENERALES_PAYS_ORIGINE_CODEPAYS','Code Pays Origine','Origin Country Code',0,12,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),'INFORMATIONS_GENERALES_PAYS_ORIGINE_CODEPAYS','Code Pays Origine','Origin Country Code',0,12,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_ATP'),'INFORMATIONS_GENERALES_PAYS_ORIGINE_CODEPAYS','Code Pays Origine','Origin Country Code',0,12,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E'),'INFORMATIONS_GENERALES_PAYS_ORIGINE_CODEPAYS','Code Pays Origine','Origin Country Code',0,12,0);
-- NOM
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'),'INFORMATIONS_GENERALES_PAYS_ORIGINE_NOMPAYS','Nom Pays Origine','Origin Country Name',0,12,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),'INFORMATIONS_GENERALES_PAYS_ORIGINE_NOMPAYS','Nom Pays Origine','Origin Country Name',0,12,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_ATP'),'INFORMATIONS_GENERALES_PAYS_ORIGINE_NOMPAYS','Nom Pays Origine','Origin Country Name',0,12,0);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E'),'INFORMATIONS_GENERALES_PAYS_ORIGINE_NOMPAYS','Nom Pays Origine','Origin Country Name',0,12,0);

-- PAYS_DESTINATION
-- CODE
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'),'INFORMATIONS_GENERALES_PAYS_DESTINATION_CODEPAYS','Code Pays Destination','Destination Country Code',0,12,1);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),'INFORMATIONS_GENERALES_PAYS_DESTINATION_CODEPAYS','Code Pays Destination','Destination Country Code',0,12,1);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_ATP'),'INFORMATIONS_GENERALES_PAYS_DESTINATION_CODEPAYS','Code Pays Destination','Destination Country Code',0,12,1);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E'),'INFORMATIONS_GENERALES_PAYS_DESTINATION_CODEPAYS','Code Pays Destination','Destination Country Code',0,12,1);
-- NOM
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_PVI'),'INFORMATIONS_GENERALES_PAYS_DESTINATION_NOMPAYS','Nom Pays Destination','Destination Country Name',0,12,1);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_FSTP'),'INFORMATIONS_GENERALES_PAYS_DESTINATION_NOMPAYS','Nom Pays Destination','Destination Country Name',0,12,1);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E_ATP'),'INFORMATIONS_GENERALES_PAYS_DESTINATION_NOMPAYS','Nom Pays Destination','Destination Country Name',0,12,1);
INSERT INTO SIAT_CT.FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES (SIAT_CT.FILE_FIELD_SEQ.NEXTVAL,(SELECT ID FROM SIAT_CT.FILE_TYPE WHERE CODE = 'CCT_CT_E'),'INFORMATIONS_GENERALES_PAYS_DESTINATION_NOMPAYS','Nom Pays Destination','Destination Country Name',0,12,1);
