
/*==============================================================*/
/* Table : FIELD_GROUP                                          */
/*==============================================================*/

/* Ajout du groupe qui régroupe les éléments du CVS */
INSERT INTO  FIELD_GROUP  (ID, LABEL_EN, LABEL_FR) VALUES ((SELECT MAX(ID) + 1 FROM FIELD_GROUP),'Details for SVC', 'Détails pour CVS');
COMMIT;

/*==============================================================*/
/* Table : FILE_FIELD                                          */
/*==============================================================*/

/* Ajout des attributs lié au CVS */
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'DATE_DEPART','Date de départ','Date of departure',0,(SELECT MAX(ID) FROM FIELD_GROUP),1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'TEMPERATURE_PRODUIT',' Température du produit',' Temperature of product',0,(SELECT MAX(ID) FROM FIELD_GROUP),1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'NOMBRE_UNITES_EMBALLES','Nombre d’unités emballées','Total number of packages',0,(SELECT MAX(ID) FROM FIELD_GROUP),1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'NATURE_EMBALLAGE','Nature de l''emballage','Type of packaging',0,(SELECT MAX(ID) FROM FIELD_GROUP),1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'MARCHANDISE_POUR','Marchandises certifiées à des fins de','Commodities intended for use as',0,(SELECT MAX(ID) FROM FIELD_GROUP),1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'MARCHANDISE_ESPECE','Espèces (Nom scientifique)','Species (Scientific name)',0,(SELECT MAX(ID) FROM FIELD_GROUP),1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'MARCHANDISE_NATURE','Nature de la marchandise','Nature of commodity',0,(SELECT MAX(ID) FROM FIELD_GROUP),1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'MARCHANDISE_TRAITEMENT','Type de traitement',' Treatment type',0,(SELECT MAX(ID) FROM FIELD_GROUP),1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'MARCHANDISE_NB_COLIS','Nombre de colis','Number of packages',0,(SELECT MAX(ID) FROM FIELD_GROUP),1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'MARCHANDISE_NB_APPROUVES','No d’agrément des établissements','Approved number of Establishments',0,(SELECT MAX(ID) FROM FIELD_GROUP),1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'MARCHANDISE_POIDS_NET','Poids net','Net weight',0,(SELECT MAX(ID) FROM FIELD_GROUP),1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'NO_PERMIS_CITES','No permis CITES','CITES permit No',0,(SELECT MAX(ID) FROM FIELD_GROUP),1);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'ID_CONTENEURS_SCELLES','Identification des conteneurs/No des scellés','Identification of container/seal number',0,(SELECT MAX(ID) FROM FIELD_GROUP),1);

COMMIT;


INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'REFERENCE_DOSSIER','Reference Dossier','File Reference',0,1,0);
COMMIT;

/*==============================================================*/
/* Table : FIELD_GROUP                                          */
/*==============================================================*/

/* Ajout du groupe qui régroupe les éléments du Destinataire */
INSERT INTO  FIELD_GROUP  (ID, LABEL_EN, LABEL_FR) VALUES ((SELECT MAX(ID) + 1 FROM FIELD_GROUP),'Recipient', 'Destinataire');
COMMIT;


/*==============================================================*/
/* Table : FILE_FIELD                                          */
/*==============================================================*/
/*Destinataire*/
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'DESTINATAIRE_RAISON_SOCIAL','Raison Sociale','Name/Business Name',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'DESTINATAIRE_ADRESSE1','Adresse 1','Address 1',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'DESTINATAIRE_ADRESSE2','Adressse 2','Address 2',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'DESTINATAIRE_BP','Boite Postale','PO Box',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'DESTINATAIRE_PAYS_CODE','Code Pays','Country Name',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'DESTINATAIRE_PAYS_NOM','Nom Pays','Country Name',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'DESTINATAIRE_VILLE','Ville','Town',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'DESTINATAIRE_EMAIL','Email','Email',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'DESTINATAIRE_SITE_WEB','Site Web','Website',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);

COMMIT;


/*==============================================================*/
/* Table : FIELD_GROUP                                          */
/*==============================================================*/

/* Ajout du groupe qui régroupe les éléments du Expéditeur */
INSERT INTO  FIELD_GROUP  (ID, LABEL_EN, LABEL_FR) VALUES ((SELECT MAX(ID) + 1 FROM FIELD_GROUP),'Consignor', 'Expéditeur');
COMMIT;


/*==============================================================*/
/* Table : FILE_FIELD                                          */
/*==============================================================*/
/*Expéditeur*/
INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'EXPEDITEUR_RAISON_SOCIAL','Raison Sociale','Name/Business Name',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);


INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'EXPEDITEUR_NUMERO_CONTRIBUABLE','Numéro Contribuable','Tax Payer Number',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);


INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'EXPEDITEUR_ADRESSE1','Adresse 1','Address 1',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);


INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'EXPEDITEUR_ADRESSE2','Adresse 2','Address 2',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);


INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'EXPEDITEUR_BP','Boite Postale','PO Box',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'EXPEDITEUR_PAYS_CODE','Code Pays','Country Name',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'EXPEDITEUR_PAYS_NOM','Nom Pays','Country Name',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'EXPEDITEUR_VILLE','Ville','Town',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'EXPEDITEUR_EMAIL','Email','Email',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'EXPEDITEUR_SITE_WEB','Site Web','Website',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);


INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'EXPEDITEUR_TELEPHONE_MOBILE_INDICATIF','Indicatif mobile','Mobile prefix',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);


INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'EXPEDITEUR_TELEPHONE_MOBILE_NUMERO','Numero Mobile','Mobule Number',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);

INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'EXPEDITEUR_TELEPHONE_FIXE_INDICATIF','Indicatif Fixe','Home prefix',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);


INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'EXPEDITEUR_TELEPHONE_FIXE_NUMERO','Numero Fixe','Home Number',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);


INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'EXPEDITEUR_TELEPHONE_FAX_INDICATIF','Indicatif Fax','Fax Prefix',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);


INSERT INTO FILE_FIELD (ID,FILE_TYPE_ID,CODE,LABEL_FR,LABEL_EN,REPEATABLE,GROUP_ID,UPDATABLE) VALUES ((SELECT MAX(ID) + 1 FROM FILE_FIELD),19,'EXPEDITEUR_TELEPHONE_FAX_NUMERO','Numero Fax','Fax Number',0,(SELECT MAX(ID) FROM FIELD_GROUP),0);

COMMIT;
